// CRC: C09139DD0A75D64CECB6A655701556EC04E7A0BAAEC1407B0F4C89EF6364E65A25403FAB33447FAB66D2C71EAC4D3E5A920BE72345EF4485BD63C62E7661FB35FFB85386900EA5FE3557084443D810B26D1F95C708D07462464D59A39C9F4F55B3277527469C5BEA5CDE1F8D43685DD5B320FFFB2B1F58F1BC383A35532066CC5FA0E62B037F1A5CAEF80DBA3F4D0A5034FE7E059A9D27FD7F02557D29A407E5ABC2C2431F6C4065B2B59391F7DFE3FBA4BAF1B34E38B68E0C3CAEE8E7DA69876E94163B353B2B9147B5A286B0BCE912624BA8C7773A74E3D418C494B920E55DA5ABD32164F66AD7EA1D8650225DE110A301A9B77579B8A35C72326EE5818C573EA0303FF1C80C38296E843F2A9EAEFD502990E2AF2DF044549D34A0D5AD11F3540782CCC185C44AA3F7649503E74408EB266342FA52B3F076D3E34736BD7539F516F4BDFF4A1CBE
// REVISION: 1.0
// GUID: 8753B786-44F2-47CB-97E7-47BB1FB33EAC
// DATE: 15\12\2025
// DIR: Misc\Templates\Sensors|and|microcontrollers\PIC\BL0144|dig|temp|sensor|-|PIC.h
//************************************************************************************
//**  
//**  Source name:   \\IRONMAN-PC2\Dev\Flowcode V11\Examples\Templates\Sensors and microcontrollers\PIC\BL0144 dig temp sensor - PIC.fcfx
//**  Title:         BL0144 dig temp sensor - PIC
//**  Description:   
//**  Device:        PIC.18F.E-blocks3 8-bit PIC
//**  
//**  Generated by:  Flowcode v11.0.0.8
//**  Date:          Monday, December 15, 2025 14:48:16
//**  Users:         1
//**  Registered to: JohnD (65060919)
//**  Licence key: MNBNUH
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#define MX_PIC

#define MX_CAL_PIC

#define MX_CLK_SPEED 64000000

#define FCP_NULL Unconnected_Port

#define MX_PWM_NEW_TMR_CONF2
#include <xc.h>
#include <math.h>

/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\internals.c"



MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;
MX_UINT8 FCLV_LOOP3;
MX_UINT8 FCLV_LOOP4;
MX_UINT32 FCLV_LOOP5;
MX_UINT32 FCLV_LOOP6;
MX_UINT32 FCLV_LOOP7;
MX_UINT32 FCLV_LOOP8;
MX_UINT32 FCLV_LOOP9;

MX_UINT8 FCD_01211_RXCB__LookForValue(MX_CHAR *FCL_VALUE, MX_UINT16 FCLsz_VALUE, MX_UINT8 FCL_NUMCHARS, MX_UINT8 FCL_REMOVECONTENT, MX_UINT8 FCL_RESETFIND);
void FCD_01211_RXCB__GetArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
void FCD_01211_RXCB__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL, MX_UINT16 FCL_MAXLENGTH);
void FCD_01211_RXCB__PutArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
MX_UINT8 FCD_01211_RXCB__GetIndexedByte(MX_UINT16 FCL_ADDRESS);
MX_UINT8 FCD_01211_RXCB__WaitForValue(MX_CHAR *FCL_VALUE, MX_UINT16 FCLsz_VALUE, MX_UINT8 FCL_NUMCHARS, MX_UINT8 FCL_REMOVECONTENT, MX_UINT16 FCL_TIMEOUT);
MX_UINT16 FCD_01211_RXCB__GetNumberBytes();
MX_UINT16 FCD_01211_RXCB__PeekByte();
void FCD_01211_RXCB__PutString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
MX_UINT8 FCD_01211_RXCB__PutByte(MX_UINT8 FCL_DATA);
MX_UINT16 FCD_01211_RXCB__GetByte();
MX_UINT16 FCD_01211_RXCB__GetSize(MX_BOOL FCL_MODE);
void FCD_01211_RXCB__FlushBuffer();

/*========================================================================*\
   Use :TypeConversionsFree1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :TypeConversionsFree1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifndef MX_UNIONTYPE
 #define MX_UNIONTYPE
 typedef union
{
  MX_FLOAT AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union_Type;
 MX_Union_Type MX_Conv_Var;
#endif


void FCD_02571_TypeConversionsFree1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE);
void FCD_02571_TypeConversionsFree1__SetLong(MX_UINT32 FCL_VALUE);
MX_FLOAT FCD_02571_TypeConversionsFree1__GetFloat();
MX_UINT32 FCD_02571_TypeConversionsFree1__GetLong();
MX_UINT16 FCD_02571_TypeConversionsFree1__GetInt(MX_UINT8 FCL_INDEX);
void FCD_02571_TypeConversionsFree1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE);
MX_UINT8 FCD_02571_TypeConversionsFree1__GetByte(MX_UINT8 FCL_INDEX);
void FCD_02571_TypeConversionsFree1__SetFloat(MX_FLOAT FCL_VALUE);

/*========================================================================*\
   Use :UART1
       :Macro function declarations
\*========================================================================*/
#define MX_UART_UseTX_1 (1)
#define MX_UART_TX_TRIS_1 trisg
#define MX_UART_REF1 
#define MX_UART_RTS_PIN_1 (4)
#define MX_UART_DBITS_1 (8)
#define MX_UART_RETURN_1 (1)
#define MX_UART_RX_PORT_1 portg
#define MX_UART_RTS_PORT_1 portc
#define MX_UART_ECHO_1 (0)
#define MX_UART_FLOWEN_1 (0)
#define MX_UART_CTS_PORT_1 portc
#define MX_UART_TX_PIN_1 (0)
#define MX_UART_RX_TRIS_1 trisg
#define MX_UART_BAUD_1 (115200)
#define MX_UART_RTS_TRIS_1 trisc
#define MX_UART_TX_PORT_1 portg
#define MX_UART_RX_PIN_1 (1)
#define MX_UART_UseRX_1 (1)
#define MX_UART_CTS_TRIS_1 trisc
#define MX_UART_CHANNEL_1 (2)
#define MX_UART_INT_1 (0)
#define MX_UART_CTS_PIN_1 (5)

MX_UINT8 FCD_05481_UART1__ControlPin(MX_UINT8 FCL_PIN, MX_UINT8 FCL_STATE);
void FCD_05481_UART1__SendString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
void FCD_05481_UART1__Prv_TextConsole(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT8 FCL_COLOUR);
void FC_CAL_UART_UpdateBaud_1(MX_UINT8 FCL_NEW_BAUD);
MX_UINT8 FCD_05481_UART1__TestProperty(MX_UINT8 FCL_PROPERTY);
void FCD_05481_UART1__SendNumber(MX_SINT32 FCL_NUMBER);
void FCD_05481_UART1__Prv_SimShowWaveform(MX_UINT8 FCL_TXRX, MX_UINT16 FCL_DATA);
MX_SINT16 FC_CAL_UART_Receive_1(MX_UINT8 FCL_TIMEOUT);
void FC_CAL_UART_Send_1(MX_UINT16 FCL_CHAR);
void FCD_05481_UART1__SendByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
void FC_CAL_UART_Init_1();
void FC_CAL_UART_Delay_1();
void FC_CAL_UART_Uninit_1();
MX_UINT8 FCD_05481_UART1__ReceiveByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT);
MX_UINT8 FCD_05481_UART1__ReceiveString(MX_CHAR *FCL_STRINGDATA, MX_UINT16 FCLsz_STRINGDATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT);
MX_UINT16 FCD_00fb8_WidthData__GetLUTCount();
MX_UINT16 FCD_00fb7_ASCIIData__GetLUTCount();
MX_UINT32 FCD_09e54_gLCD_Font4__SumWidths(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_09e54_gLCD_Font4__ReadWidth(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_09e54_gLCD_Font4__ReadFontStat(MX_UINT8 FCL_INDEX);
MX_UINT8 FCD_09e54_gLCD_Font4__ReadASCIILUT(MX_UINT8 FCL_CHARACTER, MX_UINT16 FCL_BYTEINDEX);
MX_UINT16 FCD_00fb6_WidthData__GetLUTCount();
MX_UINT16 FCD_00fb5_ASCIIData__GetLUTCount();
MX_UINT32 FCD_09e53_gLCD_Font3__SumWidths(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_09e53_gLCD_Font3__ReadWidth(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_09e53_gLCD_Font3__ReadFontStat(MX_UINT8 FCL_INDEX);
MX_UINT8 FCD_09e53_gLCD_Font3__ReadASCIILUT(MX_UINT8 FCL_CHARACTER, MX_UINT16 FCL_BYTEINDEX);
MX_UINT16 FCD_00fb4_WidthData__GetLUTCount();
MX_UINT16 FCD_00fb3_ASCIIData__GetLUTCount();
MX_UINT32 FCD_09e52_gLCD_Font2__SumWidths(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_09e52_gLCD_Font2__ReadWidth(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_09e52_gLCD_Font2__ReadFontStat(MX_UINT8 FCL_INDEX);
MX_UINT8 FCD_09e52_gLCD_Font2__ReadASCIILUT(MX_UINT8 FCL_CHARACTER, MX_UINT16 FCL_BYTEINDEX);
MX_UINT16 FCD_00fb2_WidthData__GetLUTCount();
MX_UINT16 FCD_00fb1_ASCIIData__GetLUTCount();
MX_UINT32 FCD_09e51_gLCD_Font1__SumWidths(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_09e51_gLCD_Font1__ReadWidth(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_09e51_gLCD_Font1__ReadFontStat(MX_UINT8 FCL_INDEX);
MX_UINT8 FCD_09e51_gLCD_Font1__ReadASCIILUT(MX_UINT8 FCL_CHARACTER, MX_UINT16 FCL_BYTEINDEX);

/*========================================================================*\
   Use :Base_GLCD
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Base_GLCD
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define ReadFontWidth(FONT, CHAR) FCD_0ba71_Base_GLCD__ReadFontWidth(FONT, CHAR)
#define ReadFontStat(FONT, IDX) FCD_0ba71_Base_GLCD__ReadFontStat(FONT, IDX)


MX_UINT32 FCD_0ba71_Base_GLCD__Prv_SumWidths(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_0ba71_Base_GLCD__ReadFontWidth(MX_UINT8 FCL_FONT, MX_UINT8 FCL_CHARACTER);
void FCD_0ba71_Base_GLCD__Prv_ReadFontFileHeader(MX_UINT8 FCL_FONT);
MX_UINT8 FCD_0ba71_Base_GLCD__ReadFontStat(MX_UINT8 FCL_FONT, MX_UINT8 FCL_INDEX);
void FCD_0ba71_Base_GLCD__SetExternalFont(MX_UINT8 FCL_FONT, MX_CHAR *PFCL_FILENAME, MX_UINT8 FCL_CHARACTERSPACING, MX_UINT8 FCL_SPACEWIDTH);
MX_UINT8 FCD_0ba71_Base_GLCD__ReadFontByte(MX_UINT8 FCL_FONT, MX_UINT8 FCL_CHARACTER, MX_UINT16 FCL_BYTEINDEX);

/*========================================================================*\
   Use :gLCD_EB3
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :gLCD_EB3
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_CAPTOUCH_SendCommand FCD_029f1_gLCD_EB3__SendCommand
#define MX_CAPTOUCH_SendCommandWithArray FCD_029f1_gLCD_EB3__SendCommandWithArray
#define MX_CAPTOUCH_SendCommandWithString FCD_029f1_gLCD_EB3__SendCommandWithString
#define MX_CAPTOUCH_SendCommandWithDualString FCD_029f1_gLCD_EB3__SendCommandWithDualString
#define MX_CAPTOUCH_SendBinaryScene FCD_029f1_gLCD_EB3__SendBinaryScene
#define MX_CAPTOUCH_SendBinaryAction FCD_029f1_gLCD_EB3__SendBinaryAction
#define MX_CAPTOUCH_GetByte FCD_01211_RXCB__GetByte
#define MX_CAPTOUCH_GetArray FCD_01211_RXCB__GetArray
#define MX_CAPTOUCH_GetString FCD_01211_RXCB__GetString
#define MX_CAPTOUCH_CommandTx FCV_029f1_gLCD_EB3__COMMANDTX
#define MX_CAPTOUCH_TxCount FCV_029f1_gLCD_EB3__TXCOUNT
#define MX_CAPTOUCH_RxCount FCV_029f1_gLCD_EB3__RXCOUNT

MX_UINT8 FCD_029f1_gLCD_EB3__ReceiveReply();
MX_UINT8 FCD_029f1_gLCD_EB3__ConnectWifi();
void FCD_029f1_gLCD_EB3__SetFontScaler(MX_UINT8 FCL_SCALEX, MX_UINT8 FCL_SCALEY);
MX_UINT8 FCD_029f1_gLCD_EB3__DrawBitmapScaled(MX_CHAR *FCL_FILENAME, MX_UINT16 FCLsz_FILENAME, MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT16 FCL_WIDTH, MX_UINT16 FCL_HEIGHT, MX_UINT8 FCL_ORIENTATION, MX_UINT8 FCL_TRANSPARENCY, MX_UINT8 FCL_FLIP);
MX_UINT8 FCD_029f1_gLCD_EB3__SendCommand();
MX_UINT8 FCD_029f1_gLCD_EB3__SendCommandWithArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_COUNT);
void FCD_029f1_gLCD_EB3__SendBinaryAction(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
void FCD_029f1_gLCD_EB3__PrintNumber(MX_SINT16 FCL_NUMBER, MX_UINT16 FCL_X, MX_UINT16 FCL_Y, MX_UINT8 FCL_FONT, MX_UINT8 FCL_TRANSPARENT);
void FCD_029f1_gLCD_EB3__DrawLine(MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT16 FCL_X2, MX_UINT16 FCL_Y2);
void FCD_029f1_gLCD_EB3__BacklightBrightness(MX_UINT8 FCL_BRIGHTNESS);
MX_UINT16 FCD_029f1_gLCD_EB3__TouchReadCoord(MX_UINT8 FCL_AXIS);
void FCD_029f1_gLCD_EB3__DrawEllipse(MX_UINT16 FCL_X, MX_UINT16 FCL_Y, MX_UINT16 FCL_XRADIUS, MX_UINT16 FCL_YRADIUS, MX_UINT8 FCL_TRANSPARENT, MX_UINT8 FCL_SOLID);
void FCD_029f1_gLCD_EB3__Plot(MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1);
void FCD_029f1_gLCD_EB3__FastPlot();
void FCD_029f1_gLCD_EB3__DrawQRCode(MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT8 FCL_SCALER, MX_CHAR *FCL_TEXT, MX_UINT16 FCLsz_TEXT);
void FCD_029f1_gLCD_EB3__DrawArc(MX_UINT16 FCL_X, MX_UINT16 FCL_Y, MX_UINT16 FCL_RADIUS, MX_UINT16 FCL_STARTANGLE, MX_UINT16 FCL_ENDANGLE, MX_UINT16 FCL_RESOLUTION, MX_UINT8 FCL_TRANSPARENT, MX_UINT8 FCL_SOLID);
void FCD_029f1_gLCD_EB3__SetDisplayOrientation(MX_UINT8 FCL_ORIENTATION);
void FCD_029f1_gLCD_EB3__BPlot(MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1);
void FCD_029f1_gLCD_EB3__SetBitmapTransparency(MX_UINT8 FCL_R, MX_UINT8 FCL_G, MX_UINT8 FCL_B);
MX_UINT8 FCD_029f1_gLCD_EB3__DrawBitmap(MX_CHAR *FCL_FILENAME, MX_UINT16 FCLsz_FILENAME, MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT8 FCL_ORIENTATION, MX_UINT8 FCL_TRANSPARENCY, MX_UINT8 FCL_FLIP);
void FCD_029f1_gLCD_EB3__PrintFloat(MX_FLOAT FCL_NUMBER, MX_UINT8 FCL_NUMDP, MX_UINT16 FCL_X, MX_UINT16 FCL_Y, MX_UINT8 FCL_FONT, MX_UINT8 FCL_TRANSPARENT);
MX_UINT8 FCD_029f1_gLCD_EB3__SendCommandWithString(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR);
void FCD_029f1_gLCD_EB3__Window(MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT16 FCL_X2, MX_UINT16 FCL_Y2);
void FCD_029f1_gLCD_EB3__Print(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT8 FCL_FONT, MX_UINT8 FCL_TRANSPARENT);
MX_BOOL FCD_029f1_gLCD_EB3__TouchCheck();
void FCD_029f1_gLCD_EB3__SetExternalFont(MX_UINT8 FCL_FONT, MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT8 FCL_CHARACTERSPACING, MX_UINT8 FCL_SPACEWIDTH);
MX_UINT8 FCD_029f1_gLCD_EB3__SendCommandWithDualString(MX_CHAR *FCL_STR1, MX_UINT16 FCLsz_STR1, MX_CHAR *FCL_STR2, MX_UINT16 FCLsz_STR2);
void FCD_029f1_gLCD_EB3__SendBinaryScene(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_LENGTH);
void FCD_029f1_gLCD_EB3__ClearDisplay();
void FCD_029f1_gLCD_EB3__SetBackgroundColour(MX_UINT8 FCL_RED, MX_UINT8 FCL_GREEN, MX_UINT8 FCL_BLUE);
void FCD_029f1_gLCD_EB3__DrawCircle(MX_UINT16 FCL_X, MX_UINT16 FCL_Y, MX_UINT16 FCL_RADIUS, MX_UINT8 FCL_TRANSPARENT, MX_UINT8 FCL_SOLID);
void FCD_029f1_gLCD_EB3__DrawRoundedRectangle(MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT16 FCL_X2, MX_UINT16 FCL_Y2, MX_UINT16 FCL_RADIUS, MX_UINT8 FCL_TRANSPARENT, MX_UINT8 FCL_SOLID);
void FCD_029f1_gLCD_EB3__SetForegroundColour(MX_UINT8 FCL_RED, MX_UINT8 FCL_GREEN, MX_UINT8 FCL_BLUE);
void FCD_029f1_gLCD_EB3__DrawRectangle(MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT16 FCL_X2, MX_UINT16 FCL_Y2, MX_UINT8 FCL_TRANSPARENT, MX_UINT8 FCL_SOLID);
void FCD_029f1_gLCD_EB3__Initialise();

/*========================================================================*\
   Use :cal_i2c1
       :Macro function declarations
\*========================================================================*/
#define MX_I2C_SDA_PORT_1 portc
#define MX_I2C_REF1 
#define MX_I2C_1 
#define MX_I2C_SDA_AF_1 (0)
#define MX_I2C_SCL_AF_1 (0)
#define MX_I2C_BMODE_1 (0)
#define MX_I2C_SDA_TRIS_1 trisc
#define MX_I2C_SCL_PIN_1 (5)
#define MX_I2C_SCL_PORT_1 portc
#define MX_I2C_STOPDEL_1 (0)
#define MX_I2C_SDA_PIN_1 (4)
#define MX_I2C_SCL_ODC_1 ODCONC
#define MX_I2C_SCL_TRIS_1 trisc
#define MX_I2C_BAUD_1 (100000)
#define MX_I2C_CLOCKSTRETCHING_1 (0)
#define MX_I2C_SDA_ODC_1 ODCONC
#define MX_I2C_CHANNEL_1 (0)


/*=----------------------------------------------------------------------=*\
   Use :cal_i2c1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_MI2C

void FC_CAL_I2C_Slave_Uninit_1();
void FCD_07da1_cal_i2c1__Prv_TextConsole(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT8 FCL_COLOUR, MX_UINT8 FCL_APPENDTIMESTAMP);
MX_UINT16 FC_CAL_I2C_Transaction_Write_1(MX_UINT8 *FCL_BUFFER, MX_UINT16 FCLsz_BUFFER, MX_UINT16 FCL_LENGTH);
void FC_CAL_I2C_Master_Stop_1();
void FC_CAL_I2C_Slave_Init_1(MX_UINT8 FCL_ADDRESS, MX_UINT8 FCL_MASK);
void FC_CAL_I2C_Master_Uninit_1();
MX_UINT8 FC_CAL_I2C_Slave_Status_1();
MX_UINT8 FC_CAL_I2C_Slave_TxByte_1(MX_UINT8 FCL_DATA);
void FC_CAL_I2C_Transaction_Uninit_1();
MX_UINT8 FC_CAL_I2C_Slave_RxByte_1(MX_UINT8 FCL_LAST);
void FC_CAL_I2C_Master_Init_1();
void FC_CAL_I2C_Master_Start_1();
MX_UINT16 FC_CAL_I2C_Transaction_Read_1(MX_UINT8 *FCL_BUFFER, MX_UINT16 FCLsz_BUFFER, MX_UINT16 FCL_LENGTH);
MX_UINT8 FC_CAL_I2C_Master_TxByte_1(MX_UINT8 FCL_DATA);
void FC_CAL_I2C_Master_Restart_1();
MX_UINT8 FC_CAL_I2C_Master_RxByte_1(MX_UINT8 FCL_LAST);
MX_UINT8 FC_CAL_I2C_Transaction_Init_1(MX_UINT8 FCL_ADDRESS);
MX_FLOAT FCD_01c01_temp_hum_sensor__GetTemperatureReal();
MX_SINT16 FCD_01c01_temp_hum_sensor__GetTemperatureInt();
MX_SINT16 FCD_01c01_temp_hum_sensor__GetHumidityInt();
MX_UINT8 FCD_01c01_temp_hum_sensor__Sample();
void FCD_01c01_temp_hum_sensor__ChangePrecision(MX_UINT8 FCL_PRECISION);
MX_FLOAT FCD_01c01_temp_hum_sensor__GetHumidityReal();
void FCD_01c01_temp_hum_sensor__SetTemperatureScale(MX_UINT8 FCL_SCALE);
MX_UINT8 FCD_01c01_temp_hum_sensor__Initialise();

/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\includes.c"

