// CRC: C09139DD0A75D64CECB6A655701556ECB3779E843346CE0F5130EA7DD15162532F19E22CED7E2D79FCA1D712F9F4A73B1790799BE3387D93492B2739DFD6F390EA86995873165087177459893585281C90686FF2551B5A206F82C454E0B2FCCD13F4AF9A399C50EF4BE936633A039C416EA48F3CD010D5075FF6B3AC24950F4D78642253E57F9DFA48624EF30B847B3F3027571EAD75915DA9B11F738DF98E15E806736B7C6ED617708FBA6C9D77DB83C0DA9898789DC59B853BBD0524064598CC7D8CBF0FF092B4768013E217CC90175CDDD8C148A2D851E4684809261CFFE2A7BCFDA775919FDA34B38626D8A426BD0E13B4728EEF95A1549D34A0D5AD11F3642BC356681868689149426535551EA97350F98B1596CCFDAE50ACE3D7DDA2D28E9421B336835453
// REVISION: 1.0
// GUID: EAE7C539-73D2-4F03-B7C2-AC43CFEEC5F7
// DATE: 07\01\2026
// DIR: Misc\Templates\Motors|and|microcontrollers\ESP32S3\Servo|-|ESP.h
//************************************************************************************
//**  
//**  Source name:   D:\Dev\Flowcode V11\Examples\Templates\Motors and microcontrollers\ESP32S3\Servo - ESP.fcfx
//**  Title:         Servo - ArdMega
//**  Description:   
//**  Device:        ESP.ESP32.E-Blocks3 ESP32S3 Programmer
//**  
//**  Generated by:  Flowcode v11.0.0.8
//**  Date:          Wednesday, January 07, 2026 12:54:56
//**  Users:         1
//**  Registered to: BenR (82702381)
//**  Licence key: 95CJQR
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#define MX_ESP

#define MX_CAL_ESP

#define MX_CLK_SPEED 240000000

#define FCP_NULL Unconnected_Port


#define MX_CAL_ESP32
#define MX_CAL_ESP32S3
#define MX_BL6390_PINMAP
#define MX_ESP32_TYPE ESP32S3
#include <stdio.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/task.h"
#include "driver/gpio.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include "esp_event_loop.h"
#include "nvs_flash.h"
#include "lwip/err.h"
#include "lwip/sys.h"
#include "sdkconfig.h"

/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\internals.c"



MX_UINT32 FCLV_LOOP1;
MX_UINT32 FCLV_LOOP2;
MX_UINT32 FCLV_LOOP3;


/*========================================================================*\
   Use :Servo_Controller1
       :Macro function declarations
\*========================================================================*/
#define MX_SERVO_CCPR1H 36
#define MX_SERVO_CCPR1L 248
#define MX_Servo_Channel_Count 1


/*=----------------------------------------------------------------------=*\
   Use :Servo_Controller1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#ifdef MX_CAL_PIC

	#define MX_SERVO_REG_CCPR1H		CCPR1H
	#define MX_SERVO_REG_CCPR1L		CCPR1L
	#define MX_SERVO_REG_CCPR2H		CCPR2H
	#define MX_SERVO_REG_CCPR2L		CCPR2L
	#define MX_SERVO_REG_T1CON		T1CON
	#define MX_SERVO_REG_CCP1CON	CCP1CON
	#define MX_SERVO_REG_CCP2CON 	CCP2CON
	#define MX_SERVO_T1CON			0x01

#ifdef _PIE6_CCP1IE_POSN
	#define MX_SERVO_REG_CCP1EN		PIE6
	#define MX_SERVO_REG_CCP1F		PIR6
	#define MX_SERVO_REG_CCP2EN		PIE6
	#define MX_SERVO_REG_CCP2F		PIR6
	#define MX_SERVO_CCP1CON	    0x8b
	#define MX_SERVO_CCP2CON	    0x8a
    #define MX_SERVO_T1_CLK         0x01
#else
  #ifdef _PIE3_CCP1IE_POSN
	#define MX_SERVO_REG_CCP1EN		PIE3
	#define MX_SERVO_REG_CCP1F		PIR3
	#define MX_SERVO_REG_CCP2EN		PIE3
	#define MX_SERVO_REG_CCP2F		PIR3
	#define MX_SERVO_CCP1CON	    0x0b
	#define MX_SERVO_CCP2CON	    0x0a
  #else
    #ifdef _PIE4_CCP1IE_POSN
	    #define MX_SERVO_REG_CCP1EN		PIE4
	    #define MX_SERVO_REG_CCP1F		PIR4
	    #define MX_SERVO_REG_CCP2EN		PIE4
	    #define MX_SERVO_REG_CCP2F		PIR4
	    #define MX_SERVO_CCP1CON	    0x8b
	    #define MX_SERVO_CCP2CON	    0x8a
    #else
      #ifdef _PIE7_CCP1IE_POSN
	      #define MX_SERVO_REG_CCP1EN	PIE7
	      #define MX_SERVO_REG_CCP1F	PIR7
	      #define MX_SERVO_REG_CCP2EN	PIE7
	      #define MX_SERVO_REG_CCP2F	PIR7
	      #define MX_SERVO_CCP1CON	    0x8b
	      #define MX_SERVO_CCP2CON	    0x8a
	      #define MX_SERVO_T1_CLK         0x01
      #else
	      #define MX_SERVO_REG_CCP1EN	PIE1
	      #define MX_SERVO_REG_CCP1F	PIR1
	      #define MX_SERVO_REG_CCP2EN	PIE2
	      #define MX_SERVO_REG_CCP2F	PIR2
	      #define MX_SERVO_CCP1CON	    0x0b
	      #define MX_SERVO_CCP2CON	    0x0a
      #endif
    #endif
  #endif
#endif

#ifndef INTCON
	#define INTCON	INTCON0
#endif
	#define MX_SERVO_FLAG_CCP1EN		CCP1IE
	#define MX_SERVO_FLAG_CCP2EN		CCP2IE
	#define MX_SERVO_FLAG_CCP1F			CCP1IF
	#define MX_SERVO_FLAG_CCP2F			CCP2IF
	#define MX_SERVO_REG_INT			INTCON
	#define MX_SERVO_FLAG_GLOB			GIE
	#define MX_SERVO_FLAG_PERIPH		PEIE

	#define MX_CCP1_INT_START		if (ts_bit(MX_SERVO_REG_CCP1F, MX_SERVO_FLAG_CCP1F) && ts_bit(MX_SERVO_REG_CCP1EN, MX_SERVO_FLAG_CCP1EN))
	#define MX_CCP2_INT_START		if (ts_bit(MX_SERVO_REG_CCP2F, MX_SERVO_FLAG_CCP2F) && ts_bit(MX_SERVO_REG_CCP2EN, MX_SERVO_FLAG_CCP2EN))

#endif

#ifdef MX_CAL_PIC16

	#define MX_SERVO_REG_CCP1F		IFS0bits
	#define MX_SERVO_FLAG_CCP1F		T3IF

	#define MX_SERVO_REG_CCP2F		IFS0bits
	#define MX_SERVO_FLAG_CCP2F		T2IF

	#define MX_CCP1_INT_START		void _ISR _T3Interrupt(void)
	#define MX_CCP2_INT_START		void _ISR _T2Interrupt(void)

#endif

#ifdef MX_CAL_AVR

	MX_UINT8	mx_servo_dummy;

	#ifdef MX_XMEGA

		#define OCR1AL	TCC1.CCA
		#define OCR1BL	TCC1.CCB
		#define TCCR1A	TCC1.CTRLA
		#define TCCR1B	TCC1.CTRLB
		#define TIMSK1	TCC1.INTCTRLB
		#define TIFR1	TCC1.INTFLAGS
		#define OCF1A	4
		#define OCF1B	5
		#define OCIE1A	0
		#define OCIE1B	2

	#else

		#ifndef TIMSK1
			#ifdef TIMSK
				#define TIMSK1	TIMSK
			#endif
		#endif

		#ifndef TIFR1
			#ifdef TIFR
				#define TIFR1	TIFR
			#endif
		#endif

		#ifndef OCR1AH
			#ifdef OCR1A
				#define OCR1AH	mx_servo_dummy
			#endif
		#endif

		#ifndef OCR1AL
			#ifdef OCR1A
				#define OCR1AL	OCR1A
			#endif
		#endif

		#ifndef OCR1BH
			#ifdef OCR1B
				#define OCR1BH	mx_servo_dummy
			#endif
		#endif

		#ifndef OCR1BL
			#ifdef OCR1B
				#define OCR1BL	TCC1.CCB
			#endif
		#endif

	#endif

	#define MX_SERVO_T1CON		0x01

	#define MX_SERVO_REG_CCPR1H		OCR1AH
	#define MX_SERVO_REG_CCPR1L		OCR1AL
	#define MX_SERVO_REG_CCPR2H		OCR1BH
	#define MX_SERVO_REG_CCPR2L		OCR1BL
	#define MX_SERVO_REG_T1CON		mx_servo_dummy
	#define MX_SERVO_REG_CCP1CON	TCCR1A
	#define MX_SERVO_REG_CCP2CON 	TCCR1B
	#define MX_SERVO_REG_CCP1EN		TIMSK1
	#define MX_SERVO_REG_CCP2EN		TIMSK1
	#define MX_SERVO_FLAG_CCP1EN	OCIE1A
	#define MX_SERVO_FLAG_CCP2EN	OCIE1B
	#define MX_SERVO_REG_CCP1F		TIFR1
	#define MX_SERVO_REG_CCP2F		TIFR1
	#define MX_SERVO_FLAG_CCP1F		OCF1A
	#define MX_SERVO_FLAG_CCP2F		OCF1B
	#define MX_SERVO_REG_INT		mx_servo_dummy
	#define MX_SERVO_FLAG_GLOB		0
	#define MX_SERVO_FLAG_PERIPH	0

	#define MX_SERVO_CCP1CON	0x00
	#define MX_SERVO_CCP2CON	0x09	//CTC mode with PWM prescale / 8

	#define MX_CCP1_INT_START		ISR(TIMER1_COMPA_vect)
	#define MX_CCP2_INT_START		ISR(TIMER1_COMPB_vect)

#endif

#ifdef MX_CAL_ARD

	MX_UINT8	mx_servo_dummy;

	#ifdef MX_XMEGA

		#define OCR1AL	TCC1.CCA
		#define OCR1BL	TCC1.CCB
		#define TCCR1A	TCC1.CTRLA
		#define TCCR1B	TCC1.CTRLB
		#define TIMSK1	TCC1.INTCTRLB
		#define TIFR1	TCC1.INTFLAGS
		#define OCF1A	4
		#define OCF1B	5
		#define OCIE1A	0
		#define OCIE1B	2

	#else

		#ifndef TIMSK1
			#ifdef TIMSK
				#define TIMSK1	TIMSK
			#endif
		#endif

		#ifndef TIFR1
			#ifdef TIFR
				#define TIFR1	TIFR
			#endif
		#endif

		#ifndef OCR1AH
			#ifdef OCR1A
				#define OCR1AH	mx_servo_dummy
			#endif
		#endif

		#ifndef OCR1AL
			#ifdef OCR1A
				#define OCR1AL	OCR1A
			#endif
		#endif

		#ifndef OCR1BH
			#ifdef OCR1B
				#define OCR1BH	mx_servo_dummy
			#endif
		#endif

		#ifndef OCR1BL
			#ifdef OCR1B
				#define OCR1BL	TCC1.CCB
			#endif
		#endif

	#endif

	#define MX_SERVO_T1CON		0x01

	#define MX_SERVO_REG_CCPR1H		OCR1AH
	#define MX_SERVO_REG_CCPR1L		OCR1AL
	#define MX_SERVO_REG_CCPR2H		OCR1BH
	#define MX_SERVO_REG_CCPR2L		OCR1BL
	#define MX_SERVO_REG_T1CON		mx_servo_dummy
	#define MX_SERVO_REG_CCP1CON	TCCR1A
	#define MX_SERVO_REG_CCP2CON 	TCCR1B
	#define MX_SERVO_REG_CCP1EN		TIMSK1
	#define MX_SERVO_REG_CCP2EN		TIMSK1
	#define MX_SERVO_FLAG_CCP1EN	OCIE1A
	#define MX_SERVO_FLAG_CCP2EN	OCIE1B
	#define MX_SERVO_REG_CCP1F		TIFR1
	#define MX_SERVO_REG_CCP2F		TIFR1
	#define MX_SERVO_FLAG_CCP1F		OCF1A
	#define MX_SERVO_FLAG_CCP2F		OCF1B
	#define MX_SERVO_REG_INT		mx_servo_dummy
	#define MX_SERVO_FLAG_GLOB		0
	#define MX_SERVO_FLAG_PERIPH	0

	#define MX_SERVO_CCP1CON	0x00
	#define MX_SERVO_CCP2CON	0x09	//CTC mode with PWM prescale / 8

	#define MX_CCP1_INT_START		ISR(TIMER1_COMPA_vect)
	#define MX_CCP2_INT_START		ISR(TIMER1_COMPB_vect)

#endif

#if defined MX_CAL_STARM

	#define TIM_SERVO_INSTANCE				TIM3
	#define TIM_SERVO_IRQHandler			TIM3_IRQHandler
	#define MX_ISR_TIM_SERVO				MX_ISR_TIM3
	#define __HAL_RCC_TIM_SERVO_CLK_ENABLE	__HAL_RCC_TIM3_CLK_ENABLE
	#define TIM_SERVO_IRQn					TIM3_IRQn

	TIM_HandleTypeDef		MX_HANDLE_TIM_SERVO;
	TIM_OC_InitTypeDef		MX_CONFIG_OC_SERVO;

	#define MX_CCP1_INT_START \
		void TIM_SERVO_IRQHandler(void) \
		{ \
			HAL_TIM_IRQHandler(&(MX_HANDLE_TIM_SERVO)); \
		} \
		void MX_ISR_TIM_SERVO()

	#define MX_CCP2_INT_START		void HAL_TIM_OC_DelayElapsedCallback(TIM_HandleTypeDef *htim)

#elif defined MX_CAL_ARM

	MX_UINT8	mx_servo_dummy;

	#define MX_SERVO_REG_CCP1F		mx_servo_dummy
	#define MX_SERVO_REG_CCP2F		mx_servo_dummy
	#define MX_SERVO_FLAG_CCP1F		0
	#define MX_SERVO_FLAG_CCP2F		1

	#define MX_CCP1_INT_START		if ((periphID == AT91C_ID_TC2) && (IFlags & AT91C_TC_CPCS))
	#define MX_CCP2_INT_START		if ((periphID == AT91C_ID_TC2) && (IFlags & AT91C_TC_CPAS))

#elif defined MX_CAL_ESP

	MX_UINT8	mx_servo_dummy;

	#define MX_SERVO_REG_CCP1F		mx_servo_dummy
	#define MX_SERVO_REG_CCP2F		mx_servo_dummy
	#define MX_SERVO_FLAG_CCP1F		0
	#define MX_SERVO_FLAG_CCP2F		1

	#define MX_CCP1_INT_START		void Servo_Macro_Dummy1 ()
	#define MX_CCP2_INT_START		void Servo_Macro_Dummy2 ()

#endif

//ESP32 CAL PWM Definitions
#define MX_PWM
#define MX_PWM_REF1
#define MX_PWM_CHANNEL_1 1
#define MX_PWM_PORT_1 PORTC
#define MX_PWM_PIN_1 0
#define MX_PWM_FREQ_1 50

void FCD_0dd21_Servo_Controller1__DisableServo(MX_UINT8 FCL_CHANNEL);
void FCD_0dd21_Servo_Controller1__SetPosition(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_POSITION);
MX_UINT8 FCD_0dd21_Servo_Controller1__MoveToPositionInt(MX_UINT8 FCL_CHANNEL, MX_UINT16 FCL_POSITION);
void FCD_0dd21_Servo_Controller1__SetPositionInt(MX_UINT8 FCL_CHANNEL, MX_UINT16 FCL_POSITION);
MX_BOOL FCD_0dd21_Servo_Controller1__MoveToAngle(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_ANGLE);
MX_UINT8 FCD_0dd21_Servo_Controller1__MoveToPosition(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_POSITION);
void FCD_0dd21_Servo_Controller1__SetTrim(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_TRIM);
MX_UINT8 FCD_0dd21_Servo_Controller1__IsAutoMoving();
void FCD_0dd21_Servo_Controller1__SetAutoMoveSpeedInt(MX_UINT16 FCL_SPEED);
MX_UINT8 FCD_0dd21_Servo_Controller1__IsServoAutoMoving(MX_UINT8 FCL_CHANNEL);
void FCD_0dd21_Servo_Controller1__AutoMoveToPosition(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_POSITION);
void FCD_0dd21_Servo_Controller1__EnableServo(MX_UINT8 FCL_CHANNEL);
void FCD_0dd21_Servo_Controller1__AutoMoveToAngle(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_ANGLE);
void FCD_0dd21_Servo_Controller1__SetAutoMoveSpeed(MX_UINT8 FCL_SPEED);
void FCD_0dd21_Servo_Controller1__AutoMoveToPositionInt(MX_UINT8 FCL_CHANNEL, MX_UINT16 FCL_POSITION);
void FCD_0dd21_Servo_Controller1__Initialise();

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_1 
#define MX_ADC_BITS_13 
#define MX_ADC_CHANNEL_4 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_1 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_1 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_1 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_1();
void FC_ADC_Enable_1(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_1(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT16 FCD_0cc51_adc_base1__RawSampleInt();
MX_UINT8 FCD_0cc51_adc_base1__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_0cc51_adc_base1__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_0cc51_adc_base1__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_0cc51_adc_base1__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_0cc51_adc_base1__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_0cc51_adc_base1__GetVoltage();
void FCD_0cc51_adc_base1__RawEnable();
MX_UINT8 FCD_0cc51_adc_base1__RawSampleByte();
MX_UINT16 FCD_0cc51_adc_base1__GetInt();
void FCD_0cc51_adc_base1__RawDisable();
MX_UINT8 FCD_0cc51_adc_base1__GetByte();
MX_UINT32 FCD_0c431_MapFunction1__MapUlong(MX_UINT32 FCL_VALUE, MX_UINT32 FCL_INMIN, MX_UINT32 FCL_INMAX, MX_UINT32 FCL_OUTMIN, MX_UINT32 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_SINT16 FCD_0c431_MapFunction1__MapInt(MX_SINT16 FCL_VALUE, MX_SINT16 FCL_INMIN, MX_SINT16 FCL_INMAX, MX_SINT16 FCL_OUTMIN, MX_SINT16 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_FLOAT FCD_0c431_MapFunction1__MapFloat(MX_FLOAT FCL_VALUE, MX_FLOAT FCL_INMIN, MX_FLOAT FCL_INMAX, MX_FLOAT FCL_OUTMIN, MX_FLOAT FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_SINT32 FCD_0c431_MapFunction1__MapLong(MX_SINT32 FCL_VALUE, MX_SINT32 FCL_INMIN, MX_SINT32 FCL_INMAX, MX_SINT32 FCL_OUTMIN, MX_SINT32 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_UINT16 FCD_0c431_MapFunction1__MapUInt(MX_UINT16 FCL_VALUE, MX_UINT16 FCL_INMIN, MX_UINT16 FCL_INMAX, MX_UINT16 FCL_OUTMIN, MX_UINT16 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_UINT8 FCD_0c431_MapFunction1__MapByte(MX_UINT8 FCL_VALUE, MX_UINT8 FCL_INMIN, MX_UINT8 FCL_INMAX, MX_UINT8 FCL_OUTMIN, MX_UINT8 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_BOOL FCD_0b4c1_IsSim1__Check();

/*========================================================================*\
   Use :Potentiometer1
       :Macro function declarations
\*========================================================================*/
#define FCV_00a21_Potentiometer1__COMPONENTLABEL (0)

void FCD_00a21_Potentiometer1__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_00a21_Potentiometer1__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_00a21_Potentiometer1__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_00a21_Potentiometer1__GetVoltage();
MX_UINT16 FCD_00a21_Potentiometer1__GetInt();
MX_UINT8 FCD_00a21_Potentiometer1__GetByte();
MX_UINT16 FCD_00fb2_WidthData__GetLUTCount();
MX_UINT16 FCD_00fb1_ASCIIData__GetLUTCount();
MX_UINT32 FCD_09e51_gLCD_Font1__SumWidths(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_09e51_gLCD_Font1__ReadWidth(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_09e51_gLCD_Font1__ReadFontStat(MX_UINT8 FCL_INDEX);
MX_UINT8 FCD_09e51_gLCD_Font1__ReadASCIILUT(MX_UINT8 FCL_CHARACTER, MX_UINT16 FCL_BYTEINDEX);

/*========================================================================*\
   Use :Base_GLCD1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Base_GLCD1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define ReadFontWidth(FONT, CHAR) FCD_0ba71_Base_GLCD1__ReadFontWidth(FONT, CHAR)
#define ReadFontStat(FONT, IDX) FCD_0ba71_Base_GLCD1__ReadFontStat(FONT, IDX)


MX_UINT32 FCD_0ba71_Base_GLCD1__Prv_SumWidths(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_0ba71_Base_GLCD1__ReadFontWidth(MX_UINT8 FCL_FONT, MX_UINT8 FCL_CHARACTER);
void FCD_0ba71_Base_GLCD1__Prv_ReadFontFileHeader(MX_UINT8 FCL_FONT);
MX_UINT8 FCD_0ba71_Base_GLCD1__ReadFontStat(MX_UINT8 FCL_FONT, MX_UINT8 FCL_INDEX);
void FCD_0ba71_Base_GLCD1__SetExternalFont(MX_UINT8 FCL_FONT, MX_CHAR *PFCL_FILENAME, MX_UINT8 FCL_CHARACTERSPACING, MX_UINT8 FCL_SPACEWIDTH);
MX_UINT8 FCD_0ba71_Base_GLCD1__ReadFontByte(MX_UINT8 FCL_FONT, MX_UINT8 FCL_CHARACTER, MX_UINT16 FCL_BYTEINDEX);
void FCD_04071_LCD1__Clear();
void FCD_04071_LCD1__PrintString(MX_CHAR *FCL_TEXT, MX_UINT16 FCLsz_TEXT);
void FCD_04071_LCD1__PrintAscii(MX_UINT8 FCL_CHARACTER);
void FCD_04071_LCD1__PrintNumber(MX_SINT16 FCL_NUMBER);
void FCD_04071_LCD1__RAMWrite(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_D0, MX_UINT8 FCL_D1, MX_UINT8 FCL_D2, MX_UINT8 FCL_D3, MX_UINT8 FCL_D4, MX_UINT8 FCL_D5, MX_UINT8 FCL_D6, MX_UINT8 FCL_D7);
void FCD_04071_LCD1__ClearLine(MX_UINT8 FCL_LINE);
void FCD_04071_LCD1__Cursor(MX_UINT8 FCL_X, MX_UINT8 FCL_Y);
void FCD_04071_LCD1__Command(MX_UINT8 FCL_INSTRUCTION);
void FCD_04071_LCD1__PrintFormattedNumber(MX_UINT32 FCL_NUMBER, MX_BOOL FCL_FORMAT);
void FCD_04071_LCD1__ScrollDisplay(MX_UINT8 FCL_POSITION, MX_UINT8 FCL_DIRECTION);
void FCD_04071_LCD1__RawSend(MX_UINT8 FCL_DATA, MX_BOOL FCL_TYPE);
void FCD_04071_LCD1__PrintFloat(MX_FLOAT FCL_NUMBER, MX_UINT8 FCL_DECIMALPLACES);
void FCD_04071_LCD1__RemapCharacter(MX_UINT8 FCL_REMAPIDX, MX_UINT8 FCL_SEARCHCHARACTER, MX_UINT8 FCL_REPLACEMENTCHARACTER);
void FCD_04071_LCD1__Start();
void FCD_049e1_LCD_BL0169__Clear();
void FCD_049e1_LCD_BL0169__PrintString(MX_CHAR *FCL_TEXT, MX_UINT16 FCLsz_TEXT);
void FCD_049e1_LCD_BL0169__PrintAscii(MX_UINT8 FCL_CHARACTER);
void FCD_049e1_LCD_BL0169__PrintNumber(MX_SINT16 FCL_NUMBER);
void FCD_049e1_LCD_BL0169__RAMWrite(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_D0, MX_UINT8 FCL_D1, MX_UINT8 FCL_D2, MX_UINT8 FCL_D3, MX_UINT8 FCL_D4, MX_UINT8 FCL_D5, MX_UINT8 FCL_D6, MX_UINT8 FCL_D7);
void FCD_049e1_LCD_BL0169__ClearLine(MX_UINT8 FCL_LINE);
void FCD_049e1_LCD_BL0169__Cursor(MX_UINT8 FCL_X, MX_UINT8 FCL_Y);
void FCD_049e1_LCD_BL0169__PrintFormattedNumber(MX_UINT32 FCL_NUMBER, MX_BOOL FCL_FORMAT);
void FCD_049e1_LCD_BL0169__RawSend(MX_UINT8 FCL_DATA, MX_BOOL FCL_TYPE);
void FCD_049e1_LCD_BL0169__PrintFloat(MX_FLOAT FCL_NUMBER, MX_UINT8 FCL_DECIMALPLACES);
void FCD_049e1_LCD_BL0169__RemapCharacter(MX_UINT8 FCL_REMAPIDX, MX_UINT8 FCL_SEARCHCHARACTER, MX_UINT8 FCL_REPLACEMENTCHARACTER);
void FCD_049e1_LCD_BL0169__Start();

/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\includes.c"

