// CRC: 0000000000000000000000000000000000000000000000000000000000000000
// REVISION: 1.0
// GUID: B4C5D6E7-F8A9-0123-7890-234567890123
// DATE: 22\06\2026
// DIR: CAL\RE\RE_CAL_HBRIDGE.c
/* Flowcode CAL HBridge - Renesas RA (uses GPT PWM + GPIO direction pins) */

#include "ra4m1.h"

#define MX_HBRIDGE_IN1_PORT_X  CAL_APPEND(MX_HBRIDGE_IN1_PORT_, MX_HBRIDGE_NUM)
#define MX_HBRIDGE_IN1_PIN_X   CAL_APPEND(MX_HBRIDGE_IN1_PIN_, MX_HBRIDGE_NUM)
#define MX_HBRIDGE_IN2_PORT_X  CAL_APPEND(MX_HBRIDGE_IN2_PORT_, MX_HBRIDGE_NUM)
#define MX_HBRIDGE_IN2_PIN_X   CAL_APPEND(MX_HBRIDGE_IN2_PIN_, MX_HBRIDGE_NUM)

CALFUNCTION(void, FC_CAL_HBridge_Init_, (void))
{
    /* Set IN1 and IN2 as outputs, drive low */
    RA_PFS_UNLOCK();
    R_PFS(MX_HBRIDGE_IN1_PORT_X, MX_HBRIDGE_IN1_PIN_X) = PFS_PDR;
    R_PFS(MX_HBRIDGE_IN2_PORT_X, MX_HBRIDGE_IN2_PIN_X) = PFS_PDR;
    RA_PFS_LOCK();
    R_PORT(MX_HBRIDGE_IN1_PORT_X)->PORR = (unsigned short)(1U << MX_HBRIDGE_IN1_PIN_X);
    R_PORT(MX_HBRIDGE_IN2_PORT_X)->PORR = (unsigned short)(1U << MX_HBRIDGE_IN2_PIN_X);
}

CALFUNCTION(void, FC_CAL_HBridge_Forward_, (MX_UINT8 Speed))
{
    (void)Speed;
    R_PORT(MX_HBRIDGE_IN1_PORT_X)->POSR = (unsigned short)(1U << MX_HBRIDGE_IN1_PIN_X);
    R_PORT(MX_HBRIDGE_IN2_PORT_X)->PORR = (unsigned short)(1U << MX_HBRIDGE_IN2_PIN_X);
}

CALFUNCTION(void, FC_CAL_HBridge_Reverse_, (MX_UINT8 Speed))
{
    (void)Speed;
    R_PORT(MX_HBRIDGE_IN1_PORT_X)->PORR = (unsigned short)(1U << MX_HBRIDGE_IN1_PIN_X);
    R_PORT(MX_HBRIDGE_IN2_PORT_X)->POSR = (unsigned short)(1U << MX_HBRIDGE_IN2_PIN_X);
}

CALFUNCTION(void, FC_CAL_HBridge_Stop_, (void))
{
    R_PORT(MX_HBRIDGE_IN1_PORT_X)->PORR = (unsigned short)(1U << MX_HBRIDGE_IN1_PIN_X);
    R_PORT(MX_HBRIDGE_IN2_PORT_X)->PORR = (unsigned short)(1U << MX_HBRIDGE_IN2_PIN_X);
}
