// CRC: A6459004C43C0517DC6DFC5681C2AD698104299A14C9E1875427A2F7EF4303D9CFD76A29863CD488DE50EA9D9C0AC8D1ACE0EE4E1BA3BB8CCC6790EFEF7EFF81AF5024EAE86DD3983426F260378697979A0D46BD3B6AACB92DE4D84759EBB5079CA9DA2D2BBCDAE2A4D1C56CD1580BF5A2B47EC9EA6B3838F34B24F509737DFEBA4362A078D4965773803CB39D8D40CEA574AC8C1D234331231F8CC8DE722B65E3B39A8C5C83C5EE7B3853863D4EFD22B144DD04FA6EA74CC0C2C57EA496B912EFA62DE588905CEC549D34A0D5AD11F335A26E67454AA2885C626D93CB5B93F3DB1AF2231D6857BD0C9FBA1F01A7E45B08B65E7F68830DD9
// REVISION: 1.0
// GUID: 10C887F6-3009-41BF-9E98-EAE20AF4DD55
// DATE: 08\08\2022
// DIR: CAL\PIC32BIT\PIC32BIT_CAL_TypeDefs.c
/*********************************************************************
 *                  Flowcode CAL TypeDefs File
 *
 * File: PIC16BIT_CAL_TypeDefs.c
 *
 * (c) 2011 Matrix Multimedia Ltd.
 * http://www.matrixmultimedia.com
 *
 * Software License Agreement
 *
 * The software supplied herewith by Matrix Multimedia Ltd (the
 * “Company”) for its Flowcode graphical programming language is
 * intended and supplied to you, the Company’s customer, for use
 * solely and exclusively on the Company's products. The software
 * is owned by the Company, and is protected under applicable
 * copyright laws. All rights are reserved. Any use in violation
 * of the foregoing restrictions may subject the user to criminal
 * sanctions under applicable laws, as well as to civil liability
 * for the breach of the terms and conditions of this licence.
 *
 * THIS SOFTWARE IS PROVIDED IN AN “AS IS” CONDITION. NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED
 * TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. THE COMPANY SHALL NOT,
 * IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL OR
 * CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * Changelog:
 *
 *  date  | by | description
 * -------+----+-----------------------------------------------------
 * 060911 | BR | Created
 *
 *
 *
 */

#include <stdbool.h>

// Preceeds all global variable definitions generated by Flowcode
#define MX_GLOBAL volatile

typedef bool           MX_BOOL;   // Or unsigned char, depending on platform
typedef signed char    MX_SINT8;
typedef signed short   MX_SINT16;
typedef signed long    MX_SINT32;
typedef unsigned char  MX_UINT8;
typedef unsigned short MX_UINT16;
typedef unsigned long  MX_UINT32;
typedef char           MX_CHAR;
typedef unsigned char* MX_STRING; // String pointer
typedef double         MX_FLOAT;  // In BoostC, needs '#define MX_FLOAT float'
typedef MX_UINT16      MX_UINT;   // Best integer value for the platform, at least 8 bit
typedef MX_SINT16      MX_SINT;

#define MX_FSINGLE float

typedef union
{
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union32;

typedef union
{
  MX_UINT16 AsInt;
  MX_UINT8  AsByte[2];
} MX_Union16;




//Example Union Code
//MX_Union32 Test;
//Test.AsLong = 0xFFFFFFFF;
//Test.AsInt[0] = 0xFFFF;
//Test.AsByte[0] = 0xFF;

