// CRC: C09139DD0A75D64CECB6A655701556ECC9D6F74ED0D3E47ACDB0BF7143A6B82B25FF37B297F9A200CC671842E99E31865D362FEAF5AAADADC10D5A554C6808E48D6FBA8944EFB526A10634EB7F31C4B96ED5D536AA0B2C84E7EEDE774A5BCDA6604B7AE7C58708940DA120B8FDF2F8E929170F6353B26093413E99DBFC314FB9340064A804FD4B3E1CF02FCABDF3054DABC2C2431F6C4065B2B59391F7DFE3FBA4BAF1B34E38B68E0C3CAEE8E7DA6987177B2E4FEC331D9D5B4FFC1746448087E7E757D082473223E1E24209CBBCF4CB30C52882C545716F4035D7FCFF87F812AEEBD41CA857470A5E27301F40792FA2706FE5EB6120ED0F9A5CB15D249A71D6FBB1809D884B4354549D34A0D5AD11F37522CC8DE3F1BBC073F7A8F418267434F107163D5F97C1F3F97B3AD2E0D541FFE19252820FE3EB9C
// REVISION: 1.0
// GUID: F4FB1A20-95C7-4324-88E6-FFBE1DAD05AA
// DATE: 15\12\2025
// DIR: Misc\Templates\Introduction|to|microcontrollers\PIC\Counter|-|PIC.h
//************************************************************************************
//**  
//**  Source name:   \\IRONMAN-PC2\Dev\Flowcode V11\Examples\Templates\Introduction to microcontrollers\PIC\Counter - PIC.fcfx
//**  Title:         Counter - PIC
//**  Description:   
//**  Device:        PIC.18F.E-blocks3 8-bit PIC
//**  
//**  Generated by:  Flowcode v11.0.0.8
//**  Date:          Monday, December 15, 2025 14:41:02
//**  Users:         1
//**  Registered to: JohnD (65060919)
//**  Licence key: MNBNUH
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#define MX_PIC

#define MX_CAL_PIC

#define MX_CLK_SPEED 64000000

#define FCP_NULL Unconnected_Port

#define MX_PWM_NEW_TMR_CONF2
#include <xc.h>
#include <math.h>

/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\internals.c"





/*========================================================================*\
   Use :LEDMono8
       :Macro function declarations
\*========================================================================*/
#define FCV_0e9e8_LEDMono8__POLARITY (1)

void FCD_0e9e8_LEDMono8__TurnOn();
void FCD_0e9e8_LEDMono8__SetState(MX_BOOL FCL_STATE);
void FCD_0e9e8_LEDMono8__TurnOff();

/*========================================================================*\
   Use :LEDMono7
       :Macro function declarations
\*========================================================================*/
#define FCV_0e9e7_LEDMono7__POLARITY (1)

void FCD_0e9e7_LEDMono7__TurnOn();
void FCD_0e9e7_LEDMono7__SetState(MX_BOOL FCL_STATE);
void FCD_0e9e7_LEDMono7__TurnOff();

/*========================================================================*\
   Use :LEDMono6
       :Macro function declarations
\*========================================================================*/
#define FCV_0e9e6_LEDMono6__POLARITY (1)

void FCD_0e9e6_LEDMono6__TurnOn();
void FCD_0e9e6_LEDMono6__SetState(MX_BOOL FCL_STATE);
void FCD_0e9e6_LEDMono6__TurnOff();

/*========================================================================*\
   Use :LEDMono5
       :Macro function declarations
\*========================================================================*/
#define FCV_0e9e5_LEDMono5__POLARITY (1)

void FCD_0e9e5_LEDMono5__TurnOn();
void FCD_0e9e5_LEDMono5__SetState(MX_BOOL FCL_STATE);
void FCD_0e9e5_LEDMono5__TurnOff();

/*========================================================================*\
   Use :LEDMono4
       :Macro function declarations
\*========================================================================*/
#define FCV_0e9e4_LEDMono4__POLARITY (1)

void FCD_0e9e4_LEDMono4__TurnOn();
void FCD_0e9e4_LEDMono4__SetState(MX_BOOL FCL_STATE);
void FCD_0e9e4_LEDMono4__TurnOff();

/*========================================================================*\
   Use :LEDMono3
       :Macro function declarations
\*========================================================================*/
#define FCV_0e9e3_LEDMono3__POLARITY (1)

void FCD_0e9e3_LEDMono3__TurnOn();
void FCD_0e9e3_LEDMono3__SetState(MX_BOOL FCL_STATE);
void FCD_0e9e3_LEDMono3__TurnOff();

/*========================================================================*\
   Use :LEDMono2
       :Macro function declarations
\*========================================================================*/
#define FCV_0e9e2_LEDMono2__POLARITY (1)

void FCD_0e9e2_LEDMono2__TurnOn();
void FCD_0e9e2_LEDMono2__SetState(MX_BOOL FCL_STATE);
void FCD_0e9e2_LEDMono2__TurnOff();

/*========================================================================*\
   Use :LEDMono1
       :Macro function declarations
\*========================================================================*/
#define FCV_0e9e1_LEDMono1__POLARITY (1)

void FCD_0e9e1_LEDMono1__TurnOn();
void FCD_0e9e1_LEDMono1__SetState(MX_BOOL FCL_STATE);
void FCD_0e9e1_LEDMono1__TurnOff();

/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\includes.c"

