// CRC: C09139DD0A75D64CECB6A655701556ECC9D6F74ED0D3E47ACDB0BF7143A6B82B25FF37B297F9A200CC671842E99E31865D362FEAF5AAADADC10D5A554C6808E48D6FBA8944EFB526A10634EB7F31C4B96ED5D536AA0B2C84E7EEDE774A5BCDA6604B7AE7C58708940DA120B8FDF2F8E929170F6353B26093413E99DBFC314FB99A66A2BA1661F17A474E873DCF461361ABC2C2431F6C4065B2B59391F7DFE3FBA4BAF1B34E38B68E0C3CAEE8E7DA69875629B5ACFCB1C5547255C8BEB8CD868C588CAC5BBAE7BC595C013861CB92D1D240544ABD668D2D9FEDEC8BCB0981749BBE4368EB8D4BE45F159476A9C0C4DE7E154BA414AFFE1F3EDAED7467496ECAC906E289E88807B31E549D34A0D5AD11F3FF6C8AE05154A816FF6C1322ACFEDC373DF9391938EF162EE00AF8598B7CA62D1079227E43D7E189
// REVISION: 1.0
// GUID: 5E5959CD-1EAF-45FE-88DF-DC543BC1EED8
// DATE: 15\12\2025
// DIR: Misc\Templates\Introduction|to|microcontrollers\PIC\Counter|-|PIC.c
//************************************************************************************
//**  
//**  Source name:   \\IRONMAN-PC2\Dev\Flowcode V11\Examples\Templates\Introduction to microcontrollers\PIC\Counter - PIC.fcfx
//**  Title:         Counter - PIC
//**  Description:   
//**  Device:        PIC.18F.E-blocks3 8-bit PIC
//**  
//**  Generated by:  Flowcode v11.0.0.8
//**  Date:          Monday, December 15, 2025 14:41:02
//**  Users:         1
//**  Registered to: JohnD (65060919)
//**  Licence key: MNBNUH
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#include "\\IRONMAN-PC2\Dev\Flowcode V11\Examples\Templates\Introduction to microcontrollers\PIC\Counter - PIC.h"


/*========================================================================*\
   Use :LEDMono8
       :GUID: 44f82374-a417-40d5-bd42-23a177a390d2
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\LED_Mono_2dgi.fcpx
       :Version: 20.0 (0x1300028)
       :Timestamp: 05\11\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e8_LEDMono8__TurnOn()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 7, 1);

  #endif

}

/*=----------------------------------------------------------------------=*\
   Use :Sets the state of the LED, accounting for the polarity.
       :
       :Parameters for macro SetState:
       :  State : 1=On, 0=Off
\*=----------------------------------------------------------------------=*/
void FCD_0e9e8_LEDMono8__SetState(MX_BOOL FCL_STATE)
{

  if (FCL_STATE)
  {  

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 7, 1);

    #endif

  } else {

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 7, 1 - 1);

    #endif

  }

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e8_LEDMono8__TurnOff()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 7, 1 - 1);

  #endif

}


/*========================================================================*\
   Use :LEDMono7
       :GUID: 44f82374-a417-40d5-bd42-23a177a390d2
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\LED_Mono_2dgi.fcpx
       :Version: 20.0 (0x1300028)
       :Timestamp: 05\11\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e7_LEDMono7__TurnOn()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 6, 1);

  #endif

}

/*=----------------------------------------------------------------------=*\
   Use :Sets the state of the LED, accounting for the polarity.
       :
       :Parameters for macro SetState:
       :  State : 1=On, 0=Off
\*=----------------------------------------------------------------------=*/
void FCD_0e9e7_LEDMono7__SetState(MX_BOOL FCL_STATE)
{

  if (FCL_STATE)
  {  

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 6, 1);

    #endif

  } else {

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 6, 1 - 1);

    #endif

  }

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e7_LEDMono7__TurnOff()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 6, 1 - 1);

  #endif

}


/*========================================================================*\
   Use :LEDMono6
       :GUID: 44f82374-a417-40d5-bd42-23a177a390d2
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\LED_Mono_2dgi.fcpx
       :Version: 20.0 (0x1300028)
       :Timestamp: 05\11\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e6_LEDMono6__TurnOn()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 5, 1);

  #endif

}

/*=----------------------------------------------------------------------=*\
   Use :Sets the state of the LED, accounting for the polarity.
       :
       :Parameters for macro SetState:
       :  State : 1=On, 0=Off
\*=----------------------------------------------------------------------=*/
void FCD_0e9e6_LEDMono6__SetState(MX_BOOL FCL_STATE)
{

  if (FCL_STATE)
  {  

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 5, 1);

    #endif

  } else {

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 5, 1 - 1);

    #endif

  }

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e6_LEDMono6__TurnOff()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 5, 1 - 1);

  #endif

}


/*========================================================================*\
   Use :LEDMono5
       :GUID: 44f82374-a417-40d5-bd42-23a177a390d2
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\LED_Mono_2dgi.fcpx
       :Version: 20.0 (0x1300028)
       :Timestamp: 05\11\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e5_LEDMono5__TurnOn()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 4, 1);

  #endif

}

/*=----------------------------------------------------------------------=*\
   Use :Sets the state of the LED, accounting for the polarity.
       :
       :Parameters for macro SetState:
       :  State : 1=On, 0=Off
\*=----------------------------------------------------------------------=*/
void FCD_0e9e5_LEDMono5__SetState(MX_BOOL FCL_STATE)
{

  if (FCL_STATE)
  {  

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 4, 1);

    #endif

  } else {

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 4, 1 - 1);

    #endif

  }

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e5_LEDMono5__TurnOff()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 4, 1 - 1);

  #endif

}


/*========================================================================*\
   Use :LEDMono4
       :GUID: 44f82374-a417-40d5-bd42-23a177a390d2
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\LED_Mono_2dgi.fcpx
       :Version: 20.0 (0x1300028)
       :Timestamp: 05\11\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e4_LEDMono4__TurnOn()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 3, 1);

  #endif

}

/*=----------------------------------------------------------------------=*\
   Use :Sets the state of the LED, accounting for the polarity.
       :
       :Parameters for macro SetState:
       :  State : 1=On, 0=Off
\*=----------------------------------------------------------------------=*/
void FCD_0e9e4_LEDMono4__SetState(MX_BOOL FCL_STATE)
{

  if (FCL_STATE)
  {  

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 3, 1);

    #endif

  } else {

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 3, 1 - 1);

    #endif

  }

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e4_LEDMono4__TurnOff()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 3, 1 - 1);

  #endif

}


/*========================================================================*\
   Use :LEDMono3
       :GUID: 44f82374-a417-40d5-bd42-23a177a390d2
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\LED_Mono_2dgi.fcpx
       :Version: 20.0 (0x1300028)
       :Timestamp: 05\11\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e3_LEDMono3__TurnOn()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 2, 1);

  #endif

}

/*=----------------------------------------------------------------------=*\
   Use :Sets the state of the LED, accounting for the polarity.
       :
       :Parameters for macro SetState:
       :  State : 1=On, 0=Off
\*=----------------------------------------------------------------------=*/
void FCD_0e9e3_LEDMono3__SetState(MX_BOOL FCL_STATE)
{

  if (FCL_STATE)
  {  

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 2, 1);

    #endif

  } else {

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 2, 1 - 1);

    #endif

  }

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e3_LEDMono3__TurnOff()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 2, 1 - 1);

  #endif

}


/*========================================================================*\
   Use :LEDMono2
       :GUID: 44f82374-a417-40d5-bd42-23a177a390d2
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\LED_Mono_2dgi.fcpx
       :Version: 20.0 (0x1300028)
       :Timestamp: 05\11\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e2_LEDMono2__TurnOn()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 1, 1);

  #endif

}

/*=----------------------------------------------------------------------=*\
   Use :Sets the state of the LED, accounting for the polarity.
       :
       :Parameters for macro SetState:
       :  State : 1=On, 0=Off
\*=----------------------------------------------------------------------=*/
void FCD_0e9e2_LEDMono2__SetState(MX_BOOL FCL_STATE)
{

  if (FCL_STATE)
  {  

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 1, 1);

    #endif

  } else {

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 1, 1 - 1);

    #endif

  }

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e2_LEDMono2__TurnOff()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 1, 1 - 1);

  #endif

}


/*========================================================================*\
   Use :LEDMono1
       :GUID: 44f82374-a417-40d5-bd42-23a177a390d2
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\LED_Mono_2dgi.fcpx
       :Version: 20.0 (0x1300028)
       :Timestamp: 05\11\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e1_LEDMono1__TurnOn()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 0, 1);

  #endif

}

/*=----------------------------------------------------------------------=*\
   Use :Sets the state of the LED, accounting for the polarity.
       :
       :Parameters for macro SetState:
       :  State : 1=On, 0=Off
\*=----------------------------------------------------------------------=*/
void FCD_0e9e1_LEDMono1__SetState(MX_BOOL FCL_STATE)
{

  if (FCL_STATE)
  {  

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 0, 1);

    #endif

  } else {

    #if (0)
    //Code has been optimised out by the pre-processor
    #else
      SET_PORT_PIN(A, 0, 1 - 1);

    #endif

  }

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCD_0e9e1_LEDMono1__TurnOff()
{

  #if (0)
  //Code has been optimised out by the pre-processor
  #else
    SET_PORT_PIN(A, 0, 1 - 1);

  #endif

}

#define FCA_LED_ARRAY1 0x8011
#define FCV_LED_ARRAY1 0x0015
#define FCA_TEXT4 0x2264
#define FCV_TEXT4 0x0013
#define FCA_TEXT3 0x2263
#define FCV_TEXT3 0x0011
#define FCA_TEXT2 0x2262
#define FCV_TEXT2 0x000f
#define FCA_TEXT9 0x2261
#define FCV_TEXT9 0x000d

/*========================================================================*\
   Use :User Project
       :Variable declarations
       :Macro implementations
\*========================================================================*/
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_GLOBAL MX_SINT16 FCV_COUNT = (0);



/*========================================================================*\
   Use :Main
\*========================================================================*/
void main()
{
	#ifdef INTOSCHELPER
		INTOSCHELPERCODE
	#endif
	//Setup input pins as digital
	ANSELA = 0x00;
	ANSELB = 0x00;
	ANSELD = 0x00;
	ANSELE = 0x00;
	ANSELF = 0x00;
	ANSELG = 0x00;

	//Setup UART Remapping UART2=GLCD, UART5=USB
	RX2PPS = 0x31;
	RG0PPS = 0x0E;
	RX5PPS = 0x33;
	RG2PPS = 0x14;




  // Loop
  while (1)
  {
    // Output
    SET_PORT(A,(FCV_COUNT));

    // Output
    SET_PORT(B,(FCV_COUNT));

    // Output
    SET_PORT(C,(FCV_COUNT));

    // Output
    SET_PORT(D,(FCV_COUNT));

    // Output
    SET_PORT(E,(FCV_COUNT));

    // Output
    SET_PORT(F,(FCV_COUNT));

    // Calculation
    FCV_COUNT = FCV_COUNT + 1;

    // Delay
    FCI_DELAYBYTE_MS(10);

  }

	mainendloop: goto mainendloop;
}



/*========================================================================*\
   Use :Interrupt
\*========================================================================*/
void MX_INTERRUPT_MACRO(void)
{
	#ifdef USE_FLOWCODE_ICD3
		ICD_INTERRUPT_HANDLER
	#endif

}




