//************************************************************************************
//**  
//**  Source name:   D:\Dev\Flowcode V11\Components\IO_Source\adc\External_ADC24Bit_ADS1220.fcfx
//**  Title:         
//**  Description:   
//**  Device:        PIC16.33E.E-blocks2 16-bit dsPIC
//**  
//**  Generated by:  Flowcode v11.0.1.14
//**  Date:          Monday, April 13, 2026 16:43:50
//**  Users:         1
//**  Registered to: BenR (82702381)
//**  Licence key: 95CJQR
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#include "D:\Dev\Flowcode V11\Components\IO_Source\adc\External_ADC24Bit_ADS1220.h"

#define FCA_TYPECONVERSIONS1 0x8941
#define FCV_TYPECONVERSIONS1 0x0c2f

/*========================================================================*\
   Use :TypeConversions1
       :GUID: 6508c7be-063a-4f9f-bae5-4a41cf977a86
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\TypeConversions.fcpx
       :Version: 6.0 (0x100028)
       :Timestamp: 11\04\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :Sets a single 16-bit INT value.
       :Index is in little endian, 0 is the LSW and 1 is the MSW
       :
       :Parameters for macro SetInt:
       :  Index : Range: 0-1
       :  Value : Range: 0-65535
\*=----------------------------------------------------------------------=*/
void FCD_08941_TypeConversions1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE)
{

  if (FCL_INDEX < 2)
  {  

    MX_Conv_Var.AsInt[FCL_INDEX] = FCL_VALUE;

  // } else {

  }

}

/*=----------------------------------------------------------------------=*\
   Use :Sets a single 32-bit LONG value
       :
       :Parameters for macro SetLong:
       :  Value : Range: 0-4294967295
\*=----------------------------------------------------------------------=*/
void FCD_08941_TypeConversions1__SetLong(MX_UINT32 FCL_VALUE)
{

  MX_Conv_Var.AsLong = FCL_VALUE;

}

/*=----------------------------------------------------------------------=*\
   Use :Gets a single 32-bit FLOAT value
       :
       :Returns : MX_FLOAT
\*=----------------------------------------------------------------------=*/
MX_FLOAT FCD_08941_TypeConversions1__GetFloat()
{
  //Local variable definitions
  MX_FLOAT FCR_RETVAL;


  FCR_RETVAL = MX_Conv_Var.AsFloat;

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Gets a single 32-bit LONG value
       :
       :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCD_08941_TypeConversions1__GetLong()
{
  //Local variable definitions
  MX_UINT32 FCR_RETVAL;


  FCR_RETVAL = MX_Conv_Var.AsLong;

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Allows all bytes to be set using a single macro
       :
       :Parameters for macro SetBytes:
       :  Byte0 : MX_UINT8
       :  Byte1 : MX_UINT8
       :  Byte2 : MX_UINT8
       :  Byte3 : MX_UINT8
\*=----------------------------------------------------------------------=*/
void FCD_08941_TypeConversions1__SetBytes(MX_UINT8 FCL_BYTE0, MX_UINT8 FCL_BYTE1, MX_UINT8 FCL_BYTE2, MX_UINT8 FCL_BYTE3)
{

  MX_Conv_Var.AsByte[0] = FCL_BYTE0;
  MX_Conv_Var.AsByte[1] = FCL_BYTE1;
  MX_Conv_Var.AsByte[2] = FCL_BYTE2;
  MX_Conv_Var.AsByte[3] = FCL_BYTE3;

}

/*=----------------------------------------------------------------------=*\
   Use :Gets a single 16-bit INT value
       :Index is in little endian, 0 is the LSW and 1 is the MSW
       :
       :Parameters for macro GetInt:
       :  Index : Range: 0-1
       :
       :Returns : MX_UINT16
\*=----------------------------------------------------------------------=*/
MX_UINT16 FCD_08941_TypeConversions1__GetInt(MX_UINT8 FCL_INDEX)
{
  //Local variable definitions
  MX_UINT16 FCR_RETVAL;


  if (FCL_INDEX < 2)
  {  

    FCR_RETVAL = MX_Conv_Var.AsInt[FCL_INDEX];

  } else {

    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Sets a single 8-bit BYTE value
       :Index is in little endian, 0 is the LSB and 3 is the MSB
       :
       :Parameters for macro SetByte:
       :  Index : Range: 0-3
       :  Value : Range: 0-255
\*=----------------------------------------------------------------------=*/
void FCD_08941_TypeConversions1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE)
{

  if (FCL_INDEX < 4)
  {  

    MX_Conv_Var.AsByte[FCL_INDEX] = FCL_VALUE;

  // } else {

  }

}

/*=----------------------------------------------------------------------=*\
   Use :Gets a single 8-bit BYTE value.
       :Index is in little endian, 0 is the LSB and 3 is the MSB
       :
       :Parameters for macro GetByte:
       :  Index : Range: 0-3
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCD_08941_TypeConversions1__GetByte(MX_UINT8 FCL_INDEX)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL;


  if (FCL_INDEX < 4)
  {  

    FCR_RETVAL = MX_Conv_Var.AsByte[FCL_INDEX];

  } else {

    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Sets a single 32-bit FLOAT value
       :
       :Parameters for macro SetFloat:
       :  Value : Range: 0-4294967295
\*=----------------------------------------------------------------------=*/
void FCD_08941_TypeConversions1__SetFloat(MX_FLOAT FCL_VALUE)
{

  MX_Conv_Var.AsFloat = FCL_VALUE;

}

#define FCA_SENSORLIBRARY 0x7bd1
#define FCV_SENSORLIBRARY 0x0ad9
#define FCA_CAL_SPI1 0x1531
#define FCV_CAL_SPI1 0x0929

/*========================================================================*\
   Use :cal_spi1
       :GUID: c67171df-0ad6-4b11-8361-cfe14b072847
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\cal_spi.fcpx
       :Version: 25.0 (0x1501528)
       :Timestamp: 19\09\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
MX_GLOBAL MX_UINT32 FCV_01531_cal_spi1__CONSOLELOG;

/*=----------------------------------------------------------------------=*\
   Use :Outputs a low signal to the chip select pin to select the remote slave device.
\*=----------------------------------------------------------------------=*/
void FCD_01531_cal_spi1__Master_Enable_CS()
{
  //Local variable definitions
  #define FCLsz_STR 20
  MX_CHAR FCL_STR[FCLsz_STR];


  #if (1)
    #if (1) // 0 == 0
      #if (1)
        #if (0)
        //Code has been optimised out by the pre-processor
        // #else
        #endif

        SET_PORT_PIN(C, 2, 0);

      // #else
      //Code has been optimised out by the pre-processor
      #endif

    // #else
    //Code has been optimised out by the pre-processor
    #endif

  // #else
  //Code has been optimised out by the pre-processor
  #endif

  //Local variable definitions
  #undef FCLsz_STR
}

/*=----------------------------------------------------------------------=*\
   Use :Send text to the SPI console.
       :Exposed as part of the CAL_SPI component to allow none AutoCS pins and other.
       :
       :Parameters for macro Prv_TextConsole:
       :  str[20] : MX_CHAR (by-ref)
       :  Colour : 0=Default, 1=TX, 2=RX
       :  AppendTimestamp : 0=Don't Append / 1=Do Append
\*=----------------------------------------------------------------------=*/
void FCD_01531_cal_spi1__Prv_TextConsole(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT8 FCL_COLOUR, MX_UINT8 FCL_APPENDTIMESTAMP)
{
  //Local variable definitions
  #define FCLsz_TSTR 20
  MX_CHAR FCL_TSTR[FCLsz_TSTR];


  #if (0)
  //Code has been optimised out by the pre-processor
  // #else
  #endif

  //Local variable definitions
  #undef FCLsz_TSTR
}

/*=----------------------------------------------------------------------=*\
   Use :Parameters for macro Prv_SimShowWaveform:
       :  RXData : MX_UINT8
       :  TXData : MX_UINT16
\*=----------------------------------------------------------------------=*/
void FCD_01531_cal_spi1__Prv_SimShowWaveform(MX_UINT8 FCL_RXDATA, MX_UINT16 FCL_TXDATA)
{

  #if (0)
  //Code has been optimised out by the pre-processor
  // #else
  #endif

}

/*=----------------------------------------------------------------------=*\
   Use :Outputs a high signal to the chip select pin to deselect the remote slave device.
\*=----------------------------------------------------------------------=*/
void FCD_01531_cal_spi1__Master_Disable_CS()
{
  //Local variable definitions
  #define FCLsz_STR 20
  MX_CHAR FCL_STR[FCLsz_STR];


  #if (1)
    #if (1) // 0 == 0
      #if (1)
        #if (0)
        //Code has been optimised out by the pre-processor
        // #else
        #endif

        SET_PORT_PIN(C, 2, 1 - 0);

      // #else
      //Code has been optimised out by the pre-processor
      #endif

    // #else
    //Code has been optimised out by the pre-processor
    #endif

  // #else
  //Code has been optimised out by the pre-processor
  #endif

  //Local variable definitions
  #undef FCLsz_STR
}


/*========================================================================*\
   Use :User Project
       :Variable declarations
       :Macro implementations
\*========================================================================*/
#define FCVsz_SPI_BUFFER 10
MX_GLOBAL MX_UINT8 FCV_SPI_BUFFER[FCVsz_SPI_BUFFER]; // SPI communication buffer
MX_GLOBAL MX_UINT8 FCV_TEMP = (0x0);
MX_GLOBAL MX_UINT8 FCV_CONFIGREG3; // Configuration Register 3
MX_GLOBAL MX_UINT8 FCV_CONFIGREG2; // Configuration Register 2
MX_GLOBAL MX_UINT8 FCV_CONFIGREG1; // Configuration Register 1
MX_GLOBAL MX_UINT8 FCV_CONFIGREG0; // Configuration Register 0

/*=----------------------------------------------------------------------=*\
   Use :Called back on the panel command System.TimerStart
       :
       :Parameters for macro Ev_Timer:
       :  TimerID : The identifier passed to the System.TimerStart panel command
       :
       :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_Timer(MX_UINT32 FCL_TIMERID)
{
  //Local variable definitions
  MX_UINT32 FCL_HANDLE;
  MX_UINT32 FCR_RETVAL;


  // Comms Flashers
  // ::Component.Property.SetValue(SensorLibrary, "ShowComms", SimComms)

  // Decision
  if (0)
  {  

    // SPI Icon
    // ::Component.Property.SetValue(SensorLibrary, "OutputIcon::CommsType", 5)

    // Simulation
    // ::Component.Property.SetVisible(this, "property_1", 1)

    // Component Macro
    // .Handle=cal_spi1::GetConsoleHandle()

    // Component Macro
    // SensorLibrary::SetConsoleHandle(.Handle)

  } else {

    // No Icon
    // ::Component.Property.SetValue(SensorLibrary, "OutputIcon::CommsType", 255)

    // Simulation
    // ::Component.Property.SetVisible(this, "property_1", 0)

    // Component Macro
    // SensorLibrary::SetConsoleHandle(0)

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Write configuration registers to ADS1220
\*=----------------------------------------------------------------------=*/
void FCM_WriteConfigRegisters()
{

  // Write all 4 control registers starting from 0
  FCV_SPI_BUFFER[0] = 0x43;
  FCV_SPI_BUFFER[1] = FCV_CONFIGREG0;
  FCV_SPI_BUFFER[2] = FCV_CONFIGREG1;
  FCV_SPI_BUFFER[3] = FCV_CONFIGREG2;
  FCV_SPI_BUFFER[4] = FCV_CONFIGREG3;

  // CS Pin Low
  FCD_01531_cal_spi1__Master_Enable_CS();

  // SPI Transaction
  FC_CAL_SPI_Transaction_1(FCV_SPI_BUFFER, 10, 5);

  // CS Pin High
  FCD_01531_cal_spi1__Master_Disable_CS();

}

/*=----------------------------------------------------------------------=*\
   Use :Initialize the ADS1220 ADC
       :
       :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_Initialise()
{
  //Local variable definitions
  MX_UINT32 FCR_RETVAL;


  // Initialize SPI Master
  FC_CAL_SPI_Master_Init_1();

  // Calculation
  FCV_CONFIGREG0 = 0;
  FCV_CONFIGREG1 = 0;
  FCV_CONFIGREG2 = 0;
  FCV_CONFIGREG3 = 0;

  // Write Configuration
  FCM_WriteConfigRegisters();

  // Calculation
  FCR_RETVAL = 0;

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Performs a differential ADC sample and returns voltage in volts
       :
       :Parameters for macro SampleDiffVolts:
       :  ChannelA : Positive channel: 0-3 (AN0-AN3)
       :  ChannelB : Negative channel: 0-3 (AN0-AN3)
       :  Gain : PGA Gain: 0=1x, 1=2x, 2=4x, 3=8x, 4=16x, 5=32x, 6=64x, 7=128x
       :
       :Returns : Differential voltage in volts
\*=----------------------------------------------------------------------=*/
MX_FLOAT FCM_SampleDiffVolts(MX_UINT8 FCL_CHANNELA, MX_UINT8 FCL_CHANNELB, MX_UINT8 FCL_GAIN)
{
  //Local variable definitions
  MX_SINT32 FCL_RAWVALUE;
  MX_UINT8 FCL_GAINVALUE;
  MX_FLOAT FCR_RETVAL; // Differential voltage in volts


  // Read Raw Value
  FCL_RAWVALUE = FCM_SampleDiffRAW(FCL_CHANNELA, FCL_CHANNELB, FCL_GAIN);

  // Switch
  switch (FCL_GAIN)
  {
    case 0:
    {

      // Calculation
      FCL_GAINVALUE = 1;

      break;
    }
    case 1:
    {

      // Calculation
      FCL_GAINVALUE = 2;

      break;
    }
    case 2:
    {

      // Calculation
      FCL_GAINVALUE = 4;

      break;
    }
    case 3:
    {

      // Calculation
      FCL_GAINVALUE = 8;

      break;
    }
    case 4:
    {

      // Calculation
      FCL_GAINVALUE = 16;

      break;
    }
    case 5:
    {

      // Calculation
      FCL_GAINVALUE = 32;

      break;
    }
    case 6:
    {

      // Calculation
      FCL_GAINVALUE = 64;

      break;
    }
    case 7:
    {

      // Calculation
      FCL_GAINVALUE = 128;

      break;
    }
    default:
    {
      // Calculation
      FCL_GAINVALUE = 1;

    }
  }

  // Convert to voltage
  FCR_RETVAL = flt_div(flt_mul((flt_div(flt_fromi(FCL_RAWVALUE), 8388608.0)), 2.048), flt_fromi(FCL_GAINVALUE));

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Returns : MX_SINT32
\*=----------------------------------------------------------------------=*/
MX_SINT32 FCM_ReadSample()
{
  //Local variable definitions
  MX_UINT16 FCL_TOUT = (0x2710);
  MX_FLOAT FCL_S1 = (0.0);
  MX_FLOAT FCL_S2 = (0.0);
  MX_SINT32 FCR_RETVAL;


  // Decision
  if (0 && (0 == 0))
  {  

    // Single Ended Conversion?
    if (FCV_CONFIGREG0 & 0x80)
    {    

      // Component Macro
      // .S1=SensorLibrary::GetValue((ConfigReg0 & 0x70) >> 4)

      // Calculation
      FCL_S1 = flt_mul(FCL_S1, 8388607.0);
      FCR_RETVAL = flt_toi(FCL_S1);

    } else {

      // Switch
      switch ((FCV_CONFIGREG0 & 0x70) >> 4)
      {
        case 1:
        {

          // Component Macro
          // .S1=SensorLibrary::GetValue(0)

          // Component Macro
          // .S2=SensorLibrary::GetValue(2)

          break;
        }
        case 2:
        {

          // Component Macro
          // .S1=SensorLibrary::GetValue(0)

          // Component Macro
          // .S2=SensorLibrary::GetValue(3)

          break;
        }
        case 3:
        {

          // Component Macro
          // .S1=SensorLibrary::GetValue(1)

          // Component Macro
          // .S2=SensorLibrary::GetValue(2)

          break;
        }
        case 4:
        {

          // Component Macro
          // .S1=SensorLibrary::GetValue(1)

          // Component Macro
          // .S2=SensorLibrary::GetValue(3)

          break;
        }
        case 5:
        {

          // Component Macro
          // .S1=SensorLibrary::GetValue(2)

          // Component Macro
          // .S2=SensorLibrary::GetValue(3)

          break;
        }
        case 6:
        {

          // Component Macro
          // .S1=SensorLibrary::GetValue(1)

          // Component Macro
          // .S2=SensorLibrary::GetValue(0)

          break;
        }
        case 7:
        {

          // Component Macro
          // .S1=SensorLibrary::GetValue(3)

          // Component Macro
          // .S2=SensorLibrary::GetValue(2)

          break;
        }
        default:
        {
          // Component Macro
          // .S1=SensorLibrary::GetValue(0)

          // Component Macro
          // .S2=SensorLibrary::GetValue(1)

        }
      }

      // Calculation
      FCL_S1 = flt_sub(FCL_S1, FCL_S2);
      FCL_S1 = flt_mul(FCL_S1, 8388607.0);
      FCR_RETVAL = flt_toi(FCL_S1);

    }

  } else {

    // CS Pin Low
    FCD_01531_cal_spi1__Master_Enable_CS();

    // Continuous Mode?
    if (FCV_CONFIGREG1 & 0x04)
    {    

    } else {

      // Send START/SYNC command
      FCV_SPI_BUFFER[0] = 0x08;

      // SPI Transaction
      FC_CAL_SPI_Transaction_1(FCV_SPI_BUFFER, 10, 1);

    }

    // Wait for DRDY
    if (1)
    {    

      // Wait for up to 0.1s
      while (GET_PORT_PIN(D, 8) == 1)
      {
        // Delay
        FCI_DELAYBYTE_US(10);

        // Calculation
        FCL_TOUT = FCL_TOUT - 1;

        // Decision
        if (FCL_TOUT == 0)
        {        

          // Calculation
          FCR_RETVAL = 0;

          // Goto Connection Point
          goto FCC_ReadSample_A;

        // } else {

        }

      }

      // Send READ DATA command
      FCV_SPI_BUFFER[0] = 0;
      FCV_SPI_BUFFER[1] = 0;
      FCV_SPI_BUFFER[2] = 0;

      // SPI Transaction
      FC_CAL_SPI_Transaction_1(FCV_SPI_BUFFER, 10, 3);

      // Combine 24-bit value
      FCD_08941_TypeConversions1__SetBytes(FCV_SPI_BUFFER[2], FCV_SPI_BUFFER[1], FCV_SPI_BUFFER[0], 0);

    } else {

      // Send READ DATA command
      FCV_SPI_BUFFER[0] = 0x10;
      FCV_SPI_BUFFER[1] = 0;
      FCV_SPI_BUFFER[2] = 0;
      FCV_SPI_BUFFER[3] = 0;

      // SPI Transaction
      FC_CAL_SPI_Transaction_1(FCV_SPI_BUFFER, 10, 4);

      // Combine 24-bit value
      FCD_08941_TypeConversions1__SetBytes(FCV_SPI_BUFFER[3], FCV_SPI_BUFFER[2], FCV_SPI_BUFFER[1], 0);

#if 0 // Disabled code
      // Continuous Mode?
      if (FCV_CONFIGREG1 & 0x04)
      {      

        // Send READ DATA command
        FCV_SPI_BUFFER[0] = 0;
        FCV_SPI_BUFFER[1] = 0;
        FCV_SPI_BUFFER[2] = 0;

        // SPI Transaction
        FC_CAL_SPI_Transaction_1(FCV_SPI_BUFFER, 10, 3);

        // Combine 24-bit value
        FCD_08941_TypeConversions1__SetBytes(FCV_SPI_BUFFER[2], FCV_SPI_BUFFER[1], FCV_SPI_BUFFER[0], 0);

      // } else {

      }

#endif // Disabled code

    }

    // CS Pin High
    FCD_01531_cal_spi1__Master_Disable_CS();

    // Component Macro
    FCR_RETVAL = FCD_08941_TypeConversions1__GetLong();

    // Declare Connection Point
  FCC_ReadSample_A:
    ;

    // Check if negative
    if (FCR_RETVAL > 8388607)
    {    

      // Sign extend for 24-bit signed
      FCR_RETVAL = FCR_RETVAL - 16777216;

    // } else {

    }

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Sent when a property has been changed by the User
       :
       :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_Property()
{
  //Local variable definitions
  MX_UINT32 FCR_RETVAL;


  // Decision
  if (1 == 0)
  {  

    // Built-in Function
    // ::Component.Property.SetValue(this, "ReferenceVoltage", "2.048")

    // Built-in Function
    // ::Component.Property.SetWritable(this, "ReferenceVoltage", 0)

  } else {

    // Built-in Function
    // ::Component.Property.SetWritable(this, "ReferenceVoltage", 1)

  }

  // Built-in Function
  // ::Component.Property.SetValue(this, "TempCoefficient", "0.00385055")

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_Renamed()
{
  //Local variable definitions
  #define FCLsz_NAME 20
  MX_CHAR FCL_NAME[FCLsz_NAME];
  MX_UINT32 FCR_RETVAL;


  // 
  // .Name=::Tree.GetName(this)

  // 
  // ::Component.Property.SetValue(SensorLibrary, "Name", .Name)

  return (FCR_RETVAL);

  //Local variable definitions
  #undef FCLsz_NAME
}

/*=----------------------------------------------------------------------=*\
   Use :Reads the RTD sensor and returns resistance in ohms
       :
       :Returns : RTD resistance in ohms
\*=----------------------------------------------------------------------=*/
MX_FLOAT FCM_ReadRTDResistance()
{
  //Local variable definitions
  MX_SINT32 FCL_RAWVALUE; // 24-bit ADC raw value
  MX_FLOAT FCL_GAINVALUE; // PGA gain value (1.0, 2.0, 4.0, etc.)
  MX_UINT8 FCL_GAINREG; // Gain setting from ConfigReg0
  MX_FLOAT FCL_TEMP = (0.0);
  MX_FLOAT FCR_RETVAL; // RTD resistance in ohms


  // User Macro
  FCL_RAWVALUE = FCM_ReadSample();

  // Extract PGA gain from ConfigReg0 (bits 4-6)
  FCL_GAINREG = (FCV_CONFIGREG0 >> 1) & 0x07;

  // Convert gain register to gain value
  switch (FCL_GAINREG)
  {
    case 1:
    {

      // Gain 2x
      FCL_GAINVALUE = 2.0;

      break;
    }
    case 2:
    {

      // Gain 4x
      FCL_GAINVALUE = 4.0;

      break;
    }
    case 3:
    {

      // Gain 8x
      FCL_GAINVALUE = 8.0;

      break;
    }
    case 4:
    {

      // Gain 16x
      FCL_GAINVALUE = 16.0;

      break;
    }
    case 5:
    {

      // Gain 32x
      FCL_GAINVALUE = 32.0;

      break;
    }
    case 6:
    {

      // Gain 64x
      FCL_GAINVALUE = 64.0;

      break;
    }
    case 7:
    {

      // Gain 128x
      FCL_GAINVALUE = 128.0;

      break;
    }
    default:
    {
      // Gain 1x
      FCL_GAINVALUE = 1.0;

    }
  }

  // Calculation
  FCR_RETVAL = 0;

  // 2 Wire RTD
  if (1 == 0)
  {  

    // Calculate RTD resistance 2 Wire
    FCR_RETVAL = flt_div(flt_mul(4700, flt_fromi(FCL_RAWVALUE)), (flt_mul(8388608.0, FCL_GAINVALUE)));

  // } else {

  }

  // 3 Wire RTD - Low side ref
  if (1 == 1)
  {  

    // Calculate RTD resistance using 3W low-side reference
    FCR_RETVAL = flt_div(flt_mul(4700, flt_fromi(FCL_RAWVALUE)), (flt_mul(4194304.0, FCL_GAINVALUE)));

  // } else {

  }

  // 4 Wire RTD
  if (1 == 2)
  {  

    // Calculate RTD resistance 2 Wire
    FCR_RETVAL = flt_div(flt_mul(4700, flt_fromi(FCL_RAWVALUE)), (flt_mul(8388608.0, FCL_GAINVALUE)));

  // } else {

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Broadcast to all components that simulation is starting
       :
       :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_SimStart()
{
  //Local variable definitions
  MX_UINT32 FCR_RETVAL;


  // Built-in Function
  // ::Component.Property.SetValue(this, "IsSim", 1)

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Performs a single-ended ADC sample on the selected channel and returns 24-bit raw value
       :
       :Parameters for macro SampleSglRaw:
       :  Channel : Range: 0-3 (AN0-AN3)
       :  Gain : PGA Gain: 0=1x, 1=2x, 2=4x, 3=8x, 4=16x, 5=32x, 6=64x, 7=128x
       :
       :Returns : 24-bit ADC reading
\*=----------------------------------------------------------------------=*/
MX_SINT32 FCM_SampleSglRaw(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_GAIN)
{
  //Local variable definitions
  MX_UINT8 FCL_TEMP;
  MX_SINT32 FCR_RETVAL; // 24-bit ADC reading


  // Decision
  if (FCL_CHANNEL < 4)
  {  

    // Work out channel
    FCL_TEMP = 0x80 | ((FCL_CHANNEL & 0x03) << 4);

    // Is the channel already set correctly?
    if ((FCV_CONFIGREG0 & 0xF0) == FCL_TEMP)
    {    

    } else {

      // Calculation
      FCV_CONFIGREG0 = (FCV_CONFIGREG0 & 0x0F) | FCL_TEMP;

      // CS Pin Low
      FCD_01531_cal_spi1__Master_Enable_CS();

      // Build Write Command
      FCV_SPI_BUFFER[0] = 0x40;
      FCV_SPI_BUFFER[1] = FCV_CONFIGREG0;

      // SPI Transaction
      FC_CAL_SPI_Transaction_1(FCV_SPI_BUFFER, 10, 2);

      // CS Pin High
      FCD_01531_cal_spi1__Master_Disable_CS();

    }

    // User Macro
    FCR_RETVAL = FCM_ReadSample();

  } else {

    // Invalid channel
    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Reads the RTD sensor and returns temperature in degrees Celsius using linear approximation - matches GitHub library get_temperature_from_rtd_ohms_with_linear_approx
       :
       :Returns : Temperature in degrees Celsius
\*=----------------------------------------------------------------------=*/
MX_FLOAT FCM_ReadRTDTemperature()
{
  //Local variable definitions
  MX_FLOAT FCL_RT; // RTD resistance
  MX_FLOAT FCL_R0; // Base resistance at 0??C
  MX_FLOAT FCL_TEMP = (0.0);
  MX_FLOAT FCR_RETVAL; // Temperature in degrees Celsius


  // Read RTD Resistance
  FCL_RT = FCM_ReadRTDResistance();

  // Select R0 based on RTD type
  if (1 == 0)
  {  

    // PT100
    FCL_R0 = 100.0;

  } else {

    // PT1000
    FCL_R0 = 1000.0;

  }

  // Calculate temperature using linear approximation: T = (R - R0) / (R0 × ?)
  FCL_TEMP = (flt_mul(FCL_R0, 0.00385055));
  FCR_RETVAL = (flt_sub(FCL_RT, FCL_R0));
  FCR_RETVAL = flt_div(FCR_RETVAL, FCL_TEMP);

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Performs a single-ended ADC sample and returns voltage in volts
       :
       :Parameters for macro SampleSglVolts:
       :  Channel : Range: 0-3 (AN0-AN3)
       :  Gain : PGA Gain: 0=1x, 1=2x, 2=4x, 3=8x, 4=16x, 5=32x, 6=64x, 7=128x
       :
       :Returns : Voltage in volts
\*=----------------------------------------------------------------------=*/
MX_FLOAT FCM_SampleSglVolts(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_GAIN)
{
  //Local variable definitions
  MX_SINT32 FCL_RAWVALUE;
  MX_UINT8 FCL_GAINVALUE;
  MX_FLOAT FCR_RETVAL; // Voltage in volts


  // Read Raw Value
  FCL_RAWVALUE = FCM_SampleSglRaw(FCL_CHANNEL, FCL_GAIN);

  // Switch
  switch (FCL_GAIN)
  {
    case 0:
    {

      // Calculation
      FCL_GAINVALUE = 1;

      break;
    }
    case 1:
    {

      // Calculation
      FCL_GAINVALUE = 2;

      break;
    }
    case 2:
    {

      // Calculation
      FCL_GAINVALUE = 4;

      break;
    }
    case 3:
    {

      // Calculation
      FCL_GAINVALUE = 8;

      break;
    }
    case 4:
    {

      // Calculation
      FCL_GAINVALUE = 16;

      break;
    }
    case 5:
    {

      // Calculation
      FCL_GAINVALUE = 32;

      break;
    }
    case 6:
    {

      // Calculation
      FCL_GAINVALUE = 64;

      break;
    }
    case 7:
    {

      // Calculation
      FCL_GAINVALUE = 128;

      break;
    }
    default:
    {
      // Calculation
      FCL_GAINVALUE = 1;

    }
  }

  // Convert to voltage
  FCR_RETVAL = flt_div(flt_mul((flt_div(flt_fromi(FCL_RAWVALUE), 8388608.0)), 2.048), flt_fromi(FCL_GAINVALUE));

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Broadcast to all components that compilation is starting
       :
       :Returns : Non-zero to prevent compilation
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_CompileStart()
{
  //Local variable definitions
  MX_UINT32 FCR_RETVAL; // Non-zero to prevent compilation


  // Built-in Function
  // ::Component.Property.SetValue(this, "IsSim", 0)

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Performs a differential ADC sample between two channels and returns 24-bit raw value.
       :Not all channel combinations are possible, see datasheet p40 section MUX.
       :Returns 0 if the channel selection is invalid.
       :
       :Parameters for macro SampleDiffRAW:
       :  ChannelA : Positive channel: 0-3 (AN0-AN3)
       :  ChannelB : Negative channel: 0-3 (AN0-AN3)
       :  Gain : PGA Gain: 0=1x, 1=2x, 2=4x, 3=8x, 4=16x, 5=32x, 6=64x, 7=128x
       :
       :Returns : 24-bit differential ADC reading
\*=----------------------------------------------------------------------=*/
MX_SINT32 FCM_SampleDiffRAW(MX_UINT8 FCL_CHANNELA, MX_UINT8 FCL_CHANNELB, MX_UINT8 FCL_GAIN)
{
  //Local variable definitions
  MX_UINT8 FCL_TEMP;
  MX_SINT32 FCR_RETVAL; // 24-bit differential ADC reading


  // Decision
  if ((FCL_CHANNELA < 4) && (FCL_CHANNELB < 4) && (FCL_CHANNELA != FCL_CHANNELB))
  {  

    // Decision
    if (FCL_CHANNELA == 0)
    {    

      // Switch
      switch (FCL_CHANNELB)
      {
        case 1:
        {

          // Work out channel
          FCL_TEMP = 0x00;

          break;
        }
        case 2:
        {

          // Work out channel
          FCL_TEMP = 0x10;

          break;
        }
        case 3:
        {

          // Work out channel
          FCL_TEMP = 0x20;

          break;
        }
        default:
        {
          // Invalid channel
          FCR_RETVAL = 0;

          // Goto Connection Point
          goto FCC_SampleDiffRAW_A;

        }
      }

    // } else {

    }

    // Decision
    if (FCL_CHANNELA == 1)
    {    

      // Switch
      switch (FCL_CHANNELB)
      {
        case 2:
        {

          // Work out channel
          FCL_TEMP = 0x30;

          break;
        }
        case 3:
        {

          // Work out channel
          FCL_TEMP = 0x40;

          break;
        }
        case 0:
        {

          // Work out channel
          FCL_TEMP = 0x60;

          break;
        }
        default:
        {
          // Invalid channel
          FCR_RETVAL = 0;

          // Goto Connection Point
          goto FCC_SampleDiffRAW_A;

        }
      }

    // } else {

    }

    // Decision
    if (FCL_CHANNELA == 2)
    {    

      // Switch
      switch (FCL_CHANNELB)
      {
        case 3:
        {

          // Work out channel
          FCL_TEMP = 0x50;

          break;
        }
        default:
        {
          // Invalid channel
          FCR_RETVAL = 0;

          // Goto Connection Point
          goto FCC_SampleDiffRAW_A;

        }
      }

    // } else {

    }

    // Decision
    if (FCL_CHANNELA == 3)
    {    

      // Switch
      switch (FCL_CHANNELB)
      {
        case 2:
        {

          // Work out channel
          FCL_TEMP = 0x70;

          break;
        }
        default:
        {
          // Invalid channel
          FCR_RETVAL = 0;

          // Goto Connection Point
          goto FCC_SampleDiffRAW_A;

        }
      }

    // } else {

    }

    // Is the channel already set correctly?
    if ((FCV_CONFIGREG0 & 0xF0) == FCL_TEMP)
    {    

    } else {

      // Calculation
      FCV_CONFIGREG0 = (FCV_CONFIGREG0 & 0x0F) | FCL_TEMP;

      // CS Pin Low
      FCD_01531_cal_spi1__Master_Enable_CS();

      // Build Write Command
      FCV_SPI_BUFFER[0] = 0x40;
      FCV_SPI_BUFFER[1] = FCV_CONFIGREG0;

      // SPI Transaction
      FC_CAL_SPI_Transaction_1(FCV_SPI_BUFFER, 10, 2);

      // CS Pin High
      FCD_01531_cal_spi1__Master_Disable_CS();

    }

    // User Macro
    FCR_RETVAL = FCM_ReadSample();

  } else {

    // Invalid channel
    FCR_RETVAL = 0;

  }

  // Declare Connection Point
FCC_SampleDiffRAW_A:
  ;

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Initialize the ADS1220 ADC with default settings
       :
       :Returns : 0 = Success
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCM_Initialise()
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL; // 0 = Success


  // Initialize SPI Master
  FC_CAL_SPI_Master_Init_1();

  // Delay
  FCI_DELAYBYTE_MS(10);

  // CS Pin Low
  FCD_01531_cal_spi1__Master_Enable_CS();

  // Send RESET command
  FCV_SPI_BUFFER[0] = 0x06;

  // SPI Transaction
  FC_CAL_SPI_Transaction_1(FCV_SPI_BUFFER, 10, 1);

  // CS Pin High
  FCD_01531_cal_spi1__Master_Disable_CS();

  // Delay
  FCI_DELAYBYTE_MS(10);

  // Configure Register 0
  FCV_CONFIGREG0 = 0;
  FCV_CONFIGREG0 = FCV_CONFIGREG0 | (0 << 1);

  // Configure Register 1
  FCV_CONFIGREG1 = 0;
  FCV_CONFIGREG1 = FCV_CONFIGREG1 | (0 << 5);
  FCV_CONFIGREG1 = FCV_CONFIGREG1 | (0 << 3);
  FCV_CONFIGREG1 = FCV_CONFIGREG1 | (1 << 2);

  // Configure Register 2
  FCV_CONFIGREG2 = 0;
  FCV_CONFIGREG2 = FCV_CONFIGREG2 | (1 << 6);
  FCV_CONFIGREG2 = FCV_CONFIGREG2 | (1 << 4);
  FCV_CONFIGREG2 = FCV_CONFIGREG2 | (1);

  // Configure Register 3
  FCV_CONFIGREG3 = 0;
  FCV_CONFIGREG3 = FCV_CONFIGREG3 | (3 << 5);
  FCV_CONFIGREG3 = FCV_CONFIGREG3 | (4 << 2);
  FCV_CONFIGREG3 = FCV_CONFIGREG3 | ((1 - 1) << 1);

  // Write Configuration
  FCM_WriteConfigRegisters();

  // Continuouse Conversion needs kick starting
  if (1)
  {  

    // Send START/SYNC command
    FCV_SPI_BUFFER[0] = 0x08;

    // SPI Transaction
    FC_CAL_SPI_Transaction_1(FCV_SPI_BUFFER, 10, 1);

  // } else {

  }

  // Calculation
  FCR_RETVAL = 0;

  return (FCR_RETVAL);

}

//Main program entry point - demonstrates component usage


/*========================================================================*\
   Use :Main
\*========================================================================*/
void main()
{
	#ifdef INTOSCHELPER
		INTOSCHELPERCODE
	#endif
ANSELB = 0;
ANSELC = 0;
ANSELD = 0;
ANSELE = 0;
ANSELG = 0;
RPINR23bits.SS2R = 121;  //Map SS2 to Pin G9

//Setup configuration for 70MIPs using 8MHz Crystal
PLLFBD = 68;			// M=70
CLKDIVbits.PLLPOST = 0;		// N1=2
CLKDIVbits.PLLPRE = 0;		// N2=2
OSCTUN = 0;			//Tune FRC oscillator, if FRC is used

//Disable Watch Dog Timer
RCONbits.SWDTEN = 0;

// Clock switching to incorporate PLL
__builtin_write_OSCCONH(0x03);	// Initiate Clock Switch to Primary

// Oscillator with PLL (NOSC=0b011)
__builtin_write_OSCCONL(0x01);	// Start clock switching
while(OSCCONbits.COSC != 0b011);

// Wait for Clock switch to occur	
while(OSCCONbits.LOCK != 1);

//USB H/W initialization for 70 MIPs
ACLKCON3 = 0x24C1;
ACLKDIV3 = 0x7;

// Wait for PLL to lock
ACLKCON3bits.ENAPLL = 1;
while(ACLKCON3bits.APLLCK != 1);

#ifdef USE_FLOWCODE_ICD2
  CNPUB = 0x00C0;
#endif


  // Initialize ADC
  FCM_Initialise();

  // Sample Single Channel Raw
  FCM_SampleSglRaw(0, 0);

  // Sample Single Channel Volts
  FCM_SampleSglVolts(0, 0);

  // Sample Differential Raw
  FCM_SampleDiffRAW(0, 1, 0);

  // Sample Differential Volts
  FCM_SampleDiffVolts(0, 1, 0);

  // Read RTD Temperature
  FCM_ReadRTDTemperature();

	mainendloop: goto mainendloop;
	return 0;
}



/*========================================================================*\
   Use :Interrupt
\*========================================================================*/




