//************************************************************************************
//**  
//**  Source name:   D:\Dev\Flowcode V11\Components\IO_Source\adc\External_ADC24Bit_ADS1220.fcfx
//**  Title:         
//**  Description:   
//**  Device:        PIC16.33E.E-blocks2 16-bit dsPIC
//**  
//**  Generated by:  Flowcode v11.0.1.14
//**  Date:          Monday, April 13, 2026 16:43:50
//**  Users:         1
//**  Registered to: BenR (82702381)
//**  Licence key: 95CJQR
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#define MX_PIC16

#define MX_CAL_PIC16

#define MX_CLK_SPEED 140000000

#define FCP_NULL Unconnected_Port


#include <xc.h>
#include <math.h>
#include <stdlib.h>
#include "p33Exxxx.h"

_FGS(GWRP_OFF & GSS_OFF & GSSK_OFF);
_FOSCSEL(FNOSC_PRIPLL & IESO_ON);
_FOSC(POSCMD_HS & OSCIOFNC_OFF & IOL1WAY_OFF & FCKSM_CSECME);
_FWDT(WDTPOST_PS1024 & WDTPRE_PR128 & PLLKEN_ON & WINDIS_OFF & FWDTEN_OFF);
_FPOR(FPWRT_PWR128 & BOREN_ON & ALTI2C1_ON);
_FICD(ICS_PGD1 & RSTPRI_PF & JTAGEN_OFF);
_FAS(AWRP_OFF & APL_OFF & APLK_OFF);
_FUID0(0xFF55);
;

/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\internals.c"



MX_UINT8 FCLV_LOOP1;

MX_UINT32 FCM_Ev_Timer(MX_UINT32 FCL_TIMERID);
void FCM_WriteConfigRegisters();
MX_UINT32 FCM_Ev_Initialise();
MX_FLOAT FCM_SampleDiffVolts(MX_UINT8 FCL_CHANNELA, MX_UINT8 FCL_CHANNELB, MX_UINT8 FCL_GAIN);
MX_SINT32 FCM_ReadSample();
MX_UINT32 FCM_Ev_Property();
MX_UINT32 FCM_Ev_Renamed();
MX_FLOAT FCM_ReadRTDResistance();
MX_UINT32 FCM_Ev_SimStart();
MX_SINT32 FCM_SampleSglRaw(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_GAIN);
MX_FLOAT FCM_ReadRTDTemperature();
MX_FLOAT FCM_SampleSglVolts(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_GAIN);
MX_UINT32 FCM_Ev_CompileStart();
MX_SINT32 FCM_SampleDiffRAW(MX_UINT8 FCL_CHANNELA, MX_UINT8 FCL_CHANNELB, MX_UINT8 FCL_GAIN);
MX_UINT8 FCM_Initialise();

/*========================================================================*\
   Use :TypeConversions1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :TypeConversions1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifndef MX_UNIONTYPE
 #define MX_UNIONTYPE
 typedef union
{
  MX_FLOAT AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union_Type;
 MX_Union_Type MX_Conv_Var;
#endif


void FCD_08941_TypeConversions1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE);
void FCD_08941_TypeConversions1__SetLong(MX_UINT32 FCL_VALUE);
MX_FLOAT FCD_08941_TypeConversions1__GetFloat();
MX_UINT32 FCD_08941_TypeConversions1__GetLong();
void FCD_08941_TypeConversions1__SetBytes(MX_UINT8 FCL_BYTE0, MX_UINT8 FCL_BYTE1, MX_UINT8 FCL_BYTE2, MX_UINT8 FCL_BYTE3);
MX_UINT16 FCD_08941_TypeConversions1__GetInt(MX_UINT8 FCL_INDEX);
void FCD_08941_TypeConversions1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE);
MX_UINT8 FCD_08941_TypeConversions1__GetByte(MX_UINT8 FCL_INDEX);
void FCD_08941_TypeConversions1__SetFloat(MX_FLOAT FCL_VALUE);

/*========================================================================*\
   Use :cal_spi1
       :Macro function declarations
\*========================================================================*/
#define MX_SPI_SS_TRIS_1 trisc
#define MX_SPI_MISO_PORT_1 portc
#define MX_SPI_SCK_TRIS_1 trisc
#define MX_SPI_SCK_PIN_1 (3)
#define MX_SPI_MOSI_TRIS_1 trisc
#define MX_SPI_BMODE_1 (2)
#define MX_SPI_MISO_TRIS_1 trisc
#define MX_SPI_MOSI_PIN_1 (5)
#define MX_SPI_MISO_PIN_1 (4)
#define MX_SPI_SS_PIN_1 (2)
#define MX_SPI_PR_SCALE_1 (64)
#define MX_SPI_SS_PORT_1 portc
#define MX_SPI_USESS_1 0
#define MX_SPI_SCK_PORT_1 portc
#define MX_SPI_MOSI_PORT_1 portc
#define MX_SPI_CHANNEL_1 (1)


/*=----------------------------------------------------------------------=*\
   Use :cal_spi1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_SPI_REF1
#define MX_SPI_REMAPPABLE_1 1
#define MX_SPI_MOSI_RPOR_1 RPOR2bits.RP69R
#define MX_SPI_MOSI_SDO_1 5
#define MX_SPI_MISO_RPINR_1 RPINR20bits.SDI1R
#define MX_SPI_MISO_RP_1 20
#define MX_SPI_CLK_RPOR_1 RPOR3bits.RP71R
#define MX_SPI_CLK_SCK_1 6

void FCD_01531_cal_spi1__Master_Enable_CS();
void FC_CAL_SPI_Slave_Uninit_1();
void FCD_01531_cal_spi1__Prv_TextConsole(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT8 FCL_COLOUR, MX_UINT8 FCL_APPENDTIMESTAMP);
MX_UINT8 FC_CAL_SPI_Transaction_1(MX_UINT8 *FCL_BUFFER, MX_UINT16 FCLsz_BUFFER, MX_UINT16 FCL_LENGTH);
void FCD_01531_cal_spi1__Prv_SimShowWaveform(MX_UINT8 FCL_RXDATA, MX_UINT16 FCL_TXDATA);
void FC_CAL_SPI_Slave_Init_1();
void FCD_01531_cal_spi1__Master_Disable_CS();
void FC_CAL_SPI_Master_Uninit_1();
MX_UINT8 FC_CAL_SPI_Master_Byte_1(MX_UINT8 FCL_DATAOUT);
void FC_CAL_SPI_Slave_TxByte_1(MX_UINT8 FCL_DATA);
MX_UINT8 FC_CAL_SPI_Slave_RxByte_1();
MX_UINT8 FC_CAL_SPI_Master_Init_1();

/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\includes.c"

