// CRC: 675B15CA0DE03A7497A65F03351863B93D8DFBB3B6960DACF67DB601F837E3BE5A11A7B597E6F7EA8FE53F6FF9C4729AAFF7D054EA9B4CC9BDC419C02E9E1921B6336C11BE63C7B23E6A7110B5081D39796EDD611F6757020C3CAEE8E7DA69874F72A8E0FFF6BAB26B03417734FDB29E3B56B4E9608BE7B0EED62BE8F64CF1433C4D6AB521291475EBE8E58CB0CCE2AD1C9E057381696A8EA24B2535FC5257D0E7A48E7ED61B6A7394E281A8D4067A08232AE3563A2DB2E4549D34A0D5AD11F304612437587D555BF60C451559291572EA4561AEED75746A1EDE0E6E8CE8F293FC3F53D5103A0873
// REVISION: 3.0
// GUID: 6E365E38-6E2E-44E5-B462-5B36686836C8
// DATE: 16\09\2026
// DIR: CAL\STARM\STARM_CAL_USB_Serial.c

/*********************************************************************
 *              Flowcode CAL USB Serial CDC Comms
 *
 * File: STARM_CAL_USB_Serial.c
 *
 * (c) 2025 Matrix TSL
 * http://www.matrixTSL.com
 *
 * Software License Agreement
 *
 * The software supplied herewith by Matrix TSL (the
 * ?Company?) for its Flowcode graphical programming language is
 * intended and supplied to you, the Company?s customer, for use
 * solely and exclusively on the Company's products. The software
 * is owned by the Company, and is protected under applicable
 * copyright laws. All rights are reserved. Any use in violation
 * of the foregoing restrictions may subject the user to criminal
 * sanctions under applicable laws, as well as to civil liability
 * for the breach of the terms and conditions of this licence.
 *
 * THIS SOFTWARE IS PROVIDED IN AN ?AS IS? CONDITION. NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED
 * TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. THE COMPANY SHALL NOT,
 * IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL OR
 * CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * Changelog:
 *
 *  date  | by | description
 * -------+----+-----------------------------------------------------
 * 100725 | BR | Created (stub)
 * 160926 | BR | Implemented using STM32Cube USB Device Library (CDC-ACM class)
 *
 * Notes:
 *
 *  This file assumes that the standard, unmodified ST STM32Cube USB
 *  Device middleware (usbd_core.c/h, usbd_ctlreq.c/h, usbd_ioreq.c/h
 *  and usbd_cdc.c/h) is available on the compiler include/library
 *  path, in exactly the same way that the STM32Cube HAL drivers
 *  (HAL_UART_xxx, HAL_GPIO_xxx etc) are already assumed to be
 *  available to STARM_CAL_UART.c. This file provides the
 *  "user" portion of the USB stack that a project generated by
 *  STM32CubeMX would normally put into usbd_desc.c, usbd_conf.c and
 *  usbd_cdc_if.c, wired up to the Flowcode USB_Serial component
 *  macros.
 *
 *  USB peripheral support: this file auto detects, at compile time,
 *  whether the target device has a USB On-The-Go FS peripheral
 *  (F2/F4/F7 style - USB_OTG_FS) or a dedicated Full Speed device
 *  peripheral (F0/F1/F3/L0/L1/L4 style - USB). The IRQ number/name
 *  is selected from the MX_CAL family defines already set up in
 *  internals.c (STM32F0/STM32F1/.../STM32L4). If a new family is
 *  added to the STARM CAL and the IRQ name below does not match,
 *  update the MX_USB_IRQn / MX_USB_IRQHandler defines accordingly.
 *
 */


#define MX_USB_SERIAL_ENUM_TOUTEN_X     	CAL_APPEND(MX_USB_SERIAL_ENUM_TOUTEN_, MX_USB_SERIAL_NUM)
#define MX_USB_SERIAL_ENUM_TOUT_X     		CAL_APPEND(MX_USB_SERIAL_ENUM_TOUT_, MX_USB_SERIAL_NUM)
#define MX_USB_SERIAL_ENUM_RETURN_X     	CAL_APPEND(MX_USB_SERIAL_ENUM_RETURN_, MX_USB_SERIAL_NUM)


// USB Device middleware (standard STM32Cube USB Device Library - assumed available on the include path)
#include "usbd_core.h"
#include "usbd_ctlreq.h"
#include "usbd_cdc.h"


/*=====================================================================*\
   Peripheral / family detection
\*=====================================================================*/

#if defined(USB_OTG_FS)
	#define MX_USB_INSTANCE		USB_OTG_FS
	#define MX_USB_IS_OTG		1
#elif defined(USB_OTG_HS)
	#define MX_USB_INSTANCE		USB_OTG_HS
	#define MX_USB_IS_OTG		1
#elif defined(USB)
	#define MX_USB_INSTANCE		USB
	#define MX_USB_IS_OTG		0
#else
	#error "Unable to determine the USB peripheral for this STM32 device"
#endif

#if MX_USB_IS_OTG
	#define MX_USB_CLOCK_ENABLE()		__HAL_RCC_USB_OTG_FS_CLK_ENABLE()
#else
	#define MX_USB_CLOCK_ENABLE()		__HAL_RCC_USB_CLK_ENABLE()
#endif

#if defined(STM32F2) || defined(STM32F4) || defined(STM32F7)
	#define MX_USB_IRQn				OTG_FS_IRQn
	#define MX_USB_IRQHandler		OTG_FS_IRQHandler
#elif defined(STM32F0)
	#define MX_USB_IRQn				USB_IRQn
	#define MX_USB_IRQHandler		USB_IRQHandler
#elif defined(STM32F1)
	#define MX_USB_IRQn				USB_LP_CAN1_RX0_IRQn
	#define MX_USB_IRQHandler		USB_LP_CAN1_RX0_IRQHandler
#elif defined(STM32F3)
	#define MX_USB_IRQn				USB_LP_CAN_RX0_IRQn
	#define MX_USB_IRQHandler		USB_LP_CAN_RX0_IRQHandler
#elif defined(STM32L0)
	#define MX_USB_IRQn				USB_IRQn
	#define MX_USB_IRQHandler		USB_IRQHandler
#elif defined(STM32L1)
	#define MX_USB_IRQn				USB_LP_IRQn
	#define MX_USB_IRQHandler		USB_LP_IRQHandler
#elif defined(STM32L4)
	#define MX_USB_IRQn				USB_IRQn
	#define MX_USB_IRQHandler		USB_IRQHandler
#else
	#error "Unknown STM32 family - please add the USB IRQ name for this device"
#endif


/*=====================================================================*\
   Descriptors  (usbd_desc.c equivalent)
\*=====================================================================*/

#define MX_USBD_VID					MX_VID
#define MX_USBD_PID					MX_PID
#define MX_USBD_LANGID_STRING		0x0409		//English (US)
#define MX_USBD_CONFIGURATION_STRING_FS	"CDC Config"
#define MX_USBD_INTERFACE_STRING_FS		"CDC Interface"

//Manufacturer/Product names are set by the user in the USB_Serial component and
//generated into the project .h file as dev_manufacturer_DS / dev_name_DS (comma
//separated char lists, no null terminator) - build plain C strings from them here.
static const MX_CHAR MX_USBD_MANUFACTURER_STRING[] = {dev_manufacturer_DS, 0};
static const MX_CHAR MX_USBD_PRODUCT_STRING_FS[]   = {dev_name_DS, 0};

MX_GLOBAL MX_UINT8 USBD_FS_DeviceDesc[USB_LEN_DEV_DESC] =
{
	0x12,						/*bLength */
	USB_DESC_TYPE_DEVICE,		/*bDescriptorType*/
	0x00, 0x02,					/*bcdUSB = 2.00*/
	0x02,						/*bDeviceClass: CDC*/
	0x02,						/*bDeviceSubClass*/
	0x00,						/*bDeviceProtocol*/
	USB_MAX_EP0_SIZE,			/*bMaxPacketSize*/
	LOBYTE(MX_USBD_VID), HIBYTE(MX_USBD_VID),	/*idVendor*/
	LOBYTE(MX_USBD_PID), HIBYTE(MX_USBD_PID),	/*idProduct*/
	0x00, 0x02,					/*bcdDevice = 2.00*/
	USBD_IDX_MFC_STR,			/*Index of manufacturer string*/
	USBD_IDX_PRODUCT_STR,		/*Index of product string*/
	USBD_IDX_SERIAL_STR,		/*Index of serial number string*/
	USBD_MAX_NUM_CONFIGURATION	/*bNumConfigurations*/
};

MX_GLOBAL MX_UINT8 USBD_FS_StrDesc[USBD_MAX_STR_DESC_SIZ];


static void MX_USB_IntToUnicode(MX_UINT32 value, MX_UINT8 *pbuf, MX_UINT8 len)
{
	MX_UINT8 idx;

	for (idx = 0; idx < len; idx++)
	{
		if (((value >> 28)) < 0xA)
			pbuf[2 * idx] = (value >> 28) + '0';
		else
			pbuf[2 * idx] = (value >> 28) + 'A' - 10;

		value = value << 4;
		pbuf[2 * idx + 1] = 0;
	}
}


static MX_UINT8 *MX_USBD_FS_DeviceDescriptor(USBD_SpeedTypeDef speed, MX_UINT16 *length)
{
	*length = sizeof(USBD_FS_DeviceDesc);
	return (MX_UINT8 *)USBD_FS_DeviceDesc;
}

static MX_UINT8 *MX_USBD_FS_LangIDStrDescriptor(USBD_SpeedTypeDef speed, MX_UINT16 *length)
{
	static MX_UINT8 langId[USB_LEN_LANGID_STR_DESC] =
	{
		USB_LEN_LANGID_STR_DESC,
		USB_DESC_TYPE_STRING,
		LOBYTE(MX_USBD_LANGID_STRING), HIBYTE(MX_USBD_LANGID_STRING)
	};

	*length = sizeof(langId);
	return langId;
}

static MX_UINT8 *MX_USBD_FS_ManufacturerStrDescriptor(USBD_SpeedTypeDef speed, MX_UINT16 *length)
{
	USBD_GetString((MX_UINT8 *)MX_USBD_MANUFACTURER_STRING, USBD_FS_StrDesc, length);
	return USBD_FS_StrDesc;
}

static MX_UINT8 *MX_USBD_FS_ProductStrDescriptor(USBD_SpeedTypeDef speed, MX_UINT16 *length)
{
	USBD_GetString((MX_UINT8 *)MX_USBD_PRODUCT_STRING_FS, USBD_FS_StrDesc, length);
	return USBD_FS_StrDesc;
}

static MX_UINT8 *MX_USBD_FS_SerialStrDescriptor(USBD_SpeedTypeDef speed, MX_UINT16 *length)
{
	static MX_UINT8 serial[USB_SIZ_STRING_SERIAL];

	serial[0] = USB_SIZ_STRING_SERIAL;
	serial[1] = USB_DESC_TYPE_STRING;

	#if defined(UID_BASE)
		MX_USB_IntToUnicode(*(MX_UINT32 *)UID_BASE, &serial[2], 8);
	#else
		MX_USB_IntToUnicode(0xF10CD001, &serial[2], 8);	//Fallback fixed serial when device UID is not available
	#endif

	*length = USB_SIZ_STRING_SERIAL;
	return serial;
}

static MX_UINT8 *MX_USBD_FS_ConfigStrDescriptor(USBD_SpeedTypeDef speed, MX_UINT16 *length)
{
	USBD_GetString((MX_UINT8 *)MX_USBD_CONFIGURATION_STRING_FS, USBD_FS_StrDesc, length);
	return USBD_FS_StrDesc;
}

static MX_UINT8 *MX_USBD_FS_InterfaceStrDescriptor(USBD_SpeedTypeDef speed, MX_UINT16 *length)
{
	USBD_GetString((MX_UINT8 *)MX_USBD_INTERFACE_STRING_FS, USBD_FS_StrDesc, length);
	return USBD_FS_StrDesc;
}

USBD_DescriptorsTypeDef MX_USB_FS_Desc =
{
	MX_USBD_FS_DeviceDescriptor,
	MX_USBD_FS_LangIDStrDescriptor,
	MX_USBD_FS_ManufacturerStrDescriptor,
	MX_USBD_FS_ProductStrDescriptor,
	MX_USBD_FS_SerialStrDescriptor,
	MX_USBD_FS_ConfigStrDescriptor,
	MX_USBD_FS_InterfaceStrDescriptor,
};


/*=====================================================================*\
   Low level driver  (usbd_conf.c equivalent)
\*=====================================================================*/

MX_GLOBAL PCD_HandleTypeDef MX_USB_HANDLE_HPCD;
MX_GLOBAL USBD_HandleTypeDef MX_USB_HANDLE_HUSBD;

void MX_USB_IRQHandler(void)
{
	HAL_PCD_IRQHandler(&MX_USB_HANDLE_HPCD);
}

void HAL_PCD_MspInit(PCD_HandleTypeDef *hpcd)
{
	if (hpcd->Instance != MX_USB_INSTANCE)
		return;

	#if MX_USB_IS_OTG
		__HAL_RCC_GPIOA_CLK_ENABLE();

		GPIO_InitTypeDef GPIO_InitStruct;
		GPIO_InitStruct.Pin       = GPIO_PIN_11 | GPIO_PIN_12;
		GPIO_InitStruct.Mode      = GPIO_MODE_AF_PP;
		GPIO_InitStruct.Pull      = GPIO_NOPULL;
		GPIO_InitStruct.Speed     = GPIO_SPEED_FREQ_HIGH;
		#if defined(GPIO_AF10_OTG_FS)
			GPIO_InitStruct.Alternate = GPIO_AF10_OTG_FS;
		#endif
		HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
	#endif

	MX_USB_CLOCK_ENABLE();

	HAL_NVIC_SetPriority(MX_USB_IRQn, 3, 0);
	HAL_NVIC_EnableIRQ(MX_USB_IRQn);
}

void HAL_PCD_MspDeInit(PCD_HandleTypeDef *hpcd)
{
	if (hpcd->Instance != MX_USB_INSTANCE)
		return;

	HAL_NVIC_DisableIRQ(MX_USB_IRQn);
}

//HAL PCD callbacks - bridge into the USB Device core (usbd_core / usbd_ctlreq / usbd_ioreq)
void HAL_PCD_SetupStageCallback(PCD_HandleTypeDef *hpcd)
{
	USBD_LL_SetupStage((USBD_HandleTypeDef *)hpcd->pData, (MX_UINT8 *)hpcd->Setup);
}

void HAL_PCD_DataOutStageCallback(PCD_HandleTypeDef *hpcd, MX_UINT8 epnum)
{
	USBD_LL_DataOutStage((USBD_HandleTypeDef *)hpcd->pData, epnum, hpcd->OUT_ep[epnum].xfer_buff);
}

void HAL_PCD_DataInStageCallback(PCD_HandleTypeDef *hpcd, MX_UINT8 epnum)
{
	USBD_LL_DataInStage((USBD_HandleTypeDef *)hpcd->pData, epnum, hpcd->IN_ep[epnum].xfer_buff);
}

void HAL_PCD_SOFCallback(PCD_HandleTypeDef *hpcd)
{
	USBD_LL_SOF((USBD_HandleTypeDef *)hpcd->pData);
}

void HAL_PCD_ResetCallback(PCD_HandleTypeDef *hpcd)
{
	USBD_SpeedTypeDef speed = USBD_SPEED_FULL;

	HAL_PCD_SetAddress(hpcd, 0);
	USBD_LL_SetSpeed((USBD_HandleTypeDef *)hpcd->pData, speed);
	USBD_LL_Reset((USBD_HandleTypeDef *)hpcd->pData);
}

void HAL_PCD_SuspendCallback(PCD_HandleTypeDef *hpcd)
{
	USBD_LL_Suspend((USBD_HandleTypeDef *)hpcd->pData);
}

void HAL_PCD_ResumeCallback(PCD_HandleTypeDef *hpcd)
{
	USBD_LL_Resume((USBD_HandleTypeDef *)hpcd->pData);
}

void HAL_PCD_ISOOUTIncompleteCallback(PCD_HandleTypeDef *hpcd, MX_UINT8 epnum)
{
	USBD_LL_IsoOUTIncomplete((USBD_HandleTypeDef *)hpcd->pData, epnum);
}

void HAL_PCD_ISOINIncompleteCallback(PCD_HandleTypeDef *hpcd, MX_UINT8 epnum)
{
	USBD_LL_IsoINIncomplete((USBD_HandleTypeDef *)hpcd->pData, epnum);
}

void HAL_PCD_ConnectCallback(PCD_HandleTypeDef *hpcd)
{
	USBD_LL_DevConnected((USBD_HandleTypeDef *)hpcd->pData);
}

void HAL_PCD_DisconnectCallback(PCD_HandleTypeDef *hpcd)
{
	USBD_LL_DevDisconnected((USBD_HandleTypeDef *)hpcd->pData);
}


//USB Device core -> low level driver calls (usbd_conf.c equivalent)
USBD_StatusTypeDef USBD_LL_Init(USBD_HandleTypeDef *pdev)
{
	MX_USB_HANDLE_HPCD.pData = pdev;
	pdev->pData = &MX_USB_HANDLE_HPCD;

	MX_USB_HANDLE_HPCD.Instance = MX_USB_INSTANCE;
	MX_USB_HANDLE_HPCD.Init.dev_endpoints = 8;
	MX_USB_HANDLE_HPCD.Init.speed = PCD_SPEED_FULL;
	MX_USB_HANDLE_HPCD.Init.ep0_mps = USB_MAX_EP0_SIZE;
	MX_USB_HANDLE_HPCD.Init.phy_itface = PCD_PHY_EMBEDDED;
	MX_USB_HANDLE_HPCD.Init.Sof_enable = DISABLE;
	MX_USB_HANDLE_HPCD.Init.low_power_enable = DISABLE;
	MX_USB_HANDLE_HPCD.Init.lpm_enable = DISABLE;
	MX_USB_HANDLE_HPCD.Init.vbus_sensing_enable = DISABLE;
	MX_USB_HANDLE_HPCD.Init.use_dedicated_ep1 = DISABLE;

	HAL_PCD_Init(&MX_USB_HANDLE_HPCD);

	#if MX_USB_IS_OTG
		HAL_PCDEx_SetRxFiFo(&MX_USB_HANDLE_HPCD, 0x80);
		HAL_PCDEx_SetTxFiFo(&MX_USB_HANDLE_HPCD, 0, 0x40);
		HAL_PCDEx_SetTxFiFo(&MX_USB_HANDLE_HPCD, 1, 0x40);
	#else
		HAL_PCDEx_PMAConfig(&MX_USB_HANDLE_HPCD, 0x00, PCD_SNG_BUF, 0x18);
		HAL_PCDEx_PMAConfig(&MX_USB_HANDLE_HPCD, 0x80, PCD_SNG_BUF, 0x58);
		HAL_PCDEx_PMAConfig(&MX_USB_HANDLE_HPCD, 0x81, PCD_SNG_BUF, 0x98);
		HAL_PCDEx_PMAConfig(&MX_USB_HANDLE_HPCD, 0x01, PCD_SNG_BUF, 0xD8);
	#endif

	return USBD_OK;
}

USBD_StatusTypeDef USBD_LL_DeInit(USBD_HandleTypeDef *pdev)
{
	HAL_PCD_DeInit((PCD_HandleTypeDef *)pdev->pData);
	return USBD_OK;
}

USBD_StatusTypeDef USBD_LL_Start(USBD_HandleTypeDef *pdev)
{
	HAL_PCD_Start((PCD_HandleTypeDef *)pdev->pData);
	return USBD_OK;
}

USBD_StatusTypeDef USBD_LL_Stop(USBD_HandleTypeDef *pdev)
{
	HAL_PCD_Stop((PCD_HandleTypeDef *)pdev->pData);
	return USBD_OK;
}

USBD_StatusTypeDef USBD_LL_OpenEP(USBD_HandleTypeDef *pdev, MX_UINT8 ep_addr, MX_UINT8 ep_type, MX_UINT16 ep_mps)
{
	HAL_PCD_EP_Open((PCD_HandleTypeDef *)pdev->pData, ep_addr, ep_mps, ep_type);
	return USBD_OK;
}

USBD_StatusTypeDef USBD_LL_CloseEP(USBD_HandleTypeDef *pdev, MX_UINT8 ep_addr)
{
	HAL_PCD_EP_Close((PCD_HandleTypeDef *)pdev->pData, ep_addr);
	return USBD_OK;
}

USBD_StatusTypeDef USBD_LL_FlushEP(USBD_HandleTypeDef *pdev, MX_UINT8 ep_addr)
{
	HAL_PCD_EP_Flush((PCD_HandleTypeDef *)pdev->pData, ep_addr);
	return USBD_OK;
}

USBD_StatusTypeDef USBD_LL_StallEP(USBD_HandleTypeDef *pdev, MX_UINT8 ep_addr)
{
	HAL_PCD_EP_SetStall((PCD_HandleTypeDef *)pdev->pData, ep_addr);
	return USBD_OK;
}

USBD_StatusTypeDef USBD_LL_ClearStallEP(USBD_HandleTypeDef *pdev, MX_UINT8 ep_addr)
{
	HAL_PCD_EP_ClrStall((PCD_HandleTypeDef *)pdev->pData, ep_addr);
	return USBD_OK;
}

MX_UINT8 USBD_LL_IsStallEP(USBD_HandleTypeDef *pdev, MX_UINT8 ep_addr)
{
	PCD_HandleTypeDef *hpcd = (PCD_HandleTypeDef *)pdev->pData;

	if ((ep_addr & 0x80) == 0x80)
		return hpcd->IN_ep[ep_addr & 0x7F].is_stall;

	return hpcd->OUT_ep[ep_addr & 0x7F].is_stall;
}

USBD_StatusTypeDef USBD_LL_SetUSBAddress(USBD_HandleTypeDef *pdev, MX_UINT8 dev_addr)
{
	HAL_PCD_SetAddress((PCD_HandleTypeDef *)pdev->pData, dev_addr);
	return USBD_OK;
}

USBD_StatusTypeDef USBD_LL_Transmit(USBD_HandleTypeDef *pdev, MX_UINT8 ep_addr, MX_UINT8 *pbuf, MX_UINT16 size)
{
	HAL_PCD_EP_Transmit((PCD_HandleTypeDef *)pdev->pData, ep_addr, pbuf, size);
	return USBD_OK;
}

USBD_StatusTypeDef USBD_LL_PrepareReceive(USBD_HandleTypeDef *pdev, MX_UINT8 ep_addr, MX_UINT8 *pbuf, MX_UINT16 size)
{
	HAL_PCD_EP_Receive((PCD_HandleTypeDef *)pdev->pData, ep_addr, pbuf, size);
	return USBD_OK;
}

MX_UINT32 USBD_LL_GetRxDataSize(USBD_HandleTypeDef *pdev, MX_UINT8 ep_addr)
{
	return HAL_PCD_EP_GetRxCount((PCD_HandleTypeDef *)pdev->pData, ep_addr);
}

void USBD_LL_Delay(MX_UINT32 Delay)
{
	delay_ms(Delay);
}


/*=====================================================================*\
   CDC class interface  (usbd_cdc_if.c equivalent)
\*=====================================================================*/

#define MX_USB_RX_BUF_SZ	64
#define MX_USB_TX_BUF_SZ	64

MX_GLOBAL MX_UINT8 MX_USB_TxBuffer[MX_USB_TX_BUF_SZ];
MX_GLOBAL MX_UINT8 MX_USB_RxBuffer[MX_USB_RX_BUF_SZ];

MX_GLOBAL MX_UINT8 MX_USBSer_RxByteCount = 0;
MX_GLOBAL MX_UINT8 MX_USBSer_RxPtr = 0;
MX_GLOBAL MX_UINT8 MX_USBSer_TxBusy = 0;

static int8_t MX_CDC_Init_FS(void);
static int8_t MX_CDC_DeInit_FS(void);
static int8_t MX_CDC_Control_FS(MX_UINT8 cmd, MX_UINT8 *pbuf, MX_UINT16 length);
static int8_t MX_CDC_Receive_FS(MX_UINT8 *pbuf, MX_UINT32 *Len);
static int8_t MX_CDC_TransmitCplt_FS(MX_UINT8 *pbuf, MX_UINT32 *Len, MX_UINT8 epnum);

USBD_CDC_ItfTypeDef MX_USBD_Interface_fops_FS =
{
	MX_CDC_Init_FS,
	MX_CDC_DeInit_FS,
	MX_CDC_Control_FS,
	MX_CDC_Receive_FS,
	MX_CDC_TransmitCplt_FS
};

static int8_t MX_CDC_Init_FS(void)
{
	USBD_CDC_SetTxBuffer(&MX_USB_HANDLE_HUSBD, MX_USB_TxBuffer, 0);
	USBD_CDC_SetRxBuffer(&MX_USB_HANDLE_HUSBD, MX_USB_RxBuffer);

	MX_USBSer_RxByteCount = 0;
	MX_USBSer_RxPtr = 0;
	MX_USBSer_TxBusy = 0;

	return (USBD_OK);
}

static int8_t MX_CDC_DeInit_FS(void)
{
	return (USBD_OK);
}

static int8_t MX_CDC_Control_FS(MX_UINT8 cmd, MX_UINT8 *pbuf, MX_UINT16 length)
{
	//Line coding / control line requests are accepted but not acted upon -
	//Flowcode treats the link as a fixed configuration virtual COM port.
	return (USBD_OK);
}

static int8_t MX_CDC_Receive_FS(MX_UINT8 *Buf, MX_UINT32 *Len)
{
	//Called from USB interrupt context when a new packet of data has arrived.
	//Buf == MX_USB_RxBuffer, *Len == number of bytes received.

	MX_USBSer_RxByteCount = (MX_UINT8) (*Len);
	MX_USBSer_RxPtr = 0;

	//Re-arm reception for the next packet once this one has been drained
	USBD_CDC_SetRxBuffer(&MX_USB_HANDLE_HUSBD, MX_USB_RxBuffer);

	if (MX_USBSer_RxByteCount == 0)
		USBD_CDC_ReceivePacket(&MX_USB_HANDLE_HUSBD);

	return (USBD_OK);
}

static int8_t MX_CDC_TransmitCplt_FS(MX_UINT8 *Buf, MX_UINT32 *Len, MX_UINT8 epnum)
{
	MX_USBSer_TxBusy = 0;
	return (USBD_OK);
}

static MX_UINT8 MX_CDC_Transmit_FS(MX_UINT8 *Buf, MX_UINT16 Len)
{
	MX_UINT16 timeout = 0;
	USBD_CDC_HandleTypeDef *hcdc = (USBD_CDC_HandleTypeDef *)MX_USB_HANDLE_HUSBD.pClassData;

	if (MX_USB_HANDLE_HUSBD.dev_state != USBD_STATE_CONFIGURED)
		return (USBD_FAIL);

	//Wait for any previous packet to finish transmitting
	while ((hcdc->TxState != 0) && (timeout < 32000))
	{
		timeout = timeout + 1;
		delay_us(10);
	}

	if (hcdc->TxState != 0)
		return (USBD_BUSY);

	USBD_CDC_SetTxBuffer(&MX_USB_HANDLE_HUSBD, Buf, Len);
	return USBD_CDC_TransmitPacket(&MX_USB_HANDLE_HUSBD);
}


static MX_UINT8 MX_CDC_DrainRxByte(void)
{
	MX_UINT8 data;

	data = MX_USB_RxBuffer[MX_USBSer_RxPtr++];

	if (MX_USBSer_RxPtr >= MX_USBSer_RxByteCount)
	{
		MX_USBSer_RxPtr = 0;
		MX_USBSer_RxByteCount = 0;

		//Buffer has been fully drained - re-arm the endpoint for the next packet
		USBD_CDC_ReceivePacket(&MX_USB_HANDLE_HUSBD);
	}

	return data;
}


/*=====================================================================*\
   Flowcode CAL entry points
\*=====================================================================*/

CALFUNCTION(MX_UINT8, FC_CAL_USB_Serial_Initialise_, ())
{
	MX_UINT16 FCL_DELAY_COUNTER = 0;
	MX_UINT8  FCL_INNER = 0;

	MX_USBSer_RxByteCount = 0;
	MX_USBSer_RxPtr = 0;
	MX_USBSer_TxBusy = 0;

	USBD_Init(&MX_USB_HANDLE_HUSBD, &MX_USB_FS_Desc, 0);
	USBD_RegisterClass(&MX_USB_HANDLE_HUSBD, &USBD_CDC);
	USBD_CDC_RegisterInterface(&MX_USB_HANDLE_HUSBD, &MX_USBD_Interface_fops_FS);
	USBD_Start(&MX_USB_HANDLE_HUSBD);

	if (MX_USB_SERIAL_ENUM_TOUTEN_X)
	{
		//Wait for USB to startup and enumerate
		while ((MX_USB_HANDLE_HUSBD.dev_state != USBD_STATE_CONFIGURED) && (FCL_DELAY_COUNTER < MX_USB_SERIAL_ENUM_TOUT_X))
		{
			delay_ms(10);
			FCL_INNER = FCL_INNER + 1;

			if (FCL_INNER == 100)
			{
				FCL_DELAY_COUNTER = FCL_DELAY_COUNTER + 1;
				FCL_INNER = 0;
			}
		}

		if (MX_USB_HANDLE_HUSBD.dev_state == USBD_STATE_CONFIGURED)
			return 0;

		return 255;
	}
	else
	{
		while (MX_USB_HANDLE_HUSBD.dev_state != USBD_STATE_CONFIGURED);
		return 0;
	}
}



CALFUNCTION(MX_UINT16, FC_CAL_USB_Serial_ReadByte_, (MX_UINT8 timeout_ms))
{
	MX_UINT16 retval = 255;
	MX_UINT8 inner = 0;
	MX_UINT8 FCL_WAIT_FOREVER = 0;

	if (MX_USB_SERIAL_ENUM_RETURN_X)
		retval = 512;

	if (timeout_ms == 0)
	{
		timeout_ms = 1;
		inner = 98;
	}

	if (MX_USBSer_RxByteCount)
	{
		retval = MX_CDC_DrainRxByte();
	}
	else
	{
		if (timeout_ms == 255)
			FCL_WAIT_FOREVER = 1;

		while ((MX_USBSer_RxByteCount == 0) && (timeout_ms > 0))
		{
			inner++;
			delay_us(10);

			if (inner == 100)
			{
				inner = 0;
				if (FCL_WAIT_FOREVER == 0)
					timeout_ms--;
			}
		}

		if (MX_USBSer_RxByteCount)
			retval = MX_CDC_DrainRxByte();
	}

	return retval;
}



CALFUNCTION(void, FC_CAL_USB_Serial_ReadString_, (MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL, MX_UINT8 timeout_ms, MX_UINT8 FCL_LENGTH))
{
	MX_UINT8 FCL_WAIT_FOREVER = 0;
	MX_UINT16 inner = 0;
	MX_UINT16 idx = 0;

	if (timeout_ms == 0)
		timeout_ms = 1;

	if (timeout_ms == 255)
		FCL_WAIT_FOREVER = 1;

	if (FCL_LENGTH >= FCRsz_RETVAL)
		FCL_LENGTH = FCRsz_RETVAL - 1;

	while ((idx < FCL_LENGTH) && (timeout_ms > 0))
	{
		if (MX_USBSer_RxByteCount)
		{
			FCR_RETVAL[idx] = (MX_CHAR) MX_CDC_DrainRxByte();
			idx++;
		}
		else
		{
			inner++;
			delay_us(10);

			if (inner == 100)
			{
				inner = 0;
				if (FCL_WAIT_FOREVER == 0)
					timeout_ms--;
			}
		}
	}

	FCR_RETVAL[idx] = 0;
}



CALFUNCTION(MX_UINT8, FC_CAL_USB_Serial_SendByte_, (MX_UINT8 FCL_DATA))
{
	if (MX_USB_HANDLE_HUSBD.dev_state != USBD_STATE_CONFIGURED)
		return (2);		//USB Not Configured

	if (MX_CDC_Transmit_FS(&FCL_DATA, 1) != USBD_OK)
		return (1);		//USB Not Ready

	return (0);
}




CALFUNCTION(MX_UINT8, FC_CAL_USB_Serial_SendByteArray_, (MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT8 FCL_NUMBYTES))
{
	MX_UINT16 FCL_POINTER = 0;
	MX_UINT8  FCL_CHUNK;

	if (MX_USB_HANDLE_HUSBD.dev_state != USBD_STATE_CONFIGURED)
		return (2);		//USB Not Configured

	while (FCL_NUMBYTES)
	{
		//Break transmission up into 64 byte packets - max USB Full Speed CDC packet size.
		FCL_CHUNK = (FCL_NUMBYTES > 64) ? 64 : FCL_NUMBYTES;

		if (MX_CDC_Transmit_FS(&FCL_DATA[FCL_POINTER], FCL_CHUNK) != USBD_OK)
			return (1);		//USB Not Ready

		FCL_POINTER  += FCL_CHUNK;
		FCL_NUMBYTES -= FCL_CHUNK;
	}

	return (0);
}



CALFUNCTION(MX_UINT8, FC_CAL_USB_Serial_SendString_, (MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA))
{
	MX_UINT16 FCL_POINTER = 0;
	MX_UINT8  FCL_LENGTH;
	MX_UINT8  FCL_CHUNK;

	FCL_LENGTH = FCI_GETLENGTH(FCL_DATA, FCLsz_DATA);

	if (MX_USB_HANDLE_HUSBD.dev_state != USBD_STATE_CONFIGURED)
		return (2);		//USB Not Configured

	while (FCL_LENGTH)
	{
		//Break transmission up into 64 byte packets - max USB Full Speed CDC packet size.
		FCL_CHUNK = (FCL_LENGTH > 64) ? 64 : FCL_LENGTH;

		if (MX_CDC_Transmit_FS((MX_UINT8 *)&FCL_DATA[FCL_POINTER], FCL_CHUNK) != USBD_OK)
			return (1);		//USB Not Ready

		FCL_POINTER += FCL_CHUNK;
		FCL_LENGTH  -= FCL_CHUNK;
	}

	return (0);
}
