// CRC: 34358081B117C27F7D8358E612878F8E5F343B66182D417818220CB9C07676CFB25640F7F1F25483FD2044B839850E3ADD04A5F8AD9BEEB1823278EF8F2BA19C642ECC0A8F4400287286B72E06ADF20A1FBA30B1432743E9711B8143522C2B69E9B08AF8373476EC21A0CDF15FF0A94CA7644C7C2C7BBB84BF3D57A8AAF62D038165CF1957E445DEE77F71EB5909591A8A5C9A5EFABFB6C017AA2983B3312D814B2D2C4FF4B92A242CA22197E1705F692CD69097CC056230549D34A0D5AD11F388B24F0B63E911E4B545480DA8C6C0CE6C24310F38E1F6D17E0891B16C3AB1D1B75B7955E2A3F925
// REVISION: 2.0
// GUID: 903CC92B-D873-4772-8D35-7071C167E8C5
// DATE: 30\06\2023
// DIR: CAL\RPI\RPI_CAL_TypeDefs.c

/*********************************************************************
 *                  Flowcode CAL TypeDefs File
 *
 * File: RPI_CAL_TypeDefs.c
 *
 * (c) 2011-2018 Matrix TSL
 * http://www.matrixtsl.com
 *
 * Software License Agreement
 *
 * The software supplied herewith by Matrix TSL (the
 * “Company”) for its Flowcode graphical programming language is
 * intended and supplied to you, the Company’s customer, for use
 * solely and exclusively on the Company's products. The software
 * is owned by the Company, and is protected under applicable
 * copyright laws. All rights are reserved. Any use in violation
 * of the foregoing restrictions may subject the user to criminal
 * sanctions under applicable laws, as well as to civil liability
 * for the breach of the terms and conditions of this licence.
 *
 * THIS SOFTWARE IS PROVIDED IN AN “AS IS” CONDITION. NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED
 * TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. THE COMPANY SHALL NOT,
 * IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL OR
 * CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * Changelog:
 *
 *  date  | by | description
 * -------+----+-----------------------------------------------------
 * 070218 | LM | Created from PIC version
 *
 *
 */

// Preceeds all global variable definitions generated by Flowcode
#define MX_GLOBAL volatile

typedef signed char    	MX_SINT8;
typedef signed short   	MX_SINT16;
typedef signed long    	MX_SINT32;
typedef unsigned char  	MX_UINT8;
typedef unsigned short 	MX_UINT16;
typedef unsigned long  	MX_UINT32;
typedef char       		MX_CHAR;
typedef MX_UINT16      	MX_UINT;   // Best integer value for the platform, at least 8 bit
typedef MX_SINT16      	MX_SINT;

#define MX_STRING 		unsigned char*		// String pointer

//typedef bit     		MX_BOOL;   // Or unsigned MX_UINT8, depending on platform - Causes compile issues on XC8 if bool variable used as a function parameter
typedef MX_UINT8    	MX_BOOL;   // Or unsigned MX_UINT8, depending on platform

//typedef double       	MX_FLOAT;  // 64-bit Floating point (Real)
typedef float          	MX_FLOAT;  // 32-bit Floating point (Real)

#define MX_FSINGLE float


typedef union
{
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union32;

typedef union
{
  MX_UINT16 AsInt;
  MX_UINT8  AsByte[2];
} MX_Union16;


