// CRC: F9C65A77A483DDF22B438B7FEB8E3C81451B6760FECB07508D29EE770BB95F47ACE0EE4E1BA3BB8CCC6790EFEF7EFF81AF5024EAE86DD3983426F26037869797642ECC0A8F4400287286B72E06ADF20A1FBA30B1432743E9711B8143522C2B69F061CDBA65DB66C3DCFDABEAE59F0541739091989CCC3BCC24798E1B25A2F7B824C5553A89823CC84AC19F2A384ED1F07401B086000532A0DAF01FB9ACC97979C5113B5B210E29EFCC15A41F6E8FCECFB23BCD747C62E5E4549D34A0D5AD11F36043FE35F05B0D210C81717B59B4F0FE8841B03282B13AA6C7E9BF2E0A60D235BB3AB4325F399FDA
// REVISION: 2.0
// GUID: E7777D2F-5F1E-44F3-B8DB-D268F453E865
// DATE: 30\06\2023
// DIR: CAL\PICO\PICO_CAL_TypeDefs.c

/*********************************************************************
 *                  Flowcode CAL TypeDefs File
 *
 * File: PICO_CAL_TypeDefs.c
 *
 * (c) 2018 Matrix TSL.
 * http://www.matrixtsl.com
 *
 * Software License Agreement
 *
 * The software supplied herewith by Matrix TSL (the
 * “Company”) for its Flowcode graphical programming language is
 * intended and supplied to you, the Company’s customer, for use
 * solely and exclusively on the Company's products. The software
 * is owned by the Company, and is protected under applicable
 * copyright laws. All rights are reserved. Any use in violation
 * of the foregoing restrictions may subject the user to criminal
 * sanctions under applicable laws, as well as to civil liability
 * for the breach of the terms and conditions of this licence.
 *
 * THIS SOFTWARE IS PROVIDED IN AN “AS IS” CONDITION. NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED
 * TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. THE COMPANY SHALL NOT,
 * IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL OR
 * CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * Changelog:
 *
 *  date  | by | description
 * -------+----+-----------------------------------------------------
 * 130718 | BR | Created
 * 260521 | LM | Pico version
 *
 */


#include <stdbool.h>

// Preceeds all global variable definitions generated by Flowcode
// #define MX_GLOBAL volatile
#define MX_GLOBAL

typedef bool                MX_BOOL;   // Or unsigned char, depending on platform
typedef signed char         MX_SINT8;
typedef short signed int    MX_SINT16;
typedef signed long         MX_SINT32;
typedef unsigned char       MX_UINT8;
typedef short unsigned int  MX_UINT16;
typedef unsigned long       MX_UINT32;
typedef char                MX_CHAR;
typedef char*               MX_STRING; // String pointer

//typedef double       		MX_FLOAT;  // 64-bit Floating point (Real)
typedef float          		MX_FLOAT;  // 32-bit Floating point (Real)

typedef MX_UINT32           MX_UINT;   // Best integer value for the platform, at least 8 bit
typedef MX_SINT32           MX_SINT;

#define MX_FSINGLE float

typedef union
{
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union32;

typedef union
{
  MX_UINT16 AsInt;
  MX_UINT8  AsByte[2];
} MX_Union16;



