//************************************************************************************
//**  
//**  Source name:   D:\Dev\Flowcode V11\Components\IO_Source\mechatronics\ST3215.fcfx
//**  Title:         
//**  Description:   
//**  Device:        PIC.16F.16F1937
//**  
//**  Generated by:  Flowcode v11.0.0.8
//**  Date:          Wednesday, February 18, 2026 13:37:41
//**  Users:         1
//**  Registered to: BenR (82702381)
//**  Licence key: 95CJQR
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#include "D:\Dev\Flowcode V11\Components\IO_Source\mechatronics\ST3215.h"

#define FCA_CIRCULARBUFFER1 0x1211
#define FCV_CIRCULARBUFFER1 0x151f

/*========================================================================*\
   Use :CircularBuffer1
       :GUID: c34f9b8a-a915-4f75-ad0c-87f2ad670a8a
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\CircularBuffer.fcpx
       :Version: 7.0 (0x100628)
       :Timestamp: 11\04\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
#define FCVsz_01211_CircularBuffer1__DATA 32
MX_GLOBAL MX_UINT16 FCV_01211_CircularBuffer1__DATAEND = (0x0);
MX_GLOBAL MX_UINT8 FCV_01211_CircularBuffer1__LOOKFORCOUNTER = (0x0);
MX_GLOBAL MX_UINT8 FCV_01211_CircularBuffer1__DATA[FCVsz_01211_CircularBuffer1__DATA];
MX_GLOBAL MX_UINT16 FCV_01211_CircularBuffer1__DATASTART = (0x0);

/*=----------------------------------------------------------------------=*\
   Use :Scans the buffer for an array of specific values.
       :Returns 0 if the value is not found.
       :Returns 1 if the value is found.
       :
       :Parameters for macro LookForValue:
       :  Value[20] : Value to look for, can be a string or byte array,
       :  NumChars : The number of characters you wish to try and match
       :  RemoveContent : 0=Leave data alone, 1=Remove data from buffer
       :  ResetFind : 0=Continue the find from the last operation, 1=Start again
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCD_01211_CircularBuffer1__LookForValue(MX_CHAR *FCL_VALUE, MX_UINT16 FCLsz_VALUE, MX_UINT8 FCL_NUMCHARS, MX_UINT8 FCL_REMOVECONTENT, MX_UINT8 FCL_RESETFIND)
{
  //Local variable definitions
  MX_UINT8 FCL_COMPAREDATA;
  MX_UINT8 FCL_NUMBYTES;
  MX_UINT16 FCL_DATAINDEX;
  MX_UINT16 FCL_SEARCHINDEX;
  MX_UINT8 FCR_RETVAL;


  FCR_RETVAL = 0;

  if (FCL_RESETFIND == 1)
  {  

    FCV_01211_CircularBuffer1__LOOKFORCOUNTER = 0;

  // } else {

  }

  FCL_SEARCHINDEX = FCV_01211_CircularBuffer1__LOOKFORCOUNTER;

  FCL_NUMBYTES = FCD_01211_CircularBuffer1__GetNumberBytes();

  while (FCL_NUMCHARS > FCV_01211_CircularBuffer1__LOOKFORCOUNTER)
  {
    if (FCL_NUMBYTES > 0)
    {    

      if (FCL_REMOVECONTENT == 1)
      {      

        FCL_COMPAREDATA = FCD_01211_CircularBuffer1__GetByte();

      } else {

        FCL_DATAINDEX = FCV_01211_CircularBuffer1__DATASTART + FCL_SEARCHINDEX;

        if (FCL_DATAINDEX >= 32)
        {        

          FCL_DATAINDEX = FCL_DATAINDEX - 32;

        // } else {

        }

        FCL_COMPAREDATA = FCV_01211_CircularBuffer1__DATA[FCL_DATAINDEX];

        FCL_SEARCHINDEX = FCL_SEARCHINDEX + 1;

      }

      if (FCL_COMPAREDATA == FCL_VALUE[FCV_01211_CircularBuffer1__LOOKFORCOUNTER])
      {      

        FCV_01211_CircularBuffer1__LOOKFORCOUNTER = FCV_01211_CircularBuffer1__LOOKFORCOUNTER + 1;

        if (FCV_01211_CircularBuffer1__LOOKFORCOUNTER == FCL_NUMCHARS)
        {        

          FCV_01211_CircularBuffer1__LOOKFORCOUNTER = 0;

          FCL_NUMCHARS = 0;
          FCR_RETVAL = 1;

        // } else {

        }

      } else {

        if (FCV_01211_CircularBuffer1__LOOKFORCOUNTER > 0)
        {        

          FCV_01211_CircularBuffer1__LOOKFORCOUNTER = 0;

          if (FCL_COMPAREDATA == FCL_VALUE[FCV_01211_CircularBuffer1__LOOKFORCOUNTER])
          {          

            FCV_01211_CircularBuffer1__LOOKFORCOUNTER = FCV_01211_CircularBuffer1__LOOKFORCOUNTER + 1;

          // } else {

          }

        // } else {

        }

      }

      FCL_NUMBYTES = FCL_NUMBYTES - 1;

    } else {

      FCL_NUMCHARS = 0;

    }

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Reads an array of Bytes from the circular buffer.
       :
       :Parameters for macro GetArray:
       :  Data[1000] : Data array to store the data into
       :  NumBytes : Number of bytes to read from the buffer
\*=----------------------------------------------------------------------=*/
void FCD_01211_CircularBuffer1__GetArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES)
{
  //Local variable definitions
  MX_UINT16 FCL_IDX = (0x0);


  while (FCL_IDX < FCL_NUMBYTES)
  {
    FCL_DATA[FCL_IDX] = FCD_01211_CircularBuffer1__GetByte();

    FCL_IDX = FCL_IDX + 1;

  }

}

/*=----------------------------------------------------------------------=*\
   Use :Reads a string of characters from the circular buffer.
       :
       :Parameters for macro GetString:
       :  MaxLength : Max number of bytes the string can store including the null byte
       :
       :Returns : MX_CHAR*
\*=----------------------------------------------------------------------=*/
void FCD_01211_CircularBuffer1__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL, MX_UINT16 FCL_MAXLENGTH)
{
  //Local variable definitions
  MX_UINT16 FCL_IDX = (0x0);


  if (FCL_MAXLENGTH > 1)
  {  

    FCL_MAXLENGTH = FCL_MAXLENGTH - 1;

  // } else {

  }

  while (FCL_IDX < FCL_MAXLENGTH)
  {
    FCR_RETVAL[FCL_IDX] = FCD_01211_CircularBuffer1__GetByte();

    if ((FCR_RETVAL[FCL_IDX] == 0) || (FCR_RETVAL[FCL_IDX] == 255))
    {    

      goto FCC_GetString_A;

    } else {

      FCL_IDX = FCL_IDX + 1;

    }

  }

FCC_GetString_A:
  ;

  FCR_RETVAL[FCL_IDX] = 0;

}

/*=----------------------------------------------------------------------=*\
   Use :Writes an array of bytes into the circular buffer.
       :
       :Parameters for macro PutArray:
       :  Data[1000] : Byte array to write into the buffer
       :  NumBytes : Number of bytes to write into the buffer
\*=----------------------------------------------------------------------=*/
void FCD_01211_CircularBuffer1__PutArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES)
{
  //Local variable definitions
  MX_UINT16 FCL_IDX = (0x0);


  while (FCL_IDX < FCL_NUMBYTES)
  {
    FCD_01211_CircularBuffer1__PutByte(FCL_DATA[FCL_IDX]);

    FCL_IDX = FCL_IDX + 1;

  }

}

/*=----------------------------------------------------------------------=*\
   Use :Gets the value of a single byte at a known location in the buffer.
       :Leaves the buffer contents and pointers untouched.
       :
       :Parameters for macro GetIndexedByte:
       :  address : MX_UINT16
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCD_01211_CircularBuffer1__GetIndexedByte(MX_UINT16 FCL_ADDRESS)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL;


  if (FCL_ADDRESS < 32)
  {  

    FCR_RETVAL = FCV_01211_CircularBuffer1__DATA[FCL_ADDRESS];

  } else {

    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Waits for an array of values to appear in the circular buffer.
       :Returns 0 to indicate a timeout.
       :Returns 1 to indicate the data has been found.
       :
       :Parameters for macro WaitForValue:
       :  Value[20] : MX_CHAR (by-ref)
       :  NumChars : Number of characters to try and look for
       :  RemoveContent : 0=Leave the buffer contents untouched, 1=Remove values as you go
       :  Timeout : Max amount of time to wait in milliseconds before returning 0=WaitForever
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCD_01211_CircularBuffer1__WaitForValue(MX_CHAR *FCL_VALUE, MX_UINT16 FCLsz_VALUE, MX_UINT8 FCL_NUMCHARS, MX_UINT8 FCL_REMOVECONTENT, MX_UINT16 FCL_TIMEOUT)
{
  //Local variable definitions
  MX_UINT8 FCL_WAITFOREVER = (0x0);
  MX_UINT8 FCR_RETVAL;


  FCR_RETVAL = 0;

  if (FCL_TIMEOUT == 0)
  {  

    FCL_WAITFOREVER = 1;
    FCL_TIMEOUT = 0xFFFF;

  // } else {

  }

  while ((FCL_TIMEOUT > 0) && (FCR_RETVAL == 0))
  {
    FCI_DELAYBYTE_MS(1);

    if (FCL_WAITFOREVER == 0)
    {    

      FCL_TIMEOUT = FCL_TIMEOUT - 1;

    // } else {

    }

    FCR_RETVAL = FCD_01211_CircularBuffer1__LookForValue(FCL_VALUE, FCLsz_VALUE, FCL_NUMCHARS, FCL_REMOVECONTENT, 0);

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Returns the number of valid data bytes currently inside the buffer.
       :
       :Returns : MX_UINT16
\*=----------------------------------------------------------------------=*/
MX_UINT16 FCD_01211_CircularBuffer1__GetNumberBytes()
{
  //Local variable definitions
  MX_UINT16 FCR_RETVAL;


  //Comment:
  //Jump directly to the answer

  if (FCV_01211_CircularBuffer1__DATAEND > FCV_01211_CircularBuffer1__DATASTART)
  {  

    FCR_RETVAL = FCV_01211_CircularBuffer1__DATAEND - FCV_01211_CircularBuffer1__DATASTART;

  } else {

    if (FCV_01211_CircularBuffer1__DATAEND < FCV_01211_CircularBuffer1__DATASTART)
    {    

      FCR_RETVAL = (32 - FCV_01211_CircularBuffer1__DATASTART) + FCV_01211_CircularBuffer1__DATAEND;

    } else {

      FCR_RETVAL = 0;

    }

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Reads the next available byte from the circular buffer without advancing the current index,
       :Returns 255/512 if the buffer is empty.
       :
       :Returns : MX_UINT16
\*=----------------------------------------------------------------------=*/
MX_UINT16 FCD_01211_CircularBuffer1__PeekByte()
{
  //Local variable definitions
  MX_UINT16 FCL_TEMP;
  MX_UINT16 FCR_RETVAL;


  if (FCV_01211_CircularBuffer1__DATASTART != FCV_01211_CircularBuffer1__DATAEND)
  {  

    FCR_RETVAL = FCV_01211_CircularBuffer1__DATA[FCV_01211_CircularBuffer1__DATASTART];

  } else {

    #if (0) // 0 == 1
    //Code has been optimised out by the pre-processor
    #else
      FCR_RETVAL = 255;

    #endif

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Writes a string of characters into the circular buffer.
       :
       :Parameters for macro PutString:
       :  Data[20] : String data array to write into the buffer
\*=----------------------------------------------------------------------=*/
void FCD_01211_CircularBuffer1__PutString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA)
{
  //Local variable definitions
  MX_UINT16 FCL_IDX = (0x0);
  MX_UINT16 FCL_LEN;


  FCL_LEN = FCI_GETLENGTH(FCL_DATA, FCLsz_DATA);

  while (FCL_IDX < FCL_LEN)
  {
    FCD_01211_CircularBuffer1__PutByte(FCL_DATA[FCL_IDX]);

    FCL_IDX = FCL_IDX + 1;

  }

}

/*=----------------------------------------------------------------------=*\
   Use :Add byte to the next free location inside the circular buffer.
       :If the data goes into the buffer correctly then return 1.
       :Otherwise the buffer is full and the return value will equal 0.
       :
       :Parameters for macro PutByte:
       :  Data : MX_UINT8
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCD_01211_CircularBuffer1__PutByte(MX_UINT8 FCL_DATA)
{
  //Local variable definitions
  MX_UINT16 FCL_TEMP;
  MX_UINT16 FCL_TEMP2;
  MX_UINT8 FCR_RETVAL;


  FCL_TEMP = FCV_01211_CircularBuffer1__DATAEND + 1;

  if (FCL_TEMP >= 32)
  {  

    FCL_TEMP = 0;

  // } else {

  }

  if (FCL_TEMP != FCV_01211_CircularBuffer1__DATASTART)
  {  

    FCV_01211_CircularBuffer1__DATA[FCV_01211_CircularBuffer1__DATAEND] = FCL_DATA;

    FCV_01211_CircularBuffer1__DATAEND = FCL_TEMP;

    FCR_RETVAL = 1;

  } else {

    #if (1) // 1 == 1
      FCL_TEMP2 = FCV_01211_CircularBuffer1__DATASTART + 1;

      if (FCL_TEMP2 >= 32)
      {      

        FCL_TEMP2 = 0;

      // } else {

      }

      FCV_01211_CircularBuffer1__DATASTART = FCL_TEMP2;

      FCV_01211_CircularBuffer1__DATA[FCV_01211_CircularBuffer1__DATAEND] = FCL_DATA;

      FCV_01211_CircularBuffer1__DATAEND = FCL_TEMP;

      FCR_RETVAL = 1;

    #else
    //Code has been optimised out by the pre-processor
    #endif

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Reads the next available byte from the circular buffer,
       :Returns 255 if the buffer is empty.
       :
       :Returns : MX_UINT16
\*=----------------------------------------------------------------------=*/
MX_UINT16 FCD_01211_CircularBuffer1__GetByte()
{
  //Local variable definitions
  MX_UINT16 FCL_TEMP;
  MX_UINT16 FCR_RETVAL;


  if (FCV_01211_CircularBuffer1__DATASTART != FCV_01211_CircularBuffer1__DATAEND)
  {  

    FCR_RETVAL = FCV_01211_CircularBuffer1__DATA[FCV_01211_CircularBuffer1__DATASTART];

    FCL_TEMP = FCV_01211_CircularBuffer1__DATASTART + 1;

    if (FCL_TEMP >= 32)
    {    

      FCL_TEMP = 0;

    // } else {

    }

    FCV_01211_CircularBuffer1__DATASTART = FCL_TEMP;

  } else {

    #if (0) // 0 == 1
    //Code has been optimised out by the pre-processor
    #else
      FCR_RETVAL = 255;

    #endif

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Returns the number of bytes that can be stored in the buffer.
       :Either in total or the number of bytes remaining based on Mode.
       :
       :Parameters for macro GetSize:
       :  Mode : 0=TotalBufferSize, 1=BufferFreeSpace
       :
       :Returns : MX_UINT16
\*=----------------------------------------------------------------------=*/
MX_UINT16 FCD_01211_CircularBuffer1__GetSize(MX_BOOL FCL_MODE)
{
  //Local variable definitions
  MX_UINT16 FCL_NUMBYTES;
  MX_UINT16 FCR_RETVAL;


  FCR_RETVAL = 32 - 1;

  if (FCL_MODE)
  {  

    FCL_NUMBYTES = FCD_01211_CircularBuffer1__GetNumberBytes();

    FCR_RETVAL = FCR_RETVAL - FCL_NUMBYTES;

  // } else {

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Clears the contents of the buffer and re-initialises the index locations.
\*=----------------------------------------------------------------------=*/
void FCD_01211_CircularBuffer1__FlushBuffer()
{

  FCV_01211_CircularBuffer1__DATAEND = 0;
  FCV_01211_CircularBuffer1__DATASTART = 0;

}

#define FCA_LIBRARYCOMPONENT1 0xf084
#define FCV_LIBRARYCOMPONENT1 0x14e3

/*========================================================================*\
   Use :TypeConversionsFree1
       :GUID: 
       :Location: 
       :Version:  (0x0)
       :Timestamp: 
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :Sets a single 16-bit INT value.
       :Index is in little endian, 0 is the LSW and 1 is the MSW
       :
       :Parameters for macro SetInt:
       :  Index : Range: 0-1
       :  Value : Range: 0-65535
\*=----------------------------------------------------------------------=*/
void FCD_02571_TypeConversionsFree1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE)
{

  if (FCL_INDEX < 2)
  {  

    // C Code
    MX_Conv_Var.AsInt[FCL_INDEX] = FCL_VALUE;

  // } else {

  }

}

/*=----------------------------------------------------------------------=*\
   Use :Sets a single 32-bit LONG value
       :
       :Parameters for macro SetLong:
       :  Value : Range: 0-4294967295
\*=----------------------------------------------------------------------=*/
void FCD_02571_TypeConversionsFree1__SetLong(MX_UINT32 FCL_VALUE)
{

  // C Code
  MX_Conv_Var.AsLong = FCL_VALUE;

}

/*=----------------------------------------------------------------------=*\
   Use :Gets a single 32-bit FLOAT value
       :
       :Returns : MX_FLOAT
\*=----------------------------------------------------------------------=*/
MX_FLOAT FCD_02571_TypeConversionsFree1__GetFloat()
{
  //Local variable definitions
  MX_FLOAT FCR_RETVAL;


  // C Code
  FCR_RETVAL = MX_Conv_Var.AsFloat;

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Gets a single 32-bit LONG value
       :
       :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCD_02571_TypeConversionsFree1__GetLong()
{
  //Local variable definitions
  MX_UINT32 FCR_RETVAL;


  // C Code
  FCR_RETVAL = MX_Conv_Var.AsLong;

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Gets a single 16-bit INT value
       :Index is in little endian, 0 is the LSW and 1 is the MSW
       :
       :Parameters for macro GetInt:
       :  Index : Range: 0-1
       :
       :Returns : MX_UINT16
\*=----------------------------------------------------------------------=*/
MX_UINT16 FCD_02571_TypeConversionsFree1__GetInt(MX_UINT8 FCL_INDEX)
{
  //Local variable definitions
  MX_UINT16 FCR_RETVAL;


  if (FCL_INDEX < 2)
  {  

    // C Code
    FCR_RETVAL = MX_Conv_Var.AsInt[FCL_INDEX];

  } else {

    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Sets a single 8-bit BYTE value
       :Index is in little endian, 0 is the LSB and 3 is the MSB
       :
       :Parameters for macro SetByte:
       :  Index : Range: 0-3
       :  Value : Range: 0-255
\*=----------------------------------------------------------------------=*/
void FCD_02571_TypeConversionsFree1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE)
{

  if (FCL_INDEX < 4)
  {  

    // C Code
    MX_Conv_Var.AsByte[FCL_INDEX] = FCL_VALUE;

  // } else {

  }

}

/*=----------------------------------------------------------------------=*\
   Use :Gets a single 8-bit BYTE value.
       :Index is in little endian, 0 is the LSB and 3 is the MSB
       :
       :Parameters for macro GetByte:
       :  Index : Range: 0-3
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCD_02571_TypeConversionsFree1__GetByte(MX_UINT8 FCL_INDEX)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL;


  if (FCL_INDEX < 4)
  {  

    // C Code
    FCR_RETVAL = MX_Conv_Var.AsByte[FCL_INDEX];

  } else {

    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Sets a single 32-bit FLOAT value
       :
       :Parameters for macro SetFloat:
       :  Value : Range: 0-4294967295
\*=----------------------------------------------------------------------=*/
void FCD_02571_TypeConversionsFree1__SetFloat(MX_FLOAT FCL_VALUE)
{

  // C Code
  MX_Conv_Var.AsFloat = FCL_VALUE;

}

#define FCA_CAL_UART 0x5481
#define FCV_CAL_UART 0x125b

/*========================================================================*\
   Use :cal_uart
       :GUID: 91b64b1d-b8b2-40f1-b073-e953a91fa234
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\cal_uart.fcpx
       :Version: 25.0 (0x1300328)
       :Timestamp: 19\09\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
MX_GLOBAL MX_BOOL FCV_05481_cal_uart__RS485_STATE;
MX_GLOBAL MX_UINT32 FCV_05481_cal_uart__CONSOLE;

/*=----------------------------------------------------------------------=*\
   Use :Allows direct control over the TX and RTS pins
       :Also allows for reading of the state of the RX and CTS pins.
       :Only available when the UART is uninitialised.
       :
       :Parameters for macro ControlPin:
       :  Pin : 0=TX, 1=RX, 2=RTS, 3=CTS
       :  State : MX_UINT8
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCD_05481_cal_uart__ControlPin(MX_UINT8 FCL_PIN, MX_UINT8 FCL_STATE)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL;


  FCR_RETVAL = 0;

  switch (FCL_PIN)
  {
    case 1:
    {

      #if (1)
        FCR_RETVAL = GET_PORT_PIN(C, 7);

      // #else
      //Code has been optimised out by the pre-processor
      #endif

      break;
    }
    case 2:
    {

      #if (0)
      //Code has been optimised out by the pre-processor
      // #else
      #endif

      break;
    }
    case 3:
    {

      #if (0)
      //Code has been optimised out by the pre-processor
      // #else
      #endif

      break;
    }
    default:
    {
      #if (1)
        if (FCL_STATE)
        {        

          SET_PORT_PIN(C, 6, 1);

        } else {

          SET_PORT_PIN(C, 6, 0);

        }

      // #else
      //Code has been optimised out by the pre-processor
      #endif

    }
  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Transmits a string of bytes via the UART peripheral
       :
       :Parameters for macro SendString:
       :  Data[200] : Data String to transmit
\*=----------------------------------------------------------------------=*/
void FCD_05481_cal_uart__SendString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA)
{
  //Local variable definitions
  MX_UINT16 FCL_IDX;
  MX_UINT16 FCL_LEN;


  FCL_LEN = FCI_GETLENGTH(FCL_DATA, FCLsz_DATA);
  FCL_IDX = 0;

  while (FCL_IDX < FCL_LEN)
  {
    FC_CAL_UART_Send_1(FCL_DATA[FCL_IDX]);

    FCL_IDX = FCL_IDX + 1;

  }

}

/*=----------------------------------------------------------------------=*\
   Use :Parameters for macro Prv_TextConsole:
       :  Str[20] : MX_CHAR (by-ref)
       :  colour : MX_UINT8
\*=----------------------------------------------------------------------=*/
void FCD_05481_cal_uart__Prv_TextConsole(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT8 FCL_COLOUR)
{

  #if (0)
  //Code has been optimised out by the pre-processor
  // #else
  #endif

}

/*=----------------------------------------------------------------------=*\
   Use :A simple macro to allow us to test the value of a single property during runtime.
       :
       :Parameters for macro TestProperty:
       :  Property : 0=UseTX, 1=UseRX, 2=UseFlowControl
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCD_05481_cal_uart__TestProperty(MX_UINT8 FCL_PROPERTY)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL;


  FCR_RETVAL = 0;

  if (FCL_PROPERTY == 0)
  {  

    #if (1)
      FCR_RETVAL = 1;

    // #else
    //Code has been optimised out by the pre-processor
    #endif

  // } else {

  }

  if (FCL_PROPERTY == 1)
  {  

    #if (1)
      FCR_RETVAL = 1;

    // #else
    //Code has been optimised out by the pre-processor
    #endif

  // } else {

  }

  if (FCL_PROPERTY == 2)
  {  

    #if (0)
    //Code has been optimised out by the pre-processor
    // #else
    #endif

  // } else {

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Transmits a numeric value as an ASCII string
       :
       :Parameters for macro SendNumber:
       :  Number : Numeric value to send
\*=----------------------------------------------------------------------=*/
void FCD_05481_cal_uart__SendNumber(MX_SINT32 FCL_NUMBER)
{
  //Local variable definitions
  #define FCLsz_NUMSTR 20
  MX_CHAR FCL_NUMSTR[FCLsz_NUMSTR];


  FCI_TOSTRING(FCL_NUMBER, FCL_NUMSTR,20);

  FCD_05481_cal_uart__SendString(FCL_NUMSTR, FCLsz_NUMSTR);

  //Local variable definitions
  #undef FCLsz_NUMSTR
}

/*=----------------------------------------------------------------------=*\
   Use :Parameters for macro Prv_SimShowWaveform:
       :  TXRX : MX_UINT8
       :  Data : MX_UINT16
\*=----------------------------------------------------------------------=*/
void FCD_05481_cal_uart__Prv_SimShowWaveform(MX_UINT8 FCL_TXRX, MX_UINT16 FCL_DATA)
{

  #if (0)
  //Code has been optimised out by the pre-processor
  // #else
  #endif

}

/*=----------------------------------------------------------------------=*\
   Use :Transmits an array of bytes via the UART peripheral
       :
       :Parameters for macro SendByteArray:
       :  Data[32768] : Data to transmit
       :  NumBytes : Number of bytes to send from the array
\*=----------------------------------------------------------------------=*/
void FCD_05481_cal_uart__SendByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES)
{
  //Local variable definitions
  MX_UINT16 FCL_IDX;


  FCL_IDX = 0;

  while (FCL_IDX < FCL_NUMBYTES)
  {
    FC_CAL_UART_Send_1(FCL_DATA[FCL_IDX]);

    FCL_IDX = FCL_IDX + 1;

  }

}

/*=----------------------------------------------------------------------=*\
   Use :Receives an array of bytes and returns the number of bytes received.
       :
       :Parameters for macro ReceiveByteArray:
       :  Data[32768] : MX_UINT8
       :  NumBytes : Maximum number of bytes to try and receive
       :  Timeout : Max amount of time in ms to wait between bytes
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCD_05481_cal_uart__ReceiveByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT)
{
  //Local variable definitions
  MX_UINT16 FCL_IDX;
  MX_UINT16 FCL_IN;
  MX_UINT16 FCL_TOUT;
  MX_UINT8 FCR_RETVAL;


  #if (1)
    FCL_TOUT = 256;

  #else
  //Code has been optimised out by the pre-processor
  #endif

  FCR_RETVAL = 0;

  while (FCR_RETVAL < FCL_NUMBYTES)
  {
    FCL_IN = FC_CAL_UART_Receive_1(FCL_TIMEOUT);

    if (FCL_IN < FCL_TOUT)
    {    

      FCL_DATA[FCR_RETVAL] = FCL_IN;

      FCR_RETVAL = FCR_RETVAL + 1;

    } else {

      goto FCC_ReceiveByteArray_A;

    }

  }

FCC_ReceiveByteArray_A:
  ;

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Receives a string of bytes and returns the number of bytes received.
       :
       :Parameters for macro ReceiveString:
       :  StringData[20] : MX_CHAR (by-ref)
       :  NumBytes : Maximum number of bytes to try and receive
       :  Timeout : Max amount of time in ms to wait between bytes
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCD_05481_cal_uart__ReceiveString(MX_CHAR *FCL_STRINGDATA, MX_UINT16 FCLsz_STRINGDATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT)
{
  //Local variable definitions
  MX_UINT16 FCL_IDX;
  MX_UINT16 FCL_IN;
  MX_UINT16 FCL_TOUT;
  MX_UINT8 FCR_RETVAL;


  #if (1)
    FCL_TOUT = 256;

  #else
  //Code has been optimised out by the pre-processor
  #endif

  FCR_RETVAL = 0;

  while (FCR_RETVAL < FCL_NUMBYTES)
  {
    FCL_IN = FC_CAL_UART_Receive_1(FCL_TIMEOUT);

    if (FCL_IN < FCL_TOUT)
    {    

      FCL_STRINGDATA[FCR_RETVAL] = FCL_IN;

      FCR_RETVAL = FCR_RETVAL + 1;

    } else {

      goto FCC_ReceiveString_A;

    }

  }

FCC_ReceiveString_A:
  ;

  FCL_STRINGDATA[FCR_RETVAL] = 0;

  return (FCR_RETVAL);

}


/*========================================================================*\
   Use :User Project
       :Variable declarations
       :Macro implementations
\*========================================================================*/
#define FCVsz_PACKETBUFFER 20
#define FCVsz_RESPONSEBUFFER 20
#define FCV_ST3215_HEADER2 (0xff) // STS protocol header byte 2
#define FCV_ST3215_HEADER1 (0xff) // STS protocol header byte 1
#define FCV_ST3215_CMD_WRITE (0x3) // Write command
#define FCV_ST3215_ADDR_LOAD (0x3c) // Load register address
#define FCV_ST3215_ADDR_VOLTAGE (0x3e) // Voltage register address
#define FCV_ST3215_ADDR_TORQUE_ENABLE (0x28) // Torque enable register address
#define FCV_ST3215_ADDR_CURRENT_SPEED (0x3a) // Current speed register address
#define FCV_ST3215_MODE_POSITION (0x0) // Position servo mode
#define FCV_ST3215_ADDR_STATUS (0x41) // Servo status register address
#define FCV_ST3215_ADDR_POSITION (0x2a) // Position register address
#define FCV_ST3215_ADDR_SPEED (0x2e) // Speed register address
#define FCV_ST3215_ADDR_TEMP (0x3f) // Temperature register address
#define FCV_ST3215_ADDR_LOCK (0x37) // EEPROM lock flag register address
#define FCV_ST3215_ADDR_TORQUE_LIMIT (0x30) // Torque limit register address
#define FCV_ST3215_ADDR_ACCEL (0x29) // Acceleration register address
#define FCV_ST3215_ADDR_BAUDRATE (0x4) // Baud rate register address
#define FCV_ST3215_MODE_PWM (0x2) // PWM open-loop speed regulation mode
#define FCV_ST3215_CMD_READ (0x2) // Read command
#define FCV_ST3215_ADDR_CURRENT_POS (0x38) // Current position register address
#define FCV_ST3215_ADDR_MOVING (0x42) // Moving flag register address
#define FCV_ST3215_ADDR_ID (0x5) // Servo ID register address
#define FCV_ST3215_MODE_SPEED (0x1) // Constant speed mode
#define FCV_ST3215_CMD_PING (0x1) // Ping command
#define FCV_ST3215_ADDR_MODE (0xb) // Mode register address
#define FCV_ST3215_ADDR_OPERATION_TIME (0x2c) // Operation time register address (for continuous rotation)
#define FCV_ST3215_ADDR_CORRECTION (0x1c) // Position correction register address
#define FCV_ST3215_MODE_STEP (0x3) // Step servo mode
MX_GLOBAL MX_UINT8 FCV_PACKETBUFFER[FCVsz_PACKETBUFFER]; // Buffer for building STS protocol packets
MX_GLOBAL MX_UINT8 FCV_RESPONSELENGTH = (0x0); // Length of received response
MX_GLOBAL MX_UINT8 FCV_RESPONSEBUFFER[FCVsz_RESPONSEBUFFER]; // Buffer for receiving responses

/*=----------------------------------------------------------------------=*\
   Use :Read temperature in degrees Celsius.
       :
       :Parameters for macro ReadTemperature:
       :  ServoID : Servo ID
       :
       :Returns : Temperature in Celsius, or 0 if error
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCM_ReadTemperature(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL; // Temperature in Celsius, or 0 if error


  // Store register address
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_TEMP;
  FCV_PACKETBUFFER[1] = 1;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received
  if (FCV_RESPONSELENGTH >= 1)
  {  

    // Get temperature value
    FCR_RETVAL = FCV_RESPONSEBUFFER[2];

  } else {

    // Calculation
    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Set torque limit value (0-1000). Controls maximum torque output.
       :
       :Parameters for macro SetTorqueLimit:
       :  ServoID : Servo ID
       :  TorqueLimit : Torque limit value (0-1000)
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_SetTorqueLimit(MX_UINT8 FCL_SERVOID, MX_UINT16 FCL_TORQUELIMIT)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if successful


  // Store register address and torque limit bytes
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_TORQUE_LIMIT;
  FCV_PACKETBUFFER[1] = FCL_TORQUELIMIT;
  FCV_PACKETBUFFER[2] = FCL_TORQUELIMIT >> 8;

  // Send write packet
  FCR_RETVAL = FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 3);

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Read servo status flags. Returns status byte with bits: Voltage, Sensor, Temperature, Current, Angle, Overload
       :
       :Parameters for macro ReadStatus:
       :  ServoID : Servo ID
       :
       :Returns : Status byte, or 0 if error
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCM_ReadStatus(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL; // Status byte, or 0 if error


  // Store register address
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_STATUS;
  FCV_PACKETBUFFER[1] = 1;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received
  if (FCV_RESPONSELENGTH >= 1)
  {  

    // Get status value
    FCR_RETVAL = FCV_RESPONSEBUFFER[2];

  } else {

    // Calculation
    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Sent to a component to allow dynamic amendment of the interrupts for a component
       :
       :Parameters for macro Ev_AddInterrupts:
       :  HandlerCode[20] : Text to amend for all component interrupts
       :
       :Returns : Non-zero to block code insertion
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_AddInterrupts(MX_CHAR *FCL_HANDLERCODE, MX_UINT16 FCLsz_HANDLERCODE)
{
  //Local variable definitions
  #define FCLsz_ISR_MACRO 20
  MX_CHAR FCL_ISR_MACRO[FCLsz_ISR_MACRO] = "";
  #define FCLsz_UART_STR 20
  MX_CHAR FCL_UART_STR[FCLsz_UART_STR] = "";
  MX_UINT32 FCR_RETVAL; // Non-zero to block code insertion


  // Simulation
  // .ISR_Macro=::Expand.MacroBody("Uart_isr", this, 0)

  // Calculation
  {
  MX_CHAR FCI_TMP_STR[MX_MAX_TMPSTR_SIZE];
  FCI_SHEAD("MX_UART_INT_CH",15, FCI_ITOS32(001, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE),20, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE);
  FCI_SHEAD(FCI_TMP_STR,MX_MAX_TMPSTR_SIZE, "_FUNC\n\n",8, FCL_UART_STR,20);
  FCI_SHEAD(FCL_UART_STR,FCLsz_UART_STR, "MX_UINT8 FCL_RX;\n\n",19, FCL_UART_STR,20);
  FCI_SHEAD(FCL_UART_STR,FCLsz_UART_STR, "if (MX_UART_INT_CH",19, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE);
  FCI_SHEAD(FCI_TMP_STR,MX_MAX_TMPSTR_SIZE, FCI_ITOS32(001, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE),20, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE);
  FCI_SHEAD(FCI_TMP_STR,MX_MAX_TMPSTR_SIZE, "_DET)\n{\n\n",10, FCL_UART_STR,20);
  }

  // Calculation
  FCI_SHEAD(FCL_UART_STR,FCLsz_UART_STR, FCL_ISR_MACRO,FCLsz_ISR_MACRO, FCL_ISR_MACRO,20);

  // Calculation
  {
  MX_CHAR FCI_TMP_STR[MX_MAX_TMPSTR_SIZE];
  FCI_SHEAD(FCL_ISR_MACRO,FCLsz_ISR_MACRO, "MX_UART_INT_CH",15, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE);
  FCI_SHEAD(FCI_TMP_STR,MX_MAX_TMPSTR_SIZE, FCI_ITOS32(001, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE),20, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE);
  FCI_SHEAD(FCI_TMP_STR,MX_MAX_TMPSTR_SIZE, "_CLR;",6, FCL_ISR_MACRO,20);
  FCI_SHEAD(FCL_ISR_MACRO,FCLsz_ISR_MACRO, "\n\n}\n\nMX_UART_INT_FUNC_END\n",27, FCL_ISR_MACRO,20);
  }

  // Calculation
  {
  MX_CHAR FCI_TMP_STR[MX_MAX_TMPSTR_SIZE];
  FCI_SHEAD(FCL_HANDLERCODE,FCLsz_HANDLERCODE, "\n\n",3, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE);
  FCI_SHEAD(FCI_TMP_STR,MX_MAX_TMPSTR_SIZE, FCL_ISR_MACRO,FCLsz_ISR_MACRO, FCL_HANDLERCODE,20);
  }

  // Calculation
  FCR_RETVAL = 0;

  return (FCR_RETVAL);

  //Local variable definitions
  #undef FCLsz_ISR_MACRO
  #undef FCLsz_UART_STR
}

/*=----------------------------------------------------------------------=*\
   Use :Set servo acceleration in steps per second squared.
       :
       :Parameters for macro SetAcceleration:
       :  ServoID : Servo ID
       :  Acceleration : Acceleration value (0-254)
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_SetAcceleration(MX_UINT8 FCL_SERVOID, MX_UINT8 FCL_ACCELERATION)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if successful


  // Store register address and acceleration byte
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_ACCEL;
  FCV_PACKETBUFFER[1] = FCL_ACCELERATION;

  // Send write packet
  FCR_RETVAL = FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 2);

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Change the servo ID. New ID must be 0-253. EEPROM must be unlocked. Note: New ID takes effect after power cycle.
       :
       :Parameters for macro ChangeID:
       :  ServoID : Current servo ID
       :  NewID : New servo ID (0-253)
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_ChangeID(MX_UINT8 FCL_SERVOID, MX_UINT8 FCL_NEWID)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if successful


  // Store register address and new ID value (register 5 = STS_ID)
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_ID;
  FCV_PACKETBUFFER[1] = FCL_NEWID;

  // Send write packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 2);

  // Receive and verify response
  FCR_RETVAL = FCM_Prv_ReceiveResponse(100);

  // If successful, wait for ID change to take effect (1 second required)
  if (FCR_RETVAL)
  {  

    // Delay for ID change to take effect - ST3215 requires 1 second
    FCI_DELAYINT_MS(1000);

  // } else {

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Initialisation routine for the component once the component is linked to its parent
       :
       :Returns : Non-zero to prevent initialisation
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_Initialise()
{
  //Local variable definitions
  MX_UINT32 FCR_RETVAL; // Non-zero to prevent initialisation


  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Enable torque (start servo).
       :
       :Parameters for macro StartServo:
       :  ServoID : Servo ID
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_StartServo(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if successful


  // Store register address and value (1 = enable)
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_TORQUE_ENABLE;
  FCV_PACKETBUFFER[1] = 1;

  // Send write packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 2);

  // Receive and verify response
  FCR_RETVAL = FCM_Prv_ReceiveResponse(100);

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Scan and return a list of all responsive servos. 
       :Returns number of servos found.
       :
       :Parameters for macro ListServos:
       :  ServoList[20] : Array to store found servo IDs
       :  MaxCount : Max number of servos to try and return. 0=Don't limit
       :
       :Returns : Number of servos found
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCM_ListServos(MX_UINT8 *FCL_SERVOLIST, MX_UINT16 FCLsz_SERVOLIST, MX_UINT8 FCL_MAXCOUNT)
{
  //Local variable definitions
  MX_UINT8 FCL_SERVOID = (0x0); // Current servo ID being tested
  MX_BOOL FCL_FOUND = (0); // Whether current servo responded
  MX_UINT8 FCR_RETVAL; // Number of servos found


  // Initialize count
  FCR_RETVAL = 0;

  // Scan all possible servo IDs
  while (FCL_SERVOID < 254)
  {
    // Ping servo
    FCL_FOUND = FCM_PingServo(FCL_SERVOID);

    // If servo responded
    if (FCL_FOUND)
    {    

      // Add to list
      FCL_SERVOLIST[FCR_RETVAL] = FCL_SERVOID;
      FCR_RETVAL = FCR_RETVAL + 1;

      // Decision
      if (FCR_RETVAL == FCL_MAXCOUNT)
      {      

        // End Loop
        FCL_SERVOID = 253;

      // } else {

      }

    // } else {

    }

    // Next servo ID
    FCL_SERVOID = FCL_SERVOID + 1;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Read current position of servo. Returns position in steps (0-4095).
       :
       :Parameters for macro ReadPosition:
       :  ServoID : Servo ID
       :
       :Returns : Position in steps (0-4095), or -1 if error
\*=----------------------------------------------------------------------=*/
MX_SINT16 FCM_ReadPosition(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_UINT16 FCL_RAWPOSITION = (0x0); // Raw 16-bit position value
  MX_SINT16 FCR_RETVAL; // Position in steps (0-4095), or -1 if error


  // Store register address
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_CURRENT_POS;
  FCV_PACKETBUFFER[1] = 2;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received
  if (FCV_RESPONSELENGTH >= 2)
  {  

    // Combine bytes - Python library sts_makeword uses data[0] as low byte, data[1] as high byte. Our ResponseBuffer[2] appears to be high byte, ResponseBuffer[3] is low byte, so swap them.
    FCL_RAWPOSITION = FCV_RESPONSEBUFFER[3] + (FCV_RESPONSEBUFFER[2] << 8);

    // Mask to 12 bits (0-4095) as per ST3215 specification
    FCR_RETVAL = FCL_RAWPOSITION & 0x0FFF;

  } else {

    // Return error value
    FCR_RETVAL = -1;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Check if the servo is currently moving. Returns True if moving, False otherwise.
       :
       :Parameters for macro IsMoving:
       :  ServoID : Servo ID
       :
       :Returns : True if moving
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_IsMoving(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if moving


  // Store register address
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_MOVING;
  FCV_PACKETBUFFER[1] = 1;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received and moving
  if ((FCV_RESPONSELENGTH >= 1) && (FCV_RESPONSEBUFFER[2] == 1))
  {  

    // Set return to true
    FCR_RETVAL = 1;

  } else {

    // Set return to false
    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Read torque limit value (0-1000).
       :
       :Parameters for macro ReadTorqueLimit:
       :  ServoID : Servo ID
       :
       :Returns : Torque limit value, or 0 if error
\*=----------------------------------------------------------------------=*/
MX_UINT16 FCM_ReadTorqueLimit(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_UINT16 FCR_RETVAL; // Torque limit value, or 0 if error


  // Store register address
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_TORQUE_LIMIT;
  FCV_PACKETBUFFER[1] = 2;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received
  if (FCV_RESPONSELENGTH >= 2)
  {  

    // Combine bytes to form torque limit
    FCR_RETVAL = FCV_RESPONSEBUFFER[2] + (FCV_RESPONSEBUFFER[3] << 8);

  } else {

    // Calculation
    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Disable torque (stop servo).
       :
       :Parameters for macro StopServo:
       :  ServoID : Servo ID
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_StopServo(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if successful


  // Store register address and value (0 = disable)
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_TORQUE_ENABLE;
  FCV_PACKETBUFFER[1] = 0;

  // Send write packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 2);

  // Receive and verify response
  FCR_RETVAL = FCM_Prv_ReceiveResponse(100);

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Read voltage in volts (0.1V resolution). Returns voltage * 10.
       :
       :Parameters for macro ReadVoltage:
       :  ServoID : Servo ID
       :
       :Returns : Voltage * 10, or 0 if error
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCM_ReadVoltage(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL; // Voltage * 10, or 0 if error


  // Store register address
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_VOLTAGE;
  FCV_PACKETBUFFER[1] = 1;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received
  if (FCV_RESPONSELENGTH >= 1)
  {  

    // Get voltage value
    FCR_RETVAL = FCV_RESPONSEBUFFER[2];

  } else {

    // Calculation
    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Rotate servo continuously in specified direction. Speed range: 50-1000. Direction: 0=forward, 1=reverse.
       :
       :Parameters for macro Rotate:
       :  ServoID : Servo ID
       :  Speed : Rotation speed (50-1000)
       :  Direction : Direction: 0=forward, 1=reverse
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_Rotate(MX_UINT8 FCL_SERVOID, MX_UINT16 FCL_SPEED, MX_UINT8 FCL_DIRECTION)
{
  //Local variable definitions
  MX_UINT16 FCL_SPEEDWITHDIRECTION = (0x0); // Speed value with direction bit
  MX_BOOL FCL_MODERESULT = (0); // Result of setting mode
  MX_BOOL FCR_RETVAL; // True if successful


  // Set mode to constant speed mode first
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_MODE;
  FCV_PACKETBUFFER[1] = FCV_ST3215_MODE_SPEED;

  // Send write packet to mode register
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 2);

  // Receive response for mode set
  FCL_MODERESULT = FCM_Prv_ReceiveResponse(100);

  // Set speed with direction bit (BIT10 = direction)
  FCL_SPEEDWITHDIRECTION = FCL_SPEED;
  FCL_SPEEDWITHDIRECTION = FCL_SPEEDWITHDIRECTION + (FCL_DIRECTION << 10);

  // Store register address and speed bytes with direction
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_SPEED;
  FCV_PACKETBUFFER[1] = FCL_SPEEDWITHDIRECTION;
  FCV_PACKETBUFFER[2] = FCL_SPEEDWITHDIRECTION >> 8;

  // Send write packet to speed register
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 3);

  // Receive and verify response
  FCR_RETVAL = FCM_Prv_ReceiveResponse(100);

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Sent when a property has been changed by the User
       :
       :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_Property()
{
  //Local variable definitions
  #define FCLsz_TEMPSTR 20
  MX_CHAR FCL_TEMPSTR[FCLsz_TEMPSTR] = "";
  MX_UINT32 FCR_RETVAL;


  // Built-in Function
  // .TempStr=::Component.Property.GetValue(cal_uart, "CHANNEL")

  // Built-in Function
  // ::Component.Property.SetValue(this, "UARTidx", .TempStr)

  return (FCR_RETVAL);

  //Local variable definitions
  #undef FCLsz_TEMPSTR
}

/*=----------------------------------------------------------------------=*\
   Use :Receive response packet from servo
       :
       :Parameters for macro Prv_ReceiveResponse:
       :  Timeout : Timeout in milliseconds
       :
       :Returns : True if valid response received
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_Prv_ReceiveResponse(MX_UINT16 FCL_TIMEOUT)
{
  //Local variable definitions
  MX_UINT8 FCL_HEADER1 = (0x0); // First header byte
  MX_UINT8 FCL_HEADER2 = (0x0); // Second header byte
  MX_UINT8 FCL_IDX = (0x0); // Loop index
  MX_UINT16 FCL_TIMEOUTCOUNT = (0x0); // Timeout counter
  MX_BOOL FCR_RETVAL; // True if valid response received


  // Initialize response length
  FCV_RESPONSELENGTH = 0;
  FCR_RETVAL = 0;

  // Wait for header byte 1
  while ((FCL_HEADER1 != FCV_ST3215_HEADER1) && (FCL_TIMEOUTCOUNT < FCL_TIMEOUT))
  {
    // Decision
    if (FCD_01211_CircularBuffer1__GetNumberBytes())
    {    

      // Check for received byte
      FCL_HEADER1 = FCD_01211_CircularBuffer1__GetByte();

    } else {

      // Delay
      FCI_DELAYBYTE_MS(1);

      // Increment timeout
      FCL_TIMEOUTCOUNT = FCL_TIMEOUTCOUNT + 1;

    }

  }

  // Check if header 1 received
  if (FCL_HEADER1 == FCV_ST3215_HEADER1)
  {  

    // Wait for header byte 2
    while ((FCL_HEADER2 == 0) && (FCL_TIMEOUTCOUNT < FCL_TIMEOUT))
    {
      // Decision
      if (FCD_01211_CircularBuffer1__GetNumberBytes() >= 3)
      {      

        // Check for received byte
        FCL_HEADER2 = FCD_01211_CircularBuffer1__GetByte();

      } else {

        // Delay
        FCI_DELAYBYTE_MS(1);

        // Increment timeout
        FCL_TIMEOUTCOUNT = FCL_TIMEOUTCOUNT + 1;

      }

    }

    // Check if header 2 is correct
    if (FCL_HEADER2 == FCV_ST3215_HEADER2)
    {    

      // Receive ID
      FCV_RESPONSEBUFFER[0] = FCD_01211_CircularBuffer1__GetByte();

      // Receive Length
      FCV_RESPONSEBUFFER[1] = FCD_01211_CircularBuffer1__GetByte();

      // Calculate number of data bytes
      FCV_RESPONSELENGTH = FCV_RESPONSEBUFFER[1] - 2;

      // Receive all data bytes
      while (FCL_IDX < FCV_RESPONSELENGTH)
      {
        // Decision
        if (FCD_01211_CircularBuffer1__GetNumberBytes() >= 3)
        {        

          // Receive Length
          FCV_RESPONSEBUFFER[FCL_IDX + 2] = FCD_01211_CircularBuffer1__GetByte();

          // Increment index
          FCL_IDX = FCL_IDX + 1;

          // Decision
          if (FCL_IDX > 17)
          {          

            // Goto Connection Point
            goto FCC_Prv_ReceiveResponse_A;

          // } else {

          }

        } else {

          // Delay
          FCI_DELAYBYTE_MS(1);

          // Increment timeout
          FCL_TIMEOUTCOUNT = FCL_TIMEOUTCOUNT + 1;

        }

      }

      // Mark as successful
      FCR_RETVAL = 1;

      // Declare Connection Point
    FCC_Prv_ReceiveResponse_A:
      ;

    // } else {

    }

  // } else {

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Read current operational mode. Returns: 0=position, 1=speed, 2=PWM, 3=step
       :
       :Parameters for macro ReadMode:
       :  ServoID : Servo ID
       :
       :Returns : Mode value, or 255 if error
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCM_ReadMode(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL; // Mode value, or 255 if error


  // Store register address
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_MODE;
  FCV_PACKETBUFFER[1] = 1;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received
  if (FCV_RESPONSELENGTH >= 1)
  {  

    // Get mode value
    FCR_RETVAL = FCV_RESPONSEBUFFER[2];

  } else {

    // Calculation
    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Set operational mode. Mode: 0=position, 1=speed, 2=PWM, 3=step
       :
       :Parameters for macro SetMode:
       :  ServoID : Servo ID
       :  Mode : Mode: 0=position, 1=speed, 2=PWM, 3=step
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_SetMode(MX_UINT8 FCL_SERVOID, MX_UINT8 FCL_MODE)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if successful


  // Store register address and mode value
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_MODE;
  FCV_PACKETBUFFER[1] = FCL_MODE;

  // Send write packet
  FCR_RETVAL = FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 2);

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Set servo speed in steps per second.
       :
       :Parameters for macro SetSpeed:
       :  ServoID : Servo ID
       :  Speed : Speed in steps per second (0-3400)
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_SetSpeed(MX_UINT8 FCL_SERVOID, MX_UINT16 FCL_SPEED)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if successful


  // Store register address and speed bytes
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_SPEED;
  FCV_PACKETBUFFER[1] = FCL_SPEED;
  FCV_PACKETBUFFER[2] = FCL_SPEED >> 8;

  // Send write packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 3);

  // Receive and verify response
  FCR_RETVAL = FCM_Prv_ReceiveResponse(100);

#if 0 // Disabled code
  // Calculation
  FCR_RETVAL = 1;

#endif // Disabled code

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Move servo to a target angle. Angle range: -180 to 180 degrees.
       :
       :Parameters for macro MoveToAngle:
       :  ServoID : Servo ID
       :  Angle : Angle range: -180 to 180 degrees.
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_MoveToAngle(MX_UINT8 FCL_SERVOID, MX_FLOAT FCL_ANGLE)
{
  //Local variable definitions
  MX_UINT16 FCL_POSITION = (0x0);
  MX_BOOL FCR_RETVAL; // True if successful


  // Convert angle to step position
  FCL_ANGLE = flt_add(FCL_ANGLE, 180.0);
  FCL_ANGLE = flt_mul(FCL_ANGLE, 11.37777);
  FCL_POSITION = flt_toi(FCL_ANGLE);
  FCL_POSITION = FCL_POSITION & 0x0FFF;

  // User Macro
  FCR_RETVAL = FCM_MoveTo(FCL_SERVOID, FCL_POSITION);

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Lock EEPROM to prevent writes from being saved after power loss. IMPORTANT: Use the NEW servo ID after ChangeID.
       :
       :Parameters for macro LockEEPROM:
       :  ServoID : Servo ID (use NEW ID after ChangeID)
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_LockEEPROM(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if successful


  // Store register address and lock value (1 = lock, 0 = unlock)
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_LOCK;
  FCV_PACKETBUFFER[1] = 1;

  // Send write packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 2);

  // Receive and verify response
  FCR_RETVAL = FCM_Prv_ReceiveResponse(200);

  // If successful, wait for EEPROM lock to take effect (2 seconds required)
  if (FCR_RETVAL)
  {  

    // Delay for EEPROM lock to take effect - ST3215 requires 2 seconds
    FCI_DELAYINT_MS(2000);

  // } else {

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Read position correction value in steps.
       :
       :Parameters for macro ReadCorrection:
       :  ServoID : Servo ID
       :
       :Returns : Correction value in steps, or 0 if error
\*=----------------------------------------------------------------------=*/
MX_SINT16 FCM_ReadCorrection(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_SINT16 FCR_RETVAL; // Correction value in steps, or 0 if error


  // Store register address
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_CORRECTION;
  FCV_PACKETBUFFER[1] = 2;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received
  if (FCV_RESPONSELENGTH >= 2)
  {  

    // Combine bytes to form correction value
    FCR_RETVAL = FCV_RESPONSEBUFFER[2] + (FCV_RESPONSEBUFFER[3] << 8);

  } else {

    // Calculation
    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Check if a servo is responding. Returns True if successful, False otherwise.
       :
       :Parameters for macro PingServo:
       :  ServoID : Servo ID to ping (0-253)
       :
       :Returns : True if servo responds
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_PingServo(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if servo responds


  // Send ping packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_PING, 0);

  // Receive response
  FCR_RETVAL = FCM_Prv_ReceiveResponse(20);

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Read the servo ID from EEPROM. Returns the stored ID value.
       :
       :Parameters for macro ReadID:
       :  ServoID : Servo ID to query
       :
       :Returns : Servo ID value, or 255 if error
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCM_ReadID(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL; // Servo ID value, or 255 if error


  // Store register address
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_ID;
  FCV_PACKETBUFFER[1] = 1;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received
  if (FCV_RESPONSELENGTH >= 1)
  {  

    // Get ID value
    FCR_RETVAL = FCV_RESPONSEBUFFER[2];

  } else {

    // Return error value
    FCR_RETVAL = 255;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Send an STS protocol packet to the servo
       :
       :Parameters for macro Prv_SendPacket:
       :  ServoID : Servo ID (0-253)
       :  Instruction : Instruction byte
       :  ParamCount : Number of parameter bytes
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_Prv_SendPacket(MX_UINT8 FCL_SERVOID, MX_UINT8 FCL_INSTRUCTION, MX_UINT8 FCL_PARAMCOUNT)
{
  //Local variable definitions
  MX_UINT8 FCL_LENGTH = (0x0); // Packet length
  MX_UINT8 FCL_CHECKSUM = (0x0); // Calculated checksum
  MX_UINT8 FCL_IDX = (0x0); // Loop index
  MX_BOOL FCR_RETVAL; // True if successful


  // Calculate packet length (parameters + 2)
  FCL_LENGTH = FCL_PARAMCOUNT + 2;

  // Calculate checksum
  FCL_CHECKSUM = FCM_Prv_CalculateChecksum(FCL_SERVOID, FCL_LENGTH, FCL_INSTRUCTION, FCL_PARAMCOUNT);

  // Send header byte 1
  FC_CAL_UART_Send_1(FCV_ST3215_HEADER1);

  // Send header byte 2
  FC_CAL_UART_Send_1(FCV_ST3215_HEADER2);

  // Send servo ID
  FC_CAL_UART_Send_1(FCL_SERVOID);

  // Send length
  FC_CAL_UART_Send_1(FCL_LENGTH);

  // Send instruction
  FC_CAL_UART_Send_1(FCL_INSTRUCTION);

  // Send all parameter bytes
  while (FCL_IDX < FCL_PARAMCOUNT)
  {
    // Send parameter byte
    FC_CAL_UART_Send_1(FCV_PACKETBUFFER[FCL_IDX]);

    // Increment index
    FCL_IDX = FCL_IDX + 1;

  }

  // Send checksum
  FC_CAL_UART_Send_1(FCL_CHECKSUM);

  // Component Macro
  FCD_01211_CircularBuffer1__FlushBuffer();

  // Return success
  FCR_RETVAL = 1;

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Read motor load in percentage. Returns load percentage.
       :
       :Parameters for macro ReadLoad:
       :  ServoID : Servo ID
       :
       :Returns : Load percentage, or 0 if error
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCM_ReadLoad(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL; // Load percentage, or 0 if error


  // Store register address
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_LOAD;
  FCV_PACKETBUFFER[1] = 2;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received
  if (FCV_RESPONSELENGTH >= 2)
  {  

    // Get load value
    FCR_RETVAL = FCV_RESPONSEBUFFER[2];

  } else {

    // Calculation
    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Unlock EEPROM to allow writes to be saved after power loss.
       :
       :Parameters for macro UnlockEEPROM:
       :  ServoID : Servo ID
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_UnlockEEPROM(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if successful


  // Store register address and unlock value (0 = unlock, 1 = lock)
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_LOCK;
  FCV_PACKETBUFFER[1] = 0;

  // Send write packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 2);

  // Receive and verify response
  FCR_RETVAL = FCM_Prv_ReceiveResponse(100);

  // If successful, wait for EEPROM to be ready (2.5 seconds required)
  if (FCR_RETVAL)
  {  

    // Delay for EEPROM to be ready - ST3215 requires 2.5 seconds
    FCI_DELAYINT_MS(2500);

  // } else {

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Read current speed of servo. Returns speed in steps per second.
       :
       :Parameters for macro ReadSpeed:
       :  ServoID : Servo ID
       :
       :Returns : Speed in steps per second, or 0 if error
\*=----------------------------------------------------------------------=*/
MX_UINT16 FCM_ReadSpeed(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_UINT16 FCR_RETVAL; // Speed in steps per second, or 0 if error


  // Store register address
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_CURRENT_SPEED;
  FCV_PACKETBUFFER[1] = 2;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received
  if (FCV_RESPONSELENGTH >= 2)
  {  

    // Combine bytes to form speed
    FCR_RETVAL = FCV_RESPONSEBUFFER[2] + (FCV_RESPONSEBUFFER[3] << 8);

  } else {

    // Calculation
    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Read current in milliamps (6.5mA resolution). Returns current / 6.5.
       :
       :Parameters for macro ReadCurrent:
       :  ServoID : Servo ID
       :
       :Returns : Current / 6.5, or 0 if error
\*=----------------------------------------------------------------------=*/
MX_UINT16 FCM_ReadCurrent(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_UINT16 FCR_RETVAL; // Current / 6.5, or 0 if error


  // Store register address
  FCV_PACKETBUFFER[0] = 69;
  FCV_PACKETBUFFER[1] = 2;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received
  if (FCV_RESPONSELENGTH >= 2)
  {  

    // Combine bytes to form current
    FCR_RETVAL = FCV_RESPONSEBUFFER[2] + (FCV_RESPONSEBUFFER[3] << 8);

  } else {

    // Calculation
    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Change the servo baud rate. Baud rate values: 0=9600, 1=57600, 2=115200, 3=1000000. EEPROM must be unlocked.
       :
       :Parameters for macro ChangeBaudrate:
       :  ServoID : Servo ID
       :  Baudrate : Baud rate value: 0=9600, 1=57600, 2=115200, 3=1000000
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_ChangeBaudrate(MX_UINT8 FCL_SERVOID, MX_UINT8 FCL_BAUDRATE)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if successful


  // Store register address and baud rate value
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_BAUDRATE;
  FCV_PACKETBUFFER[1] = FCL_BAUDRATE;

  // Send write packet
  FCR_RETVAL = FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 2);

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Set position correction value in steps. Adds correction to position.
       :
       :Parameters for macro SetCorrection:
       :  ServoID : Servo ID
       :  Correction : Correction value in steps
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_SetCorrection(MX_UINT8 FCL_SERVOID, MX_SINT16 FCL_CORRECTION)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if successful


  // Store register address and correction bytes
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_CORRECTION;
  FCV_PACKETBUFFER[1] = FCL_CORRECTION;
  FCV_PACKETBUFFER[2] = FCL_CORRECTION >> 8;

  // Send write packet
  FCR_RETVAL = FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 3);

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Move servo to a target position. Position range: -30719 to 30719 steps.
       :
       :Parameters for macro MoveTo:
       :  ServoID : Servo ID
       :  Position : Target position in steps (0 to 4095)
       :
       :Returns : True if successful
\*=----------------------------------------------------------------------=*/
MX_BOOL FCM_MoveTo(MX_UINT8 FCL_SERVOID, MX_UINT16 FCL_POSITION)
{
  //Local variable definitions
  MX_BOOL FCR_RETVAL; // True if successful


  // Store register address and position bytes (low byte first, then high byte)
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_POSITION;
  FCV_PACKETBUFFER[1] = FCL_POSITION;
  FCV_PACKETBUFFER[2] = FCL_POSITION >> 8;

  // Send write packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_WRITE, 3);

  // Receive and verify response
  FCR_RETVAL = FCM_Prv_ReceiveResponse(100);

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCM_Uart_isr()
{
  //Local variable definitions
  MX_UINT8 FCL_RX = (0x0);


  // Call Component Macro
  FCL_RX = FC_CAL_UART_Receive_1(0);

  // Component Macro
  FCD_01211_CircularBuffer1__PutByte(FCL_RX);

}

/*=----------------------------------------------------------------------=*\
   Use :Calculate checksum for STS protocol packet. Checksum is NOT of sum of ID, Length, Instruction, and Parameters.
       :
       :Parameters for macro Prv_CalculateChecksum:
       :  PacketID : Servo ID
       :  Length : Packet length
       :  Instruction : Instruction byte
       :  ParamCount : Number of parameter bytes
       :
       :Returns : Calculated checksum value
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCM_Prv_CalculateChecksum(MX_UINT8 FCL_PACKETID, MX_UINT8 FCL_LENGTH, MX_UINT8 FCL_INSTRUCTION, MX_UINT8 FCL_PARAMCOUNT)
{
  //Local variable definitions
  MX_UINT16 FCL_SUM = (0x0); // Sum of bytes for checksum calculation
  MX_UINT8 FCL_IDX = (0x0); // Loop index
  MX_UINT8 FCR_RETVAL; // Calculated checksum value


  // Start with ID, Length, and Instruction
  FCL_SUM = FCL_PACKETID + FCL_LENGTH + FCL_INSTRUCTION;

  // Add all parameter bytes
  while (FCL_IDX < FCL_PARAMCOUNT)
  {
    // Add parameter byte to sum
    FCL_SUM = FCL_SUM + FCV_PACKETBUFFER[FCL_IDX];
    FCL_IDX = FCL_IDX + 1;

  }

  // Checksum is NOT of the sum
  FCR_RETVAL = ~FCL_SUM;

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCM_Initialise()
{

  // Component Macro
  FC_CAL_UART_Init_1();

}

/*=----------------------------------------------------------------------=*\
   Use :Read current acceleration value in steps per second squared.
       :
       :Parameters for macro ReadAcceleration:
       :  ServoID : Servo ID
       :
       :Returns : Acceleration value (0-254), or 0 if error
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCM_ReadAcceleration(MX_UINT8 FCL_SERVOID)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL; // Acceleration value (0-254), or 0 if error


  // Store register address
  FCV_PACKETBUFFER[0] = FCV_ST3215_ADDR_ACCEL;
  FCV_PACKETBUFFER[1] = 1;

  // Send read packet
  FCM_Prv_SendPacket(FCL_SERVOID, FCV_ST3215_CMD_READ, 2);

  // Receive response
  FCM_Prv_ReceiveResponse(100);

  // Check if response received
  if (FCV_RESPONSELENGTH >= 1)
  {  

    // Get acceleration value
    FCR_RETVAL = FCV_RESPONSEBUFFER[2];

  } else {

    // Calculation
    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

//Main macro for testing the ST3215 component


/*========================================================================*\
   Use :Main
\*========================================================================*/
void main()
{
	#ifdef INTOSCHELPER
		INTOSCHELPERCODE
	#endif
  //Local variable definitions
  MX_UINT8 FCL_TESTSERVOID = (0x1); // Test servo ID
  MX_BOOL FCL_PINGRESULT = (0); // Result of ping

ANSELA = 0x00;
ANSELB = 0x00;
ANSELD = 0x00;
ANSELE = 0x00;

OPTION_REG = 0xC0;


  // Initialize component
  FCM_Ev_Initialise();

  // Initialize UART
  FCM_Initialise();

  // Ping servo
  FCL_PINGRESULT = FCM_PingServo(FCL_TESTSERVOID);

	mainendloop: goto mainendloop;
}



/*========================================================================*\
   Use :Interrupt
\*========================================================================*/
void interrupt MX_INTERRUPT_MACRO(void)
{

  

  MX_UART_INT_CH1_FUNC

  MX_UINT8 FCL_RX;

  if (MX_UART_INT_CH1_DET)
  {

  // Call Component Macro
  FCL_RX = FC_CAL_UART_Receive_1(0);

  // Component Macro
  FCD_01211_CircularBuffer1__PutByte(FCL_RX);

  MX_UART_INT_CH1_CLR;

  }

  MX_UART_INT_FUNC_END
}




