//************************************************************************************
//**  
//**  Source name:   D:\Dev\Flowcode V11\Components\IO_Source\mechatronics\ST3215.fcfx
//**  Title:         
//**  Description:   
//**  Device:        PIC.16F.16F1937
//**  
//**  Generated by:  Flowcode v11.0.0.8
//**  Date:          Wednesday, February 18, 2026 13:37:41
//**  Users:         1
//**  Registered to: BenR (82702381)
//**  Licence key: 95CJQR
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#define MX_PIC

#define MX_CAL_PIC

#define MX_CLK_SPEED 19660800

#define FCP_NULL Unconnected_Port


#include <xc.h>
#include <math.h>
//Chip Configuration Settings
__PROG_CONFIG(0x1, 0xFE2);
__PROG_CONFIG(0x2, 0x1EFF);

/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\internals.c"



MX_UINT32 FCLV_LOOP1;
MX_UINT32 FCLV_LOOP2;

MX_UINT8 FCM_ReadTemperature(MX_UINT8 FCL_SERVOID);
MX_BOOL FCM_SetTorqueLimit(MX_UINT8 FCL_SERVOID, MX_UINT16 FCL_TORQUELIMIT);
MX_UINT8 FCM_ReadStatus(MX_UINT8 FCL_SERVOID);
MX_UINT32 FCM_Ev_AddInterrupts(MX_CHAR *FCL_HANDLERCODE, MX_UINT16 FCLsz_HANDLERCODE);
MX_BOOL FCM_SetAcceleration(MX_UINT8 FCL_SERVOID, MX_UINT8 FCL_ACCELERATION);
MX_BOOL FCM_ChangeID(MX_UINT8 FCL_SERVOID, MX_UINT8 FCL_NEWID);
MX_UINT32 FCM_Ev_Initialise();
MX_BOOL FCM_StartServo(MX_UINT8 FCL_SERVOID);
MX_UINT8 FCM_ListServos(MX_UINT8 *FCL_SERVOLIST, MX_UINT16 FCLsz_SERVOLIST, MX_UINT8 FCL_MAXCOUNT);
MX_SINT16 FCM_ReadPosition(MX_UINT8 FCL_SERVOID);
MX_BOOL FCM_IsMoving(MX_UINT8 FCL_SERVOID);
MX_UINT16 FCM_ReadTorqueLimit(MX_UINT8 FCL_SERVOID);
MX_BOOL FCM_StopServo(MX_UINT8 FCL_SERVOID);
MX_UINT8 FCM_ReadVoltage(MX_UINT8 FCL_SERVOID);
MX_BOOL FCM_Rotate(MX_UINT8 FCL_SERVOID, MX_UINT16 FCL_SPEED, MX_UINT8 FCL_DIRECTION);
MX_UINT32 FCM_Ev_Property();
MX_BOOL FCM_Prv_ReceiveResponse(MX_UINT16 FCL_TIMEOUT);
MX_UINT8 FCM_ReadMode(MX_UINT8 FCL_SERVOID);
MX_BOOL FCM_SetMode(MX_UINT8 FCL_SERVOID, MX_UINT8 FCL_MODE);
MX_BOOL FCM_SetSpeed(MX_UINT8 FCL_SERVOID, MX_UINT16 FCL_SPEED);
MX_BOOL FCM_MoveToAngle(MX_UINT8 FCL_SERVOID, MX_FLOAT FCL_ANGLE);
MX_BOOL FCM_LockEEPROM(MX_UINT8 FCL_SERVOID);
MX_SINT16 FCM_ReadCorrection(MX_UINT8 FCL_SERVOID);
MX_BOOL FCM_PingServo(MX_UINT8 FCL_SERVOID);
MX_UINT8 FCM_ReadID(MX_UINT8 FCL_SERVOID);
MX_BOOL FCM_Prv_SendPacket(MX_UINT8 FCL_SERVOID, MX_UINT8 FCL_INSTRUCTION, MX_UINT8 FCL_PARAMCOUNT);
MX_UINT8 FCM_ReadLoad(MX_UINT8 FCL_SERVOID);
MX_BOOL FCM_UnlockEEPROM(MX_UINT8 FCL_SERVOID);
MX_UINT16 FCM_ReadSpeed(MX_UINT8 FCL_SERVOID);
MX_UINT16 FCM_ReadCurrent(MX_UINT8 FCL_SERVOID);
MX_BOOL FCM_ChangeBaudrate(MX_UINT8 FCL_SERVOID, MX_UINT8 FCL_BAUDRATE);
MX_BOOL FCM_SetCorrection(MX_UINT8 FCL_SERVOID, MX_SINT16 FCL_CORRECTION);
MX_BOOL FCM_MoveTo(MX_UINT8 FCL_SERVOID, MX_UINT16 FCL_POSITION);
void FCM_Uart_isr();
MX_UINT8 FCM_Prv_CalculateChecksum(MX_UINT8 FCL_PACKETID, MX_UINT8 FCL_LENGTH, MX_UINT8 FCL_INSTRUCTION, MX_UINT8 FCL_PARAMCOUNT);
void FCM_Initialise();
MX_UINT8 FCM_ReadAcceleration(MX_UINT8 FCL_SERVOID);
MX_UINT8 FCD_01211_CircularBuffer1__LookForValue(MX_CHAR *FCL_VALUE, MX_UINT16 FCLsz_VALUE, MX_UINT8 FCL_NUMCHARS, MX_UINT8 FCL_REMOVECONTENT, MX_UINT8 FCL_RESETFIND);
void FCD_01211_CircularBuffer1__GetArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
void FCD_01211_CircularBuffer1__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL, MX_UINT16 FCL_MAXLENGTH);
void FCD_01211_CircularBuffer1__PutArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
MX_UINT8 FCD_01211_CircularBuffer1__GetIndexedByte(MX_UINT16 FCL_ADDRESS);
MX_UINT8 FCD_01211_CircularBuffer1__WaitForValue(MX_CHAR *FCL_VALUE, MX_UINT16 FCLsz_VALUE, MX_UINT8 FCL_NUMCHARS, MX_UINT8 FCL_REMOVECONTENT, MX_UINT16 FCL_TIMEOUT);
MX_UINT16 FCD_01211_CircularBuffer1__GetNumberBytes();
MX_UINT16 FCD_01211_CircularBuffer1__PeekByte();
void FCD_01211_CircularBuffer1__PutString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
MX_UINT8 FCD_01211_CircularBuffer1__PutByte(MX_UINT8 FCL_DATA);
MX_UINT16 FCD_01211_CircularBuffer1__GetByte();
MX_UINT16 FCD_01211_CircularBuffer1__GetSize(MX_BOOL FCL_MODE);
void FCD_01211_CircularBuffer1__FlushBuffer();

/*========================================================================*\
   Use :TypeConversionsFree1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :TypeConversionsFree1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifndef MX_UNIONTYPE
 #define MX_UNIONTYPE
 typedef union
{
  MX_FLOAT AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union_Type;
 MX_Union_Type MX_Conv_Var;
#endif


void FCD_02571_TypeConversionsFree1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE);
void FCD_02571_TypeConversionsFree1__SetLong(MX_UINT32 FCL_VALUE);
MX_FLOAT FCD_02571_TypeConversionsFree1__GetFloat();
MX_UINT32 FCD_02571_TypeConversionsFree1__GetLong();
MX_UINT16 FCD_02571_TypeConversionsFree1__GetInt(MX_UINT8 FCL_INDEX);
void FCD_02571_TypeConversionsFree1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE);
MX_UINT8 FCD_02571_TypeConversionsFree1__GetByte(MX_UINT8 FCL_INDEX);
void FCD_02571_TypeConversionsFree1__SetFloat(MX_FLOAT FCL_VALUE);

/*========================================================================*\
   Use :cal_uart
       :Macro function declarations
\*========================================================================*/
#define MX_UART_UseTX_1 (1)
#define MX_UART_TX_TRIS_1 trisc
#define MX_UART_REF1 
#define MX_UART_RTS_PIN_1 (4)
#define MX_UART_DBITS_1 (8)
#define MX_UART_RETURN_1 (1)
#define MX_UART_RX_PORT_1 portc
#define MX_UART_RTS_PORT_1 portc
#define MX_UART_ECHO_1 (0)
#define MX_UART_FLOWEN_1 (0)
#define MX_UART_CTS_PORT_1 portc
#define MX_UART_TX_PIN_1 (6)
#define MX_UART_RX_TRIS_1 trisc
#define MX_UART_BAUD_1 (115200)
#define MX_UART_RTS_TRIS_1 trisc
#define MX_UART_TX_PORT_1 portc
#define MX_UART_RX_PIN_1 (7)
#define MX_UART_UseRX_1 (1)
#define MX_UART_CTS_TRIS_1 trisc
#define MX_UART_CHANNEL_1 (1)
#define MX_UART_INT_1 (1)
#define MX_UART_CTS_PIN_1 (5)

MX_UINT8 FCD_05481_cal_uart__ControlPin(MX_UINT8 FCL_PIN, MX_UINT8 FCL_STATE);
void FCD_05481_cal_uart__SendString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
void FCD_05481_cal_uart__Prv_TextConsole(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT8 FCL_COLOUR);
void FC_CAL_UART_UpdateBaud_1(MX_UINT8 FCL_NEW_BAUD);
MX_UINT8 FCD_05481_cal_uart__TestProperty(MX_UINT8 FCL_PROPERTY);
void FCD_05481_cal_uart__SendNumber(MX_SINT32 FCL_NUMBER);
void FCD_05481_cal_uart__Prv_SimShowWaveform(MX_UINT8 FCL_TXRX, MX_UINT16 FCL_DATA);
MX_SINT16 FC_CAL_UART_Receive_1(MX_UINT8 FCL_TIMEOUT);
void FC_CAL_UART_Send_1(MX_UINT16 FCL_CHAR);
void FCD_05481_cal_uart__SendByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
void FC_CAL_UART_Init_1();
void FC_CAL_UART_Delay_1();
void FC_CAL_UART_Uninit_1();
MX_UINT8 FCD_05481_cal_uart__ReceiveByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT);
MX_UINT8 FCD_05481_cal_uart__ReceiveString(MX_CHAR *FCL_STRINGDATA, MX_UINT16 FCLsz_STRINGDATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT);

/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\includes.c"

