// CRC: AE5753800093D2B889297C6B876B6A21749C10AFA09C3FCE4A5F65B0FF76818FB25640F7F1F25483FD2044B839850E3ADD04A5F8AD9BEEB1823278EF8F2BA19C642ECC0A8F4400287286B72E06ADF20A1FBA30B1432743E9711B8143522C2B69A119B9C2331EF8A67CB3404AD5EC83F390CD37CE3EE355699E406D6FC46B74E81D1D9CC4D2DE3A279599941A01478C5C6CE785B5C2A7F1FE710AB028426827679EE5E31A7BF98C19A622B490CC31322055CB0F632B70ACDD549D34A0D5AD11F347DF40CC545296CB9D0F07E163331953FC7233E170E383106F5155CB06B551640B4EDED414B02673
// REVISION: 2.0
// GUID: 61576775-02B4-43EA-9811-436EAA6809A3
// DATE: 30\06\2023
// DIR: CAL\ARM\ARM_CAL_TypeDefs.c
/*********************************************************************
 *                  Flowcode CAL TypeDefs File
 *
 * File: ARM_CAL_TypeDefs.c
 *
 * (c) 2011 Matrix Multimedia Ltd.
 * http://www.matrixmultimedia.com
 *
 * Software License Agreement
 *
 * The software supplied herewith by Matrix Multimedia Ltd (the
 * “Company”) for its Flowcode graphical programming language is
 * intended and supplied to you, the Company’s customer, for use
 * solely and exclusively on the Company's products. The software
 * is owned by the Company, and is protected under applicable
 * copyright laws. All rights are reserved. Any use in violation
 * of the foregoing restrictions may subject the user to criminal
 * sanctions under applicable laws, as well as to civil liability
 * for the breach of the terms and conditions of this licence.
 *
 * THIS SOFTWARE IS PROVIDED IN AN “AS IS” CONDITION. NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED
 * TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. THE COMPANY SHALL NOT,
 * IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL OR
 * CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * Changelog:
 *
 *  date  | by | description
 * -------+----+-----------------------------------------------------
 * 060911 | BR | Created
 * 050312 | BR | Updated to v5.1 CAL Schema
 */

#include <stdbool.h>

// Preceeds all global variable definitions generated by Flowcode
#define MX_GLOBAL volatile

typedef bool           MX_BOOL;   // Or unsigned char, depending on platform
typedef signed char    MX_SINT8;
typedef signed short   MX_SINT16;
typedef signed long    MX_SINT32;
typedef unsigned char  MX_UINT8;
typedef unsigned short MX_UINT16;
typedef unsigned long  MX_UINT32;
typedef char           MX_CHAR;
typedef unsigned char* MX_STRING; // String pointer

//typedef double       MX_FLOAT;  // 64-bit Floating point (Real)
typedef float          MX_FLOAT;  // 32-bit Floating point (Real)

typedef MX_UINT16      MX_UINT;   // Best integer value for the platform, at least 8 bit
typedef MX_SINT16      MX_SINT;

#define MX_FSINGLE float

typedef union
{
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union32;

typedef union
{
  MX_UINT16 AsInt;
  MX_UINT8  AsByte[2];
} MX_Union16;




//Example Union Code
//MX_Union32 Test;
//Test.AsLong = 0xFFFFFFFF;
//Test.AsInt[0] = 0xFFFF;
//Test.AsByte[0] = 0xFF;
