//************************************************************************************
//**  
//**  Source name:   D:\Dev\Flowcode V11\Components\IO_Source\FormulaFlowcode2\FA_Source_P4.fcfx
//**  Title:         
//**  Description:   
//**  Device:        PIC16.33E.Formula Allcode
//**  
//**  Generated by:  Flowcode v11.0.2.15
//**  Date:          Monday, June 15, 2026 12:18:15
//**  Users:         1
//**  Registered to: BenR (82702381)
//**  Licence key: 95CJQR
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#define MX_PIC16

#define MX_CAL_PIC16

#define MX_CLK_SPEED 140000000

#define FCP_NULL Unconnected_Port


#include <xc.h>
#include <math.h>
#include <stdlib.h>
#include "p33Exxxx.h"

//Configuration Start
_FGS(65535);
_FOSCSEL(65531);
_FOSC(65466);
_FWDT(65407);
_FPOR(65535);
_FICD(65503);
_FAS(65535);
//Configuration End

/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\internals.c"



MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;
MX_UINT8 FCLV_LOOP3;
MX_UINT8 FCLV_LOOP4;
MX_UINT32 FCLV_LOOP5;
MX_UINT32 FCLV_LOOP6;
MX_UINT8 FCLV_LOOP7;
MX_UINT32 FCLV_LOOP8;
MX_UINT32 FCLV_LOOP9;
MX_UINT32 FCLV_LOOP10;
MX_UINT32 FCLV_LOOP11;
MX_UINT32 FCLV_LOOP12;
MX_UINT8 FCLV_LOOP13;
MX_UINT8 FCLV_LOOP14;
MX_UINT8 FCLV_LOOP15;
MX_UINT8 FCLV_LOOP16;
MX_UINT8 FCLV_LOOP17;
MX_UINT8 FCLV_LOOP18;

void FCM_PlayNote(MX_UINT16 FCL_NOTE, MX_UINT16 FCL_TIME);
MX_UINT8 FCM_CheckLine_Sim(MX_UINT8 FCL_SENSOR);
void FCM_InitialiseSim();
void FCM_LEDOn(MX_UINT8 FCL_LED);
void FCM_BluetoothTransmit(MX_UINT8 FCL_DATA);
MX_UINT32 FCM_Ev_Timer(MX_UINT32 FCL_TIMERID);
void FCM_LCDPrintString(MX_UINT8 FCL_X, MX_UINT8 FCL_Y, MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_TRANSPARENT);
MX_UINT8 FCM_CheckIR_Sim(MX_UINT8 FCL_SENSOR);
void FCM_PlayNote_Sim(MX_UINT16 FCL_NOTE, MX_UINT16 FCL_TIME);
MX_UINT32 FCM_Ev_Stop();
void FCM_LogoConfigure(MX_FLOAT FCL_DISTANCE, MX_FLOAT FCL_ANGLE);
void FCM_Forward_Sim(MX_UINT8 FCL_POWER);
void FCM_SpinLeft_Sim(MX_UINT8 FCL_POWER);
MX_UINT32 FCM_Ev_AddInterrupts(MX_CHAR *FCL_HANDLERCODE, MX_UINT16 FCLsz_HANDLERCODE);
void FCM_LogoCalibrateMotors();
void FCM_Stop();
MX_FLOAT FCM_ReadBattery();
void FCM_BattMon();
void FCM_LogoProcess2(MX_SINT16 FCL_LEFT, MX_SINT16 FCL_RIGHT, MX_UINT32 FCL_ENCTARGET);
void FCM_Prv_LoadMotorCal();
void FCM_LEDOff(MX_UINT8 FCL_LED);
void FCM_LCDPrintNumber(MX_UINT8 FCL_X, MX_UINT8 FCL_Y, MX_SINT16 FCL_NUMBER, MX_UINT8 FCL_TRANSPARENT);
MX_UINT32 FCM_Ev_Initialise();
void FCM_LEDWrite(MX_UINT8 FCL_LED_BYTE);
void FCM_Interrupt_MotorTimer();
MX_UINT8 FCM_BluetoothCheckConnection();
MX_UINT16 FCM_ReadMic();
MX_UINT16 FCM_AudioQueueLength();
void FCM_AudioAddToBuffer(MX_UINT16 FCL_DATA);
MX_UINT8 FCM_ReadSwitch(MX_UINT8 FCL_SWITCH);
MX_UINT8 FCM_CheckLine(MX_UINT8 FCL_SENSOR);
void FCM_AudioStreamControl(MX_UINT8 FCL_MODE, MX_UINT8 FCL_SAMPLERATE);
void FCM_LogoProcess(MX_SINT16 FCL_LEFT, MX_SINT16 FCL_RIGHT, MX_UINT32 FCL_ENCTARGET);
void FCM_SpinLeft(MX_UINT8 FCL_POWER);
void FCM_BluetoothCommand(MX_CHAR *FCL_COMMAND, MX_UINT16 FCLsz_COMMAND);
void FCM_LogoTurnLeft(MX_UINT16 FCL_ANGLE);
MX_UINT32 FCM_Ev_Pause();
void FCM_Forward(MX_UINT8 FCL_POWER);
void FCM_LCDWriteByte(MX_UINT8 FCL_DATA, MX_UINT8 FCL_X, MX_UINT8 FCL_Y);
MX_UINT8 FCM_BluetoothReceive();
void FCM_LCDDrawLine(MX_UINT8 FCL_X1, MX_UINT8 FCL_Y1, MX_UINT8 FCL_X2, MX_UINT8 FCL_Y2);
void FCM_Interrupt_Audio();
MX_UINT16 FCM_BluetoothQueueLength();
MX_UINT32 FCM_Ev_Property();
void FCM_Reverse_Sim(MX_UINT8 FCL_POWER);
void FCM_BluetoothTransmitString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
void FCM_LCDBacklight(MX_UINT8 FCL_BRIGHTNESS);
MX_UINT16 FCM_ReadLineSensor_Sim(MX_UINT8 FCL_CHANNEL);
MX_UINT16 FCM_AudioReadFromBuffer();
MX_UINT16 FCM_ReadLineSensor(MX_UINT8 FCL_CHANNEL);
MX_UINT16 FCM_ReadIRSensor_Sim(MX_UINT8 FCL_CHANNEL);
MX_BOOL FCM_Sim_Scan_Objects_In_Group(MX_UINT32 FCL_POSITION);
void FCM_LogoTurnRight(MX_UINT16 FCL_ANGLE);
MX_UINT8 FCM_CheckUSB_Sim();
void FCM_SpinRight(MX_UINT8 FCL_POWER);
MX_UINT8 FCM_CheckIR(MX_UINT8 FCL_SENSOR);
void FCM_Interrupt_Encoder();
void FCM_LCDPlotPixel(MX_UINT8 FCL_X, MX_UINT8 FCL_Y);
void FCM_SetMotorsInterrupt(MX_SINT16 FCL_LEFT, MX_SINT16 FCL_RIGHT);
void FCM_LCDSetBackgroundColour(MX_UINT8 FCL_COLOUR);
MX_UINT16 FCM_ReadLDR_Sim();
void FCM_Stop_Sim();
void FCM_LogoForwardsSim(MX_UINT16 FCL_DISTANCE);
MX_UINT16 FCM_ReadIRSensor(MX_UINT8 FCL_CHANNEL);
void FCM_SetMotors(MX_SINT16 FCL_LEFT, MX_SINT16 FCL_RIGHT);
void FCM_LogoBackwards(MX_UINT16 FCL_DISTANCE);
MX_BOOL FCM_BluetoothCheckRx(MX_CHAR *FCL_STRDATA, MX_UINT16 FCLsz_STRDATA);
MX_FLOAT FCM_GetEEFloat(MX_UINT8 FCL_ADDRESS);
void FCM_EncoderReset();
void FCM_Reverse(MX_UINT8 FCL_POWER);
void FCM_WaitForSwitch(MX_UINT8 FCL_SWITCH);
MX_UINT16 FCM_ReadLDR();
void FCM_LCDDrawRectangle(MX_UINT8 FCL_X1, MX_UINT8 FCL_Y1, MX_UINT8 FCL_X2, MX_UINT8 FCL_Y2, MX_UINT8 FCL_TRANSPARENT, MX_UINT8 FCL_SOLID);
void FCM_LogoTurnLeftSim(MX_UINT16 FCL_ANGLE);
void FCM_LogoBackwardsSim(MX_UINT16 FCL_DISTANCE);
MX_UINT16 FCM_EncoderReadCount(MX_UINT8 FCL_CHANNEL);
MX_UINT32 FCM_Ev_Start();
void FCM_LogoTurnRightSim(MX_UINT16 FCL_ANGLE);
void FCM_SetEEFloat(MX_UINT8 FCL_ADDRESS, MX_FLOAT FCL_VALUE);
MX_UINT8 FCM_CheckUSB();
void FCM_Interrupt_BluetoothRX();
void FCM_SpinRight_Sim(MX_UINT8 FCL_POWER);
MX_UINT32 FCM_Ev_Resume();
void FCM_LCDSetForegroundColour(MX_UINT8 FCL_COLOUR);
void FCM_Initialise();
MX_FLOAT FCM_ReadBattery_Sim();
void FCM_SetMotors_Sim(MX_SINT16 FCL_LEFT, MX_SINT16 FCL_RIGHT);
void FCM_LogoSetSpeed(MX_UINT8 FCL_SPEED);
void FCM_LogoForwards(MX_UINT16 FCL_DISTANCE);
void FCM_LCDClear();
void FCD_03d98_led_base1__TurnOn();
void FCD_03d98_led_base1__TurnOff();
void FCD_03d97_led_base1__TurnOn();
void FCD_03d97_led_base1__TurnOff();
void FCD_03d96_led_base1__TurnOn();
void FCD_03d96_led_base1__TurnOff();
void FCD_03d95_led_base1__TurnOn();
void FCD_03d95_led_base1__TurnOff();
void FCD_03d94_led_base1__TurnOn();
void FCD_03d94_led_base1__TurnOff();
void FCD_03d93_led_base1__TurnOn();
void FCD_03d93_led_base1__TurnOff();
void FCD_03d92_led_base1__TurnOn();
void FCD_03d92_led_base1__TurnOff();
void FCD_03d91_led_base1__TurnOn();
void FCD_03d91_led_base1__TurnOff();

/*========================================================================*\
   Use :LCD_Backlight
       :Macro function declarations
\*========================================================================*/
#define MX_PWM_PRESCALE6 (256)
#define MX_PWM_PIN_6 (0)
#define MX_PWM_TYPE_6 (0)
#define MX_PWM_PORT_6 PORTG
#define MX_PWM_TRIS_6 TRISG
#define MX_PWM_CHANNEL_6 (4)


/*=----------------------------------------------------------------------=*\
   Use :LCD_Backlight
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_PWM
#define MX_PWM_REF6

#define MX_PWM_FREQ_6  2707
#define MX_PWM_REMAPPABLE
#define MX_PWM_RPOR_6 RPOR12bits.RP112R
#define MX_PWM_RPOC_6 19
#define MX_PWM_OCxCON
#define MX_PWM_TMR_6 5

void FC_CAL_PWM_ChangePeriod_6(MX_UINT16 FCL_PERIOD, MX_UINT16 FCL_PRESCALER);
void FC_CAL_PWM_Disable_6();
void FC_CAL_PWM_SetDuty8Bit_6(MX_UINT8 FCL_DUTY);
void FC_CAL_PWM_Enable_6();
void FC_CAL_PWM_ChangeFrequency_6(MX_UINT32 FCL_FREQUENCY);
void FC_CAL_PWM_SetDuty10Bit_6(MX_UINT16 FCL_DUTY);
void FC_CAL_PWM_SetDutyFloat_6(MX_FLOAT FCL_DUTY);

/*========================================================================*\
   Use :PWM_RightMotorFW1
       :Macro function declarations
\*========================================================================*/
#define MX_PWM_PRESCALE5 (256)
#define MX_PWM_PIN_5 (2)
#define MX_PWM_TYPE_5 (0)
#define MX_PWM_PORT_5 PORTD
#define MX_PWM_TRIS_5 TRISD
#define MX_PWM_CHANNEL_5 (2)


/*=----------------------------------------------------------------------=*\
   Use :PWM_RightMotorFW1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_PWM
#define MX_PWM_REF5

#define MX_PWM_FREQ_5  2707
#define MX_PWM_REMAPPABLE
#define MX_PWM_RPOR_5 RPOR1bits.RP66R
#define MX_PWM_RPOC_5 17
#define MX_PWM_OCxCON
#define MX_PWM_TMR_5 5

void FC_CAL_PWM_ChangePeriod_5(MX_UINT16 FCL_PERIOD, MX_UINT16 FCL_PRESCALER);
void FC_CAL_PWM_Disable_5();
void FC_CAL_PWM_SetDuty8Bit_5(MX_UINT8 FCL_DUTY);
void FC_CAL_PWM_Enable_5();
void FC_CAL_PWM_ChangeFrequency_5(MX_UINT32 FCL_FREQUENCY);
void FC_CAL_PWM_SetDuty10Bit_5(MX_UINT16 FCL_DUTY);
void FC_CAL_PWM_SetDutyFloat_5(MX_FLOAT FCL_DUTY);

/*========================================================================*\
   Use :PWM_RightMotorBW1
       :Macro function declarations
\*========================================================================*/
#define MX_PWM_PRESCALE4 (256)
#define MX_PWM_PIN_4 (3)
#define MX_PWM_TYPE_4 (0)
#define MX_PWM_PORT_4 PORTD
#define MX_PWM_TRIS_4 TRISD
#define MX_PWM_CHANNEL_4 (6)


/*=----------------------------------------------------------------------=*\
   Use :PWM_RightMotorBW1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_PWM
#define MX_PWM_REF4

#define MX_PWM_FREQ_4  2707
#define MX_PWM_REMAPPABLE
#define MX_PWM_RPOR_4 RPOR1bits.RP67R
#define MX_PWM_RPOC_4 21
#define MX_PWM_OCxCON
#define MX_PWM_TMR_4 5

void FC_CAL_PWM_ChangePeriod_4(MX_UINT16 FCL_PERIOD, MX_UINT16 FCL_PRESCALER);
void FC_CAL_PWM_Disable_4();
void FC_CAL_PWM_SetDuty8Bit_4(MX_UINT8 FCL_DUTY);
void FC_CAL_PWM_Enable_4();
void FC_CAL_PWM_ChangeFrequency_4(MX_UINT32 FCL_FREQUENCY);
void FC_CAL_PWM_SetDuty10Bit_4(MX_UINT16 FCL_DUTY);
void FC_CAL_PWM_SetDutyFloat_4(MX_FLOAT FCL_DUTY);

/*========================================================================*\
   Use :PWM_LeftMotorFW1
       :Macro function declarations
\*========================================================================*/
#define MX_PWM_PRESCALE3 (256)
#define MX_PWM_PIN_3 (1)
#define MX_PWM_TYPE_3 (0)
#define MX_PWM_PORT_3 PORTD
#define MX_PWM_TRIS_3 TRISD
#define MX_PWM_CHANNEL_3 (1)


/*=----------------------------------------------------------------------=*\
   Use :PWM_LeftMotorFW1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_PWM
#define MX_PWM_REF3

#define MX_PWM_FREQ_3  2707
#define MX_PWM_REMAPPABLE
#define MX_PWM_RPOR_3 RPOR0bits.RP65R
#define MX_PWM_RPOC_3 16
#define MX_PWM_OCxCON
#define MX_PWM_TMR_3 5

void FC_CAL_PWM_ChangePeriod_3(MX_UINT16 FCL_PERIOD, MX_UINT16 FCL_PRESCALER);
void FC_CAL_PWM_Disable_3();
void FC_CAL_PWM_SetDuty8Bit_3(MX_UINT8 FCL_DUTY);
void FC_CAL_PWM_Enable_3();
void FC_CAL_PWM_ChangeFrequency_3(MX_UINT32 FCL_FREQUENCY);
void FC_CAL_PWM_SetDuty10Bit_3(MX_UINT16 FCL_DUTY);
void FC_CAL_PWM_SetDutyFloat_3(MX_FLOAT FCL_DUTY);

/*========================================================================*\
   Use :PWM_LeftMotorBW1
       :Macro function declarations
\*========================================================================*/
#define MX_PWM_PRESCALE2 (256)
#define MX_PWM_PIN_2 (0)
#define MX_PWM_TYPE_2 (0)
#define MX_PWM_PORT_2 PORTD
#define MX_PWM_TRIS_2 TRISD
#define MX_PWM_CHANNEL_2 (5)


/*=----------------------------------------------------------------------=*\
   Use :PWM_LeftMotorBW1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_PWM
#define MX_PWM_REF2

#define MX_PWM_FREQ_2  2707
#define MX_PWM_REMAPPABLE
#define MX_PWM_RPOR_2 RPOR0bits.RP64R
#define MX_PWM_RPOC_2 20
#define MX_PWM_OCxCON
#define MX_PWM_TMR_2 5

void FC_CAL_PWM_ChangePeriod_2(MX_UINT16 FCL_PERIOD, MX_UINT16 FCL_PRESCALER);
void FC_CAL_PWM_Disable_2();
void FC_CAL_PWM_SetDuty8Bit_2(MX_UINT8 FCL_DUTY);
void FC_CAL_PWM_Enable_2();
void FC_CAL_PWM_ChangeFrequency_2(MX_UINT32 FCL_FREQUENCY);
void FC_CAL_PWM_SetDuty10Bit_2(MX_UINT16 FCL_DUTY);
void FC_CAL_PWM_SetDutyFloat_2(MX_FLOAT FCL_DUTY);

/*========================================================================*\
   Use :PWM_AudioOut1
       :Macro function declarations
\*========================================================================*/
#define MX_PWM_PRESCALE1 (1)
#define MX_PWM_PIN_1 (3)
#define MX_PWM_TYPE_1 (0)
#define MX_PWM_PORT_1 PORTF
#define MX_PWM_TRIS_1 TRISF
#define MX_PWM_CHANNEL_1 (3)


/*=----------------------------------------------------------------------=*\
   Use :PWM_AudioOut1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_PWM
#define MX_PWM_REF1

#define MX_PWM_FREQ_1  34163
#define MX_PWM_REMAPPABLE
#define MX_PWM_RPOR_1 RPOR8bits.RP99R
#define MX_PWM_RPOC_1 18
#define MX_PWM_OCxCON
#define MX_PWM_TMR_1 4

void FC_CAL_PWM_ChangePeriod_1(MX_UINT16 FCL_PERIOD, MX_UINT16 FCL_PRESCALER);
void FC_CAL_PWM_Disable_1();
void FC_CAL_PWM_SetDuty8Bit_1(MX_UINT8 FCL_DUTY);
void FC_CAL_PWM_Enable_1();
void FC_CAL_PWM_ChangeFrequency_1(MX_UINT32 FCL_FREQUENCY);
void FC_CAL_PWM_SetDuty10Bit_1(MX_UINT16 FCL_DUTY);
void FC_CAL_PWM_SetDutyFloat_1(MX_FLOAT FCL_DUTY);
void FCD_092a1_AutoVersionID1__GetTime(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
void FCD_092a1_AutoVersionID1__GetDate(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT16 FCD_092a1_AutoVersionID1__GetBuildNumber();
MX_UINT8 FCD_05263_switch_base__ReadState();
void FCD_05263_switch_base__WaitUntilHigh();
void FCD_05263_switch_base__WaitUntilLow();
#define FCD_08833_USBSwitch__ReadState FCD_05263_switch_base__ReadState
#define FCD_08833_USBSwitch__WaitUntilHigh FCD_05263_switch_base__WaitUntilHigh
#define FCD_08833_USBSwitch__WaitUntilLow FCD_05263_switch_base__WaitUntilLow
MX_UINT8 FCD_02b22_CB_AUDIO__LookForValue(MX_CHAR *FCL_VALUE, MX_UINT16 FCLsz_VALUE, MX_UINT8 FCL_NUMCHARS, MX_UINT8 FCL_REMOVECONTENT, MX_UINT8 FCL_RESETFIND);
MX_UINT8 FCD_02b22_CB_AUDIO__GetIndexedByte(MX_UINT16 FCL_ADDRESS);
MX_UINT8 FCD_02b22_CB_AUDIO__WaitForValue(MX_CHAR *FCL_VALUE, MX_UINT16 FCLsz_VALUE, MX_UINT8 FCL_NUMCHARS, MX_UINT8 FCL_REMOVECONTENT, MX_UINT16 FCL_TIMEOUT);
MX_UINT16 FCD_02b22_CB_AUDIO__GetNumberBytes();
MX_UINT16 FCD_02b22_CB_AUDIO__PeekByte();
MX_UINT8 FCD_02b22_CB_AUDIO__PutByte(MX_UINT8 FCL_DATA);
MX_UINT16 FCD_02b22_CB_AUDIO__GetByte();
void FCD_02b22_CB_AUDIO__FlushBuffer();
MX_UINT8 FCD_02b21_CB_BT__LookForValue(MX_CHAR *FCL_VALUE, MX_UINT16 FCLsz_VALUE, MX_UINT8 FCL_NUMCHARS, MX_UINT8 FCL_REMOVECONTENT, MX_UINT8 FCL_RESETFIND);
MX_UINT8 FCD_02b21_CB_BT__GetIndexedByte(MX_UINT16 FCL_ADDRESS);
MX_UINT8 FCD_02b21_CB_BT__WaitForValue(MX_CHAR *FCL_VALUE, MX_UINT16 FCLsz_VALUE, MX_UINT8 FCL_NUMCHARS, MX_UINT8 FCL_REMOVECONTENT, MX_UINT16 FCL_TIMEOUT);
MX_UINT16 FCD_02b21_CB_BT__GetNumberBytes();
MX_UINT16 FCD_02b21_CB_BT__PeekByte();
MX_UINT8 FCD_02b21_CB_BT__PutByte(MX_UINT8 FCL_DATA);
MX_UINT16 FCD_02b21_CB_BT__GetByte();
void FCD_02b21_CB_BT__FlushBuffer();

/*========================================================================*\
   Use :TypeConversionsFree1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :TypeConversionsFree1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifndef MX_UNIONTYPE
 #define MX_UNIONTYPE
 typedef union
{
  MX_FLOAT AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union_Type;
 MX_Union_Type MX_Conv_Var;
#endif


void FCD_02571_TypeConversionsFree1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE);
void FCD_02571_TypeConversionsFree1__SetLong(MX_UINT32 FCL_VALUE);
MX_FLOAT FCD_02571_TypeConversionsFree1__GetFloat();
MX_UINT32 FCD_02571_TypeConversionsFree1__GetLong();
MX_UINT16 FCD_02571_TypeConversionsFree1__GetInt(MX_UINT8 FCL_INDEX);
void FCD_02571_TypeConversionsFree1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE);
MX_UINT8 FCD_02571_TypeConversionsFree1__GetByte(MX_UINT8 FCL_INDEX);
void FCD_02571_TypeConversionsFree1__SetFloat(MX_FLOAT FCL_VALUE);

/*========================================================================*\
   Use :cal_uart
       :Macro function declarations
\*========================================================================*/
#define MX_UART_UseTX_1 (1)
#define MX_UART_TX_TRIS_1 trisd
#define MX_UART_REF1 
#define MX_UART_RTS_PIN_1 (2)
#define MX_UART_DBITS_1 (8)
#define MX_UART_RETURN_1 (0)
#define MX_UART_RX_PORT_1 port
#define MX_UART_RTS_PORT_1 portb
#define MX_UART_ECHO_1 (0)
#define MX_UART_FLOWEN_1 (1)
#define MX_UART_CTS_PORT_1 portb
#define MX_UART_TX_PIN_1 (15)
#define MX_UART_RX_TRIS_1 tris
#define MX_UART_BAUD_1 (9600)
#define MX_UART_RTS_TRIS_1 trisb
#define MX_UART_TX_PORT_1 portd
#define MX_UART_RX_PIN_1 (0)
#define MX_UART_UseRX_1 (1)
#define MX_UART_CTS_TRIS_1 trisb
#define MX_UART_CHANNEL_1 (1)
#define MX_UART_INT_1 (0)
#define MX_UART_CTS_PIN_1 (1)


/*=----------------------------------------------------------------------=*\
   Use :cal_uart
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_UART_1_REMAPPABLE
#define MX_UART_1_TX_RPOR RPOR4bits.RP79R
#define MX_UART_1_TX_UTX 1
#define MX_UART_1_RX_RPINR RPINR18bits.U1RXR
#define MX_UART_1_RX_RP 13

MX_UINT8 FCD_05481_cal_uart__ControlPin(MX_UINT8 FCL_PIN, MX_UINT8 FCL_STATE);
void FCD_05481_cal_uart__SendString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
void FCD_05481_cal_uart__Prv_TextConsole(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT8 FCL_COLOUR);
void FC_CAL_UART_UpdateBaud_1(MX_UINT8 FCL_NEW_BAUD);
MX_UINT8 FCD_05481_cal_uart__TestProperty(MX_UINT8 FCL_PROPERTY);
void FCD_05481_cal_uart__SendNumber(MX_SINT32 FCL_NUMBER);
void FCD_05481_cal_uart__Prv_SimShowWaveform(MX_UINT8 FCL_TXRX, MX_UINT16 FCL_DATA);
MX_SINT16 FC_CAL_UART_Receive_1(MX_UINT8 FCL_TIMEOUT);
void FC_CAL_UART_Send_1(MX_UINT16 FCL_CHAR);
void FCD_05481_cal_uart__SendByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
void FC_CAL_UART_Init_1();
void FC_CAL_UART_Delay_1();
void FC_CAL_UART_Uninit_1();
MX_UINT8 FCD_05481_cal_uart__ReceiveByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT);
MX_UINT8 FCD_05481_cal_uart__ReceiveString(MX_CHAR *FCL_STRINGDATA, MX_UINT16 FCLsz_STRINGDATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT);
void FCD_06b71_BlueTooth__SendString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
void FCD_06b71_BlueTooth__SendNumber(MX_SINT32 FCL_NUMBER);
void FCD_06b71_BlueTooth__SendChar(MX_SINT16 FCL_CHAR);
void FCD_06b71_BlueTooth__ChangeHWBaud(MX_UINT8 FCL_NEWBAUD);
void FCD_06b71_BlueTooth__ReceiveString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL, MX_UINT8 FCL_TIMEOUT, MX_UINT16 FCL_NUMBYTES);
void FCD_06b71_BlueTooth__Initialise();
MX_SINT16 FCD_06b71_BlueTooth__ReceiveChar(MX_SINT16 FCL_TIMEOUT);

/*========================================================================*\
   Use :flashio1
       :Macro function declarations
\*========================================================================*/
#define FCV_PRVTFLASHBUFFER FCV_0f151_flashio1__PRVTFLASHBUFFER


/*=----------------------------------------------------------------------=*\
   Use :flashio1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#include "../support/generic/h/libpic30.h"
void FCD_0f151_flashio1__ClearPage(MX_UINT8 FCL_PAGENUMBER);
MX_UINT32 FCD_0f151_flashio1__ReadCell(MX_UINT8 FCL_PAGE, MX_UINT8 FCL_CELL);
void FCD_0f151_flashio1__WriteCell(MX_UINT8 FCL_PAGE, MX_UINT8 FCL_CELL, MX_UINT8 FCL_ADDRESS, MX_UINT16 FCL_VALUE);
void FCD_0ee91_flasheeprom1__Clear(MX_UINT8 FCL_PAGE);
MX_UINT16 FCD_0ee91_flasheeprom1__Read(MX_UINT8 FCL_ADDRESS);
void FCD_0ee91_flasheeprom1__ClearAll();
MX_UINT8 FCD_0ee91_flasheeprom1__Write(MX_UINT8 FCL_ADDRESS, MX_UINT16 FCL_VALUE);
void FCD_0ee91_flasheeprom1__ConsolidatePage();
MX_UINT8 FCD_0ee91_flasheeprom1__Initialise();

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_21 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_13 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_13 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_13 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_13();
void FC_ADC_Enable_13(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_13(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f4d_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f4d_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f4d_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f4d_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f4d_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f4d_adc_base__GetVoltage();
MX_UINT16 FCD_08f4d_adc_base__GetInt();
MX_UINT8 FCD_08f4d_adc_base__GetByte();
#define FCD_0352d_Battery__GetString FCD_08f4d_adc_base__GetString
#define FCD_0352d_Battery__GetAverageByte FCD_08f4d_adc_base__GetAverageByte
#define FCD_0352d_Battery__GetAverageInt FCD_08f4d_adc_base__GetAverageInt
#define FCD_0352d_Battery__GetVoltage FCD_08f4d_adc_base__GetVoltage
#define FCD_0352d_Battery__GetInt FCD_08f4d_adc_base__GetInt
#define FCD_0352d_Battery__GetByte FCD_08f4d_adc_base__GetByte

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_3 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_12 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_12 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_12 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_12();
void FC_ADC_Enable_12(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_12(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f4c_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f4c_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f4c_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f4c_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f4c_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f4c_adc_base__GetVoltage();
MX_UINT16 FCD_08f4c_adc_base__GetInt();
MX_UINT8 FCD_08f4c_adc_base__GetByte();
#define FCD_0352c_MIC__GetString FCD_08f4c_adc_base__GetString
#define FCD_0352c_MIC__GetAverageByte FCD_08f4c_adc_base__GetAverageByte
#define FCD_0352c_MIC__GetAverageInt FCD_08f4c_adc_base__GetAverageInt
#define FCD_0352c_MIC__GetVoltage FCD_08f4c_adc_base__GetVoltage
#define FCD_0352c_MIC__GetInt FCD_08f4c_adc_base__GetInt
#define FCD_0352c_MIC__GetByte FCD_08f4c_adc_base__GetByte

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_20 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_11 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_11 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_11 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_11();
void FC_ADC_Enable_11(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_11(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f4b_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f4b_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f4b_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f4b_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f4b_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f4b_adc_base__GetVoltage();
MX_UINT16 FCD_08f4b_adc_base__GetInt();
MX_UINT8 FCD_08f4b_adc_base__GetByte();
#define FCD_0352b_IR7__GetString FCD_08f4b_adc_base__GetString
#define FCD_0352b_IR7__GetAverageByte FCD_08f4b_adc_base__GetAverageByte
#define FCD_0352b_IR7__GetAverageInt FCD_08f4b_adc_base__GetAverageInt
#define FCD_0352b_IR7__GetVoltage FCD_08f4b_adc_base__GetVoltage
#define FCD_0352b_IR7__GetInt FCD_08f4b_adc_base__GetInt
#define FCD_0352b_IR7__GetByte FCD_08f4b_adc_base__GetByte

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_10 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_10 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_10 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_10 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_10();
void FC_ADC_Enable_10(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_10(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f4a_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f4a_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f4a_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f4a_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f4a_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f4a_adc_base__GetVoltage();
MX_UINT16 FCD_08f4a_adc_base__GetInt();
MX_UINT8 FCD_08f4a_adc_base__GetByte();
#define FCD_0352a_IR6__GetString FCD_08f4a_adc_base__GetString
#define FCD_0352a_IR6__GetAverageByte FCD_08f4a_adc_base__GetAverageByte
#define FCD_0352a_IR6__GetAverageInt FCD_08f4a_adc_base__GetAverageInt
#define FCD_0352a_IR6__GetVoltage FCD_08f4a_adc_base__GetVoltage
#define FCD_0352a_IR6__GetInt FCD_08f4a_adc_base__GetInt
#define FCD_0352a_IR6__GetByte FCD_08f4a_adc_base__GetByte

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_9 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_9 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_9 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_9 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_9();
void FC_ADC_Enable_9(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_9(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f49_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f49_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f49_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f49_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f49_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f49_adc_base__GetVoltage();
MX_UINT16 FCD_08f49_adc_base__GetInt();
MX_UINT8 FCD_08f49_adc_base__GetByte();
#define FCD_03529_IR5__GetString FCD_08f49_adc_base__GetString
#define FCD_03529_IR5__GetAverageByte FCD_08f49_adc_base__GetAverageByte
#define FCD_03529_IR5__GetAverageInt FCD_08f49_adc_base__GetAverageInt
#define FCD_03529_IR5__GetVoltage FCD_08f49_adc_base__GetVoltage
#define FCD_03529_IR5__GetInt FCD_08f49_adc_base__GetInt
#define FCD_03529_IR5__GetByte FCD_08f49_adc_base__GetByte

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_8 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_8 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_8 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_8 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_8();
void FC_ADC_Enable_8(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_8(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f48_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f48_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f48_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f48_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f48_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f48_adc_base__GetVoltage();
MX_UINT16 FCD_08f48_adc_base__GetInt();
MX_UINT8 FCD_08f48_adc_base__GetByte();
#define FCD_03528_IR4__GetString FCD_08f48_adc_base__GetString
#define FCD_03528_IR4__GetAverageByte FCD_08f48_adc_base__GetAverageByte
#define FCD_03528_IR4__GetAverageInt FCD_08f48_adc_base__GetAverageInt
#define FCD_03528_IR4__GetVoltage FCD_08f48_adc_base__GetVoltage
#define FCD_03528_IR4__GetInt FCD_08f48_adc_base__GetInt
#define FCD_03528_IR4__GetByte FCD_08f48_adc_base__GetByte

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_15 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_7 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_7 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_7 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_7();
void FC_ADC_Enable_7(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_7(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f47_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f47_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f47_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f47_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f47_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f47_adc_base__GetVoltage();
MX_UINT16 FCD_08f47_adc_base__GetInt();
MX_UINT8 FCD_08f47_adc_base__GetByte();
#define FCD_03527_IR3__GetString FCD_08f47_adc_base__GetString
#define FCD_03527_IR3__GetAverageByte FCD_08f47_adc_base__GetAverageByte
#define FCD_03527_IR3__GetAverageInt FCD_08f47_adc_base__GetAverageInt
#define FCD_03527_IR3__GetVoltage FCD_08f47_adc_base__GetVoltage
#define FCD_03527_IR3__GetInt FCD_08f47_adc_base__GetInt
#define FCD_03527_IR3__GetByte FCD_08f47_adc_base__GetByte

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_14 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_6 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_6 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_6 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_6();
void FC_ADC_Enable_6(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_6(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f46_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f46_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f46_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f46_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f46_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f46_adc_base__GetVoltage();
MX_UINT16 FCD_08f46_adc_base__GetInt();
MX_UINT8 FCD_08f46_adc_base__GetByte();
#define FCD_03526_IR2__GetString FCD_08f46_adc_base__GetString
#define FCD_03526_IR2__GetAverageByte FCD_08f46_adc_base__GetAverageByte
#define FCD_03526_IR2__GetAverageInt FCD_08f46_adc_base__GetAverageInt
#define FCD_03526_IR2__GetVoltage FCD_08f46_adc_base__GetVoltage
#define FCD_03526_IR2__GetInt FCD_08f46_adc_base__GetInt
#define FCD_03526_IR2__GetByte FCD_08f46_adc_base__GetByte

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_5 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_5 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_5 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_5 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_5();
void FC_ADC_Enable_5(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_5(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f45_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f45_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f45_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f45_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f45_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f45_adc_base__GetVoltage();
MX_UINT16 FCD_08f45_adc_base__GetInt();
MX_UINT8 FCD_08f45_adc_base__GetByte();
#define FCD_03525_IR1__GetString FCD_08f45_adc_base__GetString
#define FCD_03525_IR1__GetAverageByte FCD_08f45_adc_base__GetAverageByte
#define FCD_03525_IR1__GetAverageInt FCD_08f45_adc_base__GetAverageInt
#define FCD_03525_IR1__GetVoltage FCD_08f45_adc_base__GetVoltage
#define FCD_03525_IR1__GetInt FCD_08f45_adc_base__GetInt
#define FCD_03525_IR1__GetByte FCD_08f45_adc_base__GetByte

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_1 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_4 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_4 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_4 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_4();
void FC_ADC_Enable_4(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_4(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f44_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f44_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f44_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f44_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f44_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f44_adc_base__GetVoltage();
MX_UINT16 FCD_08f44_adc_base__GetInt();
MX_UINT8 FCD_08f44_adc_base__GetByte();
#define FCD_03524_LF2__GetString FCD_08f44_adc_base__GetString
#define FCD_03524_LF2__GetAverageByte FCD_08f44_adc_base__GetAverageByte
#define FCD_03524_LF2__GetAverageInt FCD_08f44_adc_base__GetAverageInt
#define FCD_03524_LF2__GetVoltage FCD_08f44_adc_base__GetVoltage
#define FCD_03524_LF2__GetInt FCD_08f44_adc_base__GetInt
#define FCD_03524_LF2__GetByte FCD_08f44_adc_base__GetByte

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_0 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_3 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_3 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_3 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_3();
void FC_ADC_Enable_3(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_3(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f43_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f43_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f43_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f43_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f43_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f43_adc_base__GetVoltage();
MX_UINT16 FCD_08f43_adc_base__GetInt();
MX_UINT8 FCD_08f43_adc_base__GetByte();
#define FCD_03523_LF1__GetString FCD_08f43_adc_base__GetString
#define FCD_03523_LF1__GetAverageByte FCD_08f43_adc_base__GetAverageByte
#define FCD_03523_LF1__GetAverageInt FCD_08f43_adc_base__GetAverageInt
#define FCD_03523_LF1__GetVoltage FCD_08f43_adc_base__GetVoltage
#define FCD_03523_LF1__GetInt FCD_08f43_adc_base__GetInt
#define FCD_03523_LF1__GetByte FCD_08f43_adc_base__GetByte

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_2 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_2 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_2 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_2 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_2();
void FC_ADC_Enable_2(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_2(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f42_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f42_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f42_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f42_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f42_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f42_adc_base__GetVoltage();
MX_UINT16 FCD_08f42_adc_base__GetInt();
MX_UINT8 FCD_08f42_adc_base__GetByte();
#define FCD_03522_LDR__GetString FCD_08f42_adc_base__GetString
#define FCD_03522_LDR__GetAverageByte FCD_08f42_adc_base__GetAverageByte
#define FCD_03522_LDR__GetAverageInt FCD_08f42_adc_base__GetAverageInt
#define FCD_03522_LDR__GetVoltage FCD_08f42_adc_base__GetVoltage
#define FCD_03522_LDR__GetInt FCD_08f42_adc_base__GetInt
#define FCD_03522_LDR__GetByte FCD_08f42_adc_base__GetByte

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_10 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_4 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_1 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_1 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_1 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_1();
void FC_ADC_Enable_1(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_1(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT8 FCD_08f41_adc_base__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_08f41_adc_base__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_08f41_adc_base__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_08f41_adc_base__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_08f41_adc_base__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_08f41_adc_base__GetVoltage();
MX_UINT16 FCD_08f41_adc_base__GetInt();
MX_UINT8 FCD_08f41_adc_base__GetByte();
#define FCD_03521_IR0__GetString FCD_08f41_adc_base__GetString
#define FCD_03521_IR0__GetAverageByte FCD_08f41_adc_base__GetAverageByte
#define FCD_03521_IR0__GetAverageInt FCD_08f41_adc_base__GetAverageInt
#define FCD_03521_IR0__GetVoltage FCD_08f41_adc_base__GetVoltage
#define FCD_03521_IR0__GetInt FCD_08f41_adc_base__GetInt
#define FCD_03521_IR0__GetByte FCD_08f41_adc_base__GetByte
MX_UINT16 FCD_00fb2_WidthData__GetLUTCount();
MX_UINT16 FCD_00fb1_ASCIIData__GetLUTCount();
MX_UINT32 FCD_09e51_gLCD_Font1__SumWidths(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_09e51_gLCD_Font1__ReadWidth(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_09e51_gLCD_Font1__ReadFontStat(MX_UINT8 FCL_INDEX);
MX_UINT8 FCD_09e51_gLCD_Font1__ReadASCIILUT(MX_UINT8 FCL_CHARACTER, MX_UINT16 FCL_BYTEINDEX);

/*========================================================================*\
   Use :Base_GLCD
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Base_GLCD
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define ReadFontWidth(FONT, CHAR) FCD_0ba71_Base_GLCD__ReadFontWidth(FONT, CHAR)
#define ReadFontStat(FONT, IDX) FCD_0ba71_Base_GLCD__ReadFontStat(FONT, IDX)


MX_UINT32 FCD_0ba71_Base_GLCD__Prv_SumWidths(MX_UINT8 FCL_CHARACTER);
MX_UINT8 FCD_0ba71_Base_GLCD__ReadFontWidth(MX_UINT8 FCL_FONT, MX_UINT8 FCL_CHARACTER);
void FCD_0ba71_Base_GLCD__Prv_ReadFontFileHeader(MX_UINT8 FCL_FONT);
MX_UINT8 FCD_0ba71_Base_GLCD__ReadFontStat(MX_UINT8 FCL_FONT, MX_UINT8 FCL_INDEX);
void FCD_0ba71_Base_GLCD__SetExternalFont(MX_UINT8 FCL_FONT, MX_CHAR *PFCL_FILENAME, MX_UINT8 FCL_CHARACTERSPACING, MX_UINT8 FCL_SPACEWIDTH);
MX_UINT8 FCD_0ba71_Base_GLCD__ReadFontByte(MX_UINT8 FCL_FONT, MX_UINT8 FCL_CHARACTER, MX_UINT16 FCL_BYTEINDEX);
void FCD_0ab21_gLCD_ST7567_SPI1__SetFontScaler(MX_UINT8 FCL_SCALEX, MX_UINT8 FCL_SCALEY);
void FCD_0ab21_gLCD_ST7567_SPI1__PrintNumber(MX_SINT16 FCL_NUMBER, MX_UINT16 FCL_X, MX_UINT16 FCL_LINE, MX_UINT8 FCL_FONT, MX_UINT8 FCL_TRANSPARENT);
void FCD_0ab21_gLCD_ST7567_SPI1__DrawLine(MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT16 FCL_X2, MX_UINT16 FCL_Y2);
void FCD_0ab21_gLCD_ST7567_SPI1__Write_Data(MX_UINT8 FCL_DATA);
void FCD_0ab21_gLCD_ST7567_SPI1__DrawEllipse(MX_UINT16 FCL_X, MX_UINT16 FCL_Y, MX_UINT16 FCL_XRADIUS, MX_UINT16 FCL_YRADIUS, MX_UINT8 FCL_TRANSPARENT, MX_UINT8 FCL_SOLID);
void FCD_0ab21_gLCD_ST7567_SPI1__Goto_XY(MX_UINT8 FCL_X, MX_UINT8 FCL_Y);
void FCD_0ab21_gLCD_ST7567_SPI1__Plot(MX_UINT8 FCL_X, MX_UINT8 FCL_Y);
void FCD_0ab21_gLCD_ST7567_SPI1__DrawArc(MX_UINT16 FCL_X, MX_UINT16 FCL_Y, MX_UINT16 FCL_RADIUS, MX_FLOAT FCL_STARTANGLE, MX_FLOAT FCL_ENDANGLE, MX_UINT16 FCL_RESOLUTION, MX_UINT8 FCL_TRANSPARENT, MX_UINT8 FCL_SOLID);
void FCD_0ab21_gLCD_ST7567_SPI1__SetDisplayOrientation(MX_UINT8 FCL_ORIENTATION);
void FCD_0ab21_gLCD_ST7567_SPI1__BPlot(MX_UINT8 FCL_X, MX_UINT8 FCL_Y);
void FCD_0ab21_gLCD_ST7567_SPI1__Print(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT8 FCL_FONT, MX_UINT8 FCL_TRANSPARENT);
void FCD_0ab21_gLCD_ST7567_SPI1__ClearDisplay();
void FCD_0ab21_gLCD_ST7567_SPI1__SetBackgroundColour(MX_UINT8 FCL_PIXELCOLOUR);
void FCD_0ab21_gLCD_ST7567_SPI1__DrawCircle(MX_UINT16 FCL_X, MX_UINT16 FCL_Y, MX_UINT16 FCL_RADIUS, MX_UINT8 FCL_TRANSPARENT, MX_UINT8 FCL_SOLID);
void FCD_0ab21_gLCD_ST7567_SPI1__Write_Command(MX_UINT8 FCL_COMMAND);
void FCD_0ab21_gLCD_ST7567_SPI1__DrawRoundedRectangle(MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT16 FCL_X2, MX_UINT16 FCL_Y2, MX_UINT16 FCL_RADIUS, MX_UINT8 FCL_TRANSPARENT, MX_UINT8 FCL_SOLID);
void FCD_0ab21_gLCD_ST7567_SPI1__SetForegroundColour(MX_UINT8 FCL_PIXELCOLOUR);
void FCD_0ab21_gLCD_ST7567_SPI1__DrawRectangle(MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT16 FCL_X2, MX_UINT16 FCL_Y2, MX_UINT8 FCL_TRANSPARENT, MX_UINT8 FCL_SOLID);
void FCD_0ab21_gLCD_ST7567_SPI1__Initialise();
MX_UINT8 FCD_05262_switch_base__ReadState();
void FCD_05262_switch_base__WaitUntilHigh();
void FCD_05262_switch_base__WaitUntilLow();
MX_UINT8 FCD_05261_switch_base__ReadState();
void FCD_05261_switch_base__WaitUntilHigh();
void FCD_05261_switch_base__WaitUntilLow();

/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\includes.c"

