// CRC: 20C35A1E87BE6D5C727502197CD041A7B491451D5915BA6B046B33DA966607B8B25640F7F1F25483FD2044B839850E3ADD04A5F8AD9BEEB1823278EF8F2BA19C642ECC0A8F4400287286B72E06ADF20A1FBA30B1432743E9711B8143522C2B696590AC0D07939900B7E5DE4E31DA737AEBEC2E9F5593733437F11C1FAFEC1ED63E323F177853F24B0442648C3F0A69928AAD90D5F4B22608576EF27B7C061B3A0F8987A417CB5EEC1E3B7A2820F807B1F37A7309679571A6549D34A0D5AD11F37C72CD24C163EBE812219A5B2E9ADA5073448447E28A8C37A8B2FE2536E6C50FEBD31FED13C8BAD2
// REVISION: 2.0
// GUID: 52AFF5B2-5ADA-4E48-902B-EA48B7D728C1
// DATE: 30\06\2023
// DIR: CAL\PIC\PIC_CAL_TypeDefs.c
/*********************************************************************
 *                  Flowcode CAL TypeDefs File
 *
 * File: PIC_CAL_TypeDefs.c
 *
 * (c) 2011 Matrix Multimedia Ltd.
 * http://www.matrixmultimedia.com
 *
 * Software License Agreement
 *
 * The software supplied herewith by Matrix Multimedia Ltd (the
 * “Company”) for its Flowcode graphical programming language is
 * intended and supplied to you, the Company’s customer, for use
 * solely and exclusively on the Company's products. The software
 * is owned by the Company, and is protected under applicable
 * copyright laws. All rights are reserved. Any use in violation
 * of the foregoing restrictions may subject the user to criminal
 * sanctions under applicable laws, as well as to civil liability
 * for the breach of the terms and conditions of this licence.
 *
 * THIS SOFTWARE IS PROVIDED IN AN “AS IS” CONDITION. NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED
 * TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. THE COMPANY SHALL NOT,
 * IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL OR
 * CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * Changelog:
 *
 *  date  | by | description
 * -------+----+-----------------------------------------------------
 * 010911 | BR | Created
 * 160412 | BR | Incompatible types problem sorted by changing char* to unsigned char*
 *
 *
 */

// Preceeds all global variable definitions generated by Flowcode
#define MX_GLOBAL volatile

typedef signed char    	MX_SINT8;
typedef signed short   	MX_SINT16;
typedef signed long    	MX_SINT32;
typedef unsigned char  	MX_UINT8;
typedef unsigned short 	MX_UINT16;
typedef unsigned long  	MX_UINT32;
typedef char       		MX_CHAR;
typedef MX_UINT16      	MX_UINT;   // Best integer value for the platform, at least 8 bit
typedef MX_SINT16      	MX_SINT;

#define MX_STRING 		unsigned char*		// String pointer

//typedef bit     		MX_BOOL;   // Or unsigned MX_UINT8, depending on platform - Causes compile issues on XC8 if bool variable used as a function parameter
typedef MX_UINT8    	MX_BOOL;   // Or unsigned MX_UINT8, depending on platform

//typedef double       	MX_FLOAT;  // 64-bit Floating point (Real)
typedef float          	MX_FLOAT;  // 32-bit Floating point (Real)

#define MX_FSINGLE float


typedef union
{
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union32;

typedef union
{
  MX_UINT16 AsInt;
  MX_UINT8  AsByte[2];
} MX_Union16;




//Example Union Code
//MX_Union32 Test;
//Test.AsLong = 0xFFFFFFFF;
//Test.AsInt[0] = 0xFFFF;
//Test.AsByte[0] = 0xFF;

