//************************************************************************************
//**  
//**  Source name:   D:\Dev\Flowcode V11\Components\IO_Source\outputs\LED_WS2811.fcfx
//**  Title:         
//**  Description:   
//**  Device:        PIC.16F.16F1937
//**  
//**  Generated by:  Flowcode v11.0.0.8
//**  Date:          Friday, January 16, 2026 10:41:23
//**  Users:         1
//**  Registered to: BenR (82702381)
//**  Licence key: 95CJQR
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#define MX_PIC

#define MX_CAL_PIC

#define MX_CLK_SPEED 19660800

#define FCP_NULL Unconnected_Port


#include <xc.h>
#include <math.h>
//Chip Configuration Settings
__PROG_CONFIG(0x1, 0xCFE2);
__PROG_CONFIG(0x2, 0xDEFF);

/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\internals.c"



MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;
MX_UINT8 FCLV_LOOP3;
MX_UINT8 FCLV_LOOP4;
MX_UINT8 FCLV_LOOP5;
MX_UINT8 FCLV_LOOP6;
MX_UINT8 FCLV_LOOP7;
MX_UINT8 FCLV_LOOP8;
MX_UINT8 FCLV_LOOP9;
MX_UINT8 FCLV_LOOP10;
MX_UINT8 FCLV_LOOP11;
MX_UINT8 FCLV_LOOP12;
MX_UINT8 FCLV_LOOP13;
MX_UINT8 FCLV_LOOP14;

void FCM_SetBrightness(MX_FLOAT FCL_SCALER);
MX_UINT32 FCM_Ev_Initialise();
MX_UINT8 FCM_GetLEDColour(MX_UINT16 FCL_LED, MX_UINT8 FCL_COLIDX);
MX_UINT32 FCM_Ev_Property();
void FCM_SetBrightnessByte(MX_UINT8 FCL_SCALER);
void FCM_DrawLine2D(MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT16 FCL_X2, MX_UINT16 FCL_Y2, MX_UINT8 FCL_R, MX_UINT8 FCL_G, MX_UINT8 FCL_B);
void FCM_SetLEDColour(MX_UINT16 FCL_LED, MX_UINT8 FCL_R, MX_UINT8 FCL_G, MX_UINT8 FCL_B);
void FCM_SetAllLEDColour(MX_UINT8 FCL_R, MX_UINT8 FCL_G, MX_UINT8 FCL_B);
MX_UINT32 FCM_Ev_AddVar(MX_CHAR *PFCL_VARNAME, MX_CHAR *PFCL_EXPANDNAME, MX_CHAR *FCL_EXPANSION, MX_UINT16 FCLsz_EXPANSION);
void FCM_Refresh();
void FCM_ShiftLEDs1D(MX_UINT8 FCL_DIRECTION, MX_UINT8 FCL_DATAMODE);
void FCM_DrawLine3D(MX_UINT16 FCL_X1, MX_UINT16 FCL_Y1, MX_UINT16 FCL_Z1, MX_UINT16 FCL_X2, MX_UINT16 FCL_Y2, MX_UINT16 FCL_Z2, MX_UINT8 FCL_R, MX_UINT8 FCL_G, MX_UINT8 FCL_B);
MX_UINT16 FCM_GetLEDIndex2D(MX_UINT16 FCL_X, MX_UINT16 FCL_Y);
void FCM_DrawRectangle2D(MX_UINT8 FCL_X1, MX_UINT8 FCL_Y1, MX_UINT8 FCL_X2, MX_UINT8 FCL_Y2, MX_UINT8 FCL_DRAWSTYLE, MX_UINT8 FCL_R, MX_UINT8 FCL_G, MX_UINT8 FCL_B);
MX_UINT32 FCM_Ev_AddHeader(MX_CHAR *FCL_HEADCODE, MX_UINT16 FCLsz_HEADCODE);
void FCM_ShiftLEDs2D(MX_SINT16 FCL_X, MX_SINT16 FCL_Y, MX_UINT8 FCL_DATAMODE);
MX_UINT16 FCM_GetLEDIndex3D(MX_UINT16 FCL_X, MX_UINT16 FCL_Y, MX_UINT16 FCL_Z);
void FCM_RefreshSim();
void FCM_DrawCuboid3D(MX_UINT8 FCL_X1, MX_UINT8 FCL_Y1, MX_UINT8 FCL_Z1, MX_UINT8 FCL_X2, MX_UINT8 FCL_Y2, MX_UINT8 FCL_Z2, MX_UINT8 FCL_DRAWSTYLE, MX_UINT8 FCL_R, MX_UINT8 FCL_G, MX_UINT8 FCL_B);
void FCM_Initialise();
void FCM_ShiftLEDs3D(MX_SINT16 FCL_X, MX_SINT16 FCL_Y, MX_SINT16 FCL_Z, MX_UINT8 FCL_DATAMODE);

/*========================================================================*\
   Use :ESP32_RMT1
       :Macro function declarations
\*========================================================================*/
#define MX_RMT_MODE_1 RMT_MODE_TX
#define MX_RMT_TXIDLEEN_1 true
#define MX_RMT_REF1 
#define MX_RMT_TXIDLELVL_1 0
#define MX_RMT_MEMBLKNUM_1 1
#define MX_RMT_RXFILTEREN_1 (0)
#define MX_RMT_TXLOOPEN_1 false
#define MX_RMT_IDLETHRESH_1 (2)
#define MX_RMT_BUFFSZ_1 64
#define MX_RMT_RXFILTERTICKS_1 (0)
#define MX_RMT_TXCARRIEREN_1 false
#define MX_RMT_TXCARRIERFREQ_1 (4800)
#define MX_RMT_PIN_1 2
#define MX_RMT_TXCARRIERDUTY_1 (50)
#define MX_RMT_CLKDIV_1 2
#define MX_RMT_TXCARRIERLVL_1 (1)


/*=----------------------------------------------------------------------=*\
   Use :ESP32_RMT1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifdef MX_CAL_ESP32
  #define FC_CAL_RMT_SetBuffer_1(Idx, St0, Len0, St1, Len1) MX_RMT_BUFFER_1[Idx] = (rmt_item32_t){{{Len0, St0, Len1, St1}}}
#endif

#if defined(MX_BL0058_PINMAP) || defined(MX_BL6390_PINMAP)
  #undef MX_RMT_PIN_1
  #define MX_RMT_PIN_1 2
#endif

MX_UINT8 FC_CAL_RMT_TXBusy_1();
void FC_CAL_RMT_TX_1(MX_UINT8 FCL_WAITWHILECOMPLETE);
void FC_CAL_RMT_Init_1();

/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\includes.c"


/*=----------------------------------------------------------------------=*\
   Use :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define GPIO_BIT_OUT(p,b)	{GPIO##p->MODER&=~(3<<((b)*2));GPIO##p->MODER|=(1<<((b)*2));}
#define GPIO_BIT_VAL(p,b,v)	{if(v)GPIO##p->BSRR = 1<<b; else GPIO##p->BSRR = 1<<(b+16);}

#define GPIO_BIT_VAL_DEF(p,b,v)  GPIO_BIT_VAL(p,b,v)

#if defined(MX_CAL_PIC32)

	#define scNsDelay( nsDelay )                    \
	{                                               \
	   register unsigned int startCnt = _CP0_GET_COUNT(); \
	   register unsigned int waitCnt = nsDelay / ( 1000000000 / (MX_CLK_SPEED / 2) );  \
	   while( _CP0_GET_COUNT() - startCnt < waitCnt ) ; \
	}

#endif


//WS2811 Bit Timings

//Data 1 High Pulse Timing : 1.200000us - 5 Instruction cycles
#define FCM_00000_LED_WS2811__Delay_T1H()  nop(); nop(); nop(); nop(); nop();

//Data 1 Low Pulse Timing : 1.300000us - 6 Instruction cycles
#define FCM_00000_LED_WS2811__Delay_T1L()  nop(); nop(); nop(); nop(); nop(); nop();

//Data 0 High Pulse Timing : 0.500000us - 0 Instruction cycles
#define FCM_00000_LED_WS2811__Delay_T0H() 

//Data 0 Low Pulse Timing : 2.000000us - 9 Instruction cycles
#define FCM_00000_LED_WS2811__Delay_T0L()  nop(); nop(); nop(); nop(); nop(); nop(); nop(); nop(); nop();

#warning WS2811 Timings are less than 10 instructions, timing may be incorrect at the current clock speed
//Data Output High
#if defined(_LATC5) || defined(_LATC_LATC5_POSITION)
#define FCM_00000_LED_WS2811__OutputHigh() LATCbits.LATC5 = 1
#else
#define FCM_00000_LED_WS2811__OutputHigh() PORTCbits.RC5 = 1
#endif
//Data Output Low
#if defined(_LATC5) || defined(_LATC_LATC5_POSITION)
#define FCM_00000_LED_WS2811__OutputLow() LATCbits.LATC5 = 0
#else
#define FCM_00000_LED_WS2811__OutputLow() PORTCbits.RC5 = 0
#endif

