// CRC: 84D9E1FE72EA3BCC519B65499DB4B2BCC2E928A318D32B862581E6BBE90394A0B25640F7F1F25483FD2044B839850E3ADD04A5F8AD9BEEB1823278EF8F2BA19C642ECC0A8F4400287286B72E06ADF20A1FBA30B1432743E9711B8143522C2B69D0B3F66B6CAC63454EB01013AE1576B02F4385EDF948571DB165FDB853C1F062FFC33A8516A88B59914F9C96474CD5D3941031D4715387089415F519F1194457113F070857C4DC23A1FF519F4021F2C693C8374C623C5868549D34A0D5AD11F3FC5C9DE57544828E1B873640C96000612E6E845F27DD72AB1EDE0E6E8CE8F293FC3F53D5103A0873
// REVISION: 3.0
// GUID: 31D70655-56D3-4E9A-8663-E38F90F22403
// DATE: 30\06\2023
// DIR: CAL\ESP\ESP_CAL_TypeDefs.c
/*********************************************************************
 *                  Flowcode CAL TypeDefs File
 *
 * File: ESP_CAL_TypeDefs.c
 *
 * (c) 2018 Matrix TSL.
 * http://www.matrixtsl.com
 *
 * Software License Agreement
 *
 * The software supplied herewith by Matrix TSL (the
 * “Company”) for its Flowcode graphical programming language is
 * intended and supplied to you, the Company’s customer, for use
 * solely and exclusively on the Company's products. The software
 * is owned by the Company, and is protected under applicable
 * copyright laws. All rights are reserved. Any use in violation
 * of the foregoing restrictions may subject the user to criminal
 * sanctions under applicable laws, as well as to civil liability
 * for the breach of the terms and conditions of this licence.
 *
 * THIS SOFTWARE IS PROVIDED IN AN “AS IS” CONDITION. NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED
 * TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. THE COMPANY SHALL NOT,
 * IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL OR
 * CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * Changelog:
 *
 *  date  | by | description
 * -------+----+-----------------------------------------------------
 * 130718 | BR | Created
 *
 */


#include <stdbool.h>

// Preceeds all global variable definitions generated by Flowcode
#define MX_GLOBAL volatile

typedef bool                MX_BOOL;   // Or unsigned char, depending on platform
typedef signed char         MX_SINT8;
typedef short signed int    MX_SINT16;
typedef signed long         MX_SINT32;
typedef unsigned char       MX_UINT8;
typedef short unsigned int  MX_UINT16;
typedef unsigned long       MX_UINT32;
typedef char                MX_CHAR;
typedef char*               MX_STRING; // String pointer

//typedef double       		MX_FLOAT;  // 64-bit Floating point (Real)
typedef float          		MX_FLOAT;  // 32-bit Floating point (Real)

typedef MX_UINT16           MX_UINT;   // Best integer value for the platform, at least 8 bit
typedef MX_SINT16           MX_SINT;

#define MX_FSINGLE float

typedef union
{
  MX_FLOAT  AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union32;

typedef union
{
  MX_UINT16 AsInt;
  MX_UINT8  AsByte[2];
} MX_Union16;




//Example Union Code
//MX_Union32 Test;
//Test.AsLong = 0xFFFFFFFF;
//Test.AsInt[0] = 0xFFFF;
//Test.AsByte[0] = 0xFF;

